path = "cans"

[[definition]]
type = "io.internal.can.zynqps8"
registers = [
    { resource = "zynqps8/can.toml", name = "CAN${index}", base_address = "0x60_0000", address_increment = "0x10_0000" },
]
max_instances = 2
