#include "core/core.h"
#include "platform/reg_access.h"
#include "utils/boot_psi.h"
#include "platform/memory_map.h"
#include "hw_regs/crl_apb.h"
#include "hw_regs/crf_apb.h"

__attribute__((__section__(".hwregs")))
static PSI_IWord const pll_init[] = {
		PSI_SET_REGISTER_BANK(CRL_APB),

		PSI_WRITE_MASKED_32(CRL_APB, PSSYSMON_REF_CTRL, 0x013F3F07U, 0x01012302U),
		PSI_WRITE_MASKED_32(CRL_APB, RST_LPD_IOU2, 0x00000001U, 0x00000001U),

		PSI_WRITE_MASKED_32(CRL_APB, RPLL_CFG, 0xFE7FEDEFU, 0x7E60EC6CU),
		PSI_WRITE_MASKED_32(CRL_APB, RPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, RPLL_CTRL, POST_SRC) |
												HW_REG_FIELD_MASK(CRL_APB, RPLL_CTRL, PRE_SRC) |
												HW_REG_FIELD_MASK(CRL_APB, RPLL_CTRL, DIV2) |
												HW_REG_FIELD_MASK(CRL_APB, RPLL_CTRL, FBDIV),

												HW_REG_ENCODE_ENUM(CRL_APB, RPLL_CTRL, POST_SRC, PS_REF_CLK) |  // PS_REF_CLK 33.3Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, RPLL_CTRL, PRE_SRC, PS_REF_CLK) |     // PS_REF_CLK
												HW_REG_ENCODE_FIELD(CRL_APB, RPLL_CTRL, DIV2, 1) |        // / 2
												HW_REG_ENCODE_FIELD(CRL_APB, RPLL_CTRL, FBDIV, 0x30)      // / 48 = 33.3 * 24 = 800Mhz
												),
		PSI_WRITE_MASKED_32(CRL_APB, RPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, RPLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRL_APB, RPLL_CTRL, BYPASS, 1)),
		PSI_WRITE_MASKED_32(CRL_APB, RPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, RPLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRL_APB, RPLL_CTRL, RESET, 1)),
		PSI_WRITE_MASKED_32(CRL_APB, RPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, RPLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRL_APB, RPLL_CTRL, RESET, 0)),
		PSI_POLL_MASKED_32(CRL_APB, PLL_STATUS, CRL_APB_PLL_STATUS_RPLL_LOCK_MASK),
		PSI_WRITE_MASKED_32(CRL_APB, RPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, RPLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRL_APB, RPLL_CTRL, BYPASS, 0)),
		PSI_WRITE_32(CRL_APB, RPLL_TO_FPD_CTRL,
											 HW_REG_ENCODE_FIELD(CRL_APB, RPLL_TO_FPD_CTRL, DIVISOR0,0x2)), // RPLL_TO_FPD = 400 Mhz

		PSI_WRITE_MASKED_32(CRL_APB, PSSYSMON_REF_CTRL, 0x013F3F07U, 0x01012300U),

		PSI_WRITE_MASKED_32(CRL_APB, IOPLL_CFG, CRL_APB_IOPLL_CFG_USERMASK, 0x7E4B0C82U),
		PSI_WRITE_MASKED_32(CRL_APB, IOPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, IOPLL_CTRL, POST_SRC) |
												HW_REG_FIELD_MASK(CRL_APB, IOPLL_CTRL, PRE_SRC) |
												HW_REG_FIELD_MASK(CRL_APB, IOPLL_CTRL, DIV2) |
												HW_REG_FIELD_MASK(CRL_APB, IOPLL_CTRL, FBDIV),

												HW_REG_ENCODE_ENUM(CRL_APB, IOPLL_CTRL, POST_SRC, PS_REF_CLK) |  // PS_REF_CLK 33.3Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, IOPLL_CTRL, PRE_SRC, PS_REF_CLK) |     // PS_REF_CLK
												HW_REG_ENCODE_FIELD(CRL_APB, IOPLL_CTRL, DIV2, 1) |        // / 2
												HW_REG_ENCODE_FIELD(CRL_APB, IOPLL_CTRL, FBDIV, 0x5A)      // / 90 = 33.3 * 45 = 1500Mhz
		),
		PSI_WRITE_MASKED_32(CRL_APB, IOPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, IOPLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRL_APB, IOPLL_CTRL, BYPASS, 1)),
		PSI_WRITE_MASKED_32(CRL_APB, IOPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, IOPLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRL_APB, IOPLL_CTRL, RESET, 1)),
		PSI_WRITE_MASKED_32(CRL_APB, IOPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, IOPLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRL_APB, IOPLL_CTRL, RESET, 0)),
		PSI_POLL_MASKED_32(CRL_APB, PLL_STATUS, CRL_APB_PLL_STATUS_IOPLL_LOCK_MASK),
		PSI_WRITE_MASKED_32(CRL_APB, IOPLL_CTRL,
												HW_REG_FIELD_MASK(CRL_APB, IOPLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRL_APB, IOPLL_CTRL, BYPASS, 0)),
		PSI_WRITE_32(CRL_APB, IOPLL_TO_FPD_CTRL,
												HW_REG_ENCODE_FIELD(CRL_APB, IOPLL_TO_FPD_CTRL, DIVISOR0,0x3)), // IOPLL_TO_FPD = 500 Mhz

		PSI_SET_REGISTER_BANK(CRF_APB),
		PSI_WRITE_MASKED_32(CRF_APB, APLL_CFG, 0xFE7FEDEFU, 0x7E4B0C62U),
		PSI_WRITE_MASKED_32(CRF_APB, APLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, APLL_CTRL, POST_SRC) |
												HW_REG_FIELD_MASK(CRF_APB, APLL_CTRL, PRE_SRC) |
												HW_REG_FIELD_MASK(CRF_APB, APLL_CTRL, DIV2) |
												HW_REG_FIELD_MASK(CRF_APB, APLL_CTRL, FBDIV),
												HW_REG_ENCODE_ENUM(CRF_APB, APLL_CTRL, POST_SRC, PS_REF_CLK) |
												HW_REG_ENCODE_ENUM(CRF_APB, APLL_CTRL, PRE_SRC, PS_REF_CLK) |
												HW_REG_ENCODE_FIELD(CRF_APB, APLL_CTRL, DIV2, 1)|				// / 2
												HW_REG_ENCODE_FIELD(CRF_APB, APLL_CTRL, FBDIV, 0x48) ), // / 72 = 33.3 * 36 = 1200Mhz
		PSI_WRITE_MASKED_32(CRF_APB, APLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, APLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRF_APB, APLL_CTRL, BYPASS, 1)),
		PSI_WRITE_MASKED_32(CRF_APB, APLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, APLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRF_APB, APLL_CTRL, RESET, 1)),
		PSI_WRITE_MASKED_32(CRF_APB, APLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, APLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRF_APB, APLL_CTRL, RESET, 0)),
		PSI_POLL_MASKED_32(CRF_APB, PLL_STATUS, 0x00000001U),
		PSI_WRITE_MASKED_32(CRF_APB, APLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, APLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRF_APB, APLL_CTRL, BYPASS, 0)),
		PSI_WRITE_32(CRF_APB, APLL_TO_LPD_CTRL,
								 				HW_REG_ENCODE_FIELD(CRF_APB, APLL_TO_LPD_CTRL, DIVISOR0,0x3)), // APLL_TO_LPD = 400 Mhz

		PSI_WRITE_MASKED_32(CRF_APB, DPLL_CFG, 0xFE7FEDEFU, 0x7E4B0C62U),
		PSI_WRITE_MASKED_32(CRF_APB, DPLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, DPLL_CTRL, POST_SRC) |
												HW_REG_FIELD_MASK(CRF_APB, DPLL_CTRL, PRE_SRC) |
												HW_REG_FIELD_MASK(CRF_APB, DPLL_CTRL, DIV2) |
												HW_REG_FIELD_MASK(CRF_APB, DPLL_CTRL, FBDIV),
												HW_REG_ENCODE_ENUM(CRF_APB, DPLL_CTRL, POST_SRC, PS_REF_CLK) |
												HW_REG_ENCODE_ENUM(CRF_APB, DPLL_CTRL, PRE_SRC, PS_REF_CLK) |
												HW_REG_ENCODE_FIELD(CRF_APB, DPLL_CTRL, DIV2, 1)|				// / 2
												HW_REG_ENCODE_FIELD(CRF_APB, DPLL_CTRL, FBDIV, 0x48) ), // / 72 = 33.3 * 36 = 1200Mhz
		PSI_WRITE_MASKED_32(CRF_APB, DPLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, DPLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRF_APB, DPLL_CTRL, BYPASS, 1)),
		PSI_WRITE_MASKED_32(CRF_APB, DPLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, DPLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRF_APB, DPLL_CTRL, RESET, 1)),
		PSI_WRITE_MASKED_32(CRF_APB, DPLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, DPLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRF_APB, DPLL_CTRL, RESET, 0)),
		PSI_POLL_MASKED_32(CRF_APB, PLL_STATUS, 0x00000002U),
		PSI_WRITE_MASKED_32(CRF_APB, DPLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, DPLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRF_APB, DPLL_CTRL, BYPASS, 0)),
		PSI_WRITE_32(CRF_APB, DPLL_TO_LPD_CTRL,
								 				HW_REG_ENCODE_FIELD(CRF_APB, DPLL_TO_LPD_CTRL, DIVISOR0,0x3)), // DPLL_TO_LPD = 400 Mhz

		PSI_WRITE_MASKED_32(CRF_APB, VPLL_CFG, 0xFE7FEDEFU, 0x7E4B0C82U),
		PSI_WRITE_32(CRF_APB, VPLL_CTRL,
												HW_REG_ENCODE_ENUM(CRF_APB, VPLL_CTRL, POST_SRC, PS_REF_CLK) |
												HW_REG_ENCODE_ENUM(CRF_APB, VPLL_CTRL, PRE_SRC, PS_REF_CLK) |
												HW_REG_ENCODE_FIELD(CRF_APB, VPLL_CTRL, DIV2, 1)|				// / 2
												HW_REG_ENCODE_FIELD(CRF_APB, VPLL_CTRL, FBDIV, 90) |  // / 90 = 33.3 * 45 = 1500Mhz
												HW_REG_ENCODE_FIELD(CRF_APB, VPLL_CTRL, BYPASS, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, VPLL_CTRL, RESET, 1)
												),
		PSI_DELAY_US(20),
		PSI_WRITE_MASKED_32(CRF_APB, VPLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, VPLL_CTRL, RESET),
												HW_REG_ENCODE_FIELD(CRF_APB, VPLL_CTRL, RESET, 0)),
		PSI_POLL_MASKED_32(CRF_APB, PLL_STATUS, 0x00000004U),
		PSI_WRITE_MASKED_32(CRF_APB, VPLL_CTRL,
												HW_REG_FIELD_MASK(CRF_APB, VPLL_CTRL, BYPASS),
												HW_REG_ENCODE_FIELD(CRF_APB, VPLL_CTRL, BYPASS, 0)),
		PSI_WRITE_32(CRF_APB, VPLL_TO_LPD_CTRL,
								 HW_REG_ENCODE_FIELD(CRF_APB, VPLL_TO_LPD_CTRL, DIVISOR0,0x3)), // VPLL_TO_LPD = 500 Mhz

		PSI_END_PROGRAM
};
void pllRunInitProgram() {
	psi_RunRegisterProgram(pll_init);
}