path = "libs"

[[definition]]
type = "library.cadt"
depends = ["core", "dbg", "memory", "multi_core", "platform"]

[[definition]]
type = "library.core"

[[definition]]
type = "library.data_binify"
cpus = "host"
depends = ["cadt", "core", "dbg", "memory", "multi_core", "utils", "vfile", "tiny_stl"]

[[definition]]
type = "library.data_utils"
cpus = "a53,host"
depends = ["core", "dbg", "memory", "multi_core", "platform", "vfile"]

[[definition]]
type = "library.dbg"
depends = ["core", "platform"]

[[definition]]
type = "library.gfx_image"
cpus = "a53,host"
depends = ["core", "dbg", "memory", "multi_core", "platform", "tiny_image_format", "musl_math"]

[[definition]]
type = "library.gfxdebug"
cpus = "a53,r5f,pmu"
depends = ["core", "dbg", "utils"]

[[definition]]
type = "library.host_os"
cpus = "host"
depends = ["core", "dbg", "memory", "platform", "vfile"]

[[definition]]
type = "library.luau"
cpus = "host"

[[definition]]
type = "library.luau_vm"
cpus = "a53"
depends = ["core", "dbg"]

[[definition]]
type = "library.memory"
depends = ["core", "dbg", "multi_core", "platform"]

[[definition]]
type = "library.multi_core"
depends = ["core", "platform"]

[[definition]]
type = "library.musl_math"
cpus = "a53,r5f"
depends = ["core", "dbg", "osservices", "platform"]

[[definition]]
type = "library.osservices"
cpus = "a53,r5f,pmu"
depends = ["core", "dbg", "platform", "utils"]

[[definition]]
type = "library.platform"
depends = ["core", "dbg"]

[[definition]]
type = "library.tiny_image_format"
depends = ["core", "platform", "musl_math"]

[[definition]]
type = "library.tiny_stl"
depends = ["core", "dbg", "multi_core", "platform"]

[[definition]]
type = "library.utils"
depends = ["core", "dbg", "platform"]

[[definition]]
type = "library.vfile"
depends = ["core", "dbg"]

[[definition]]
type = "library.vfile_memory"
depends = ["core", "dbg", "vfile", "memory"]

