[[definition]]
name = "bin2c"
type = "program.bin2c"
software = "programs/bin2c/bin2c.toml"
cpus = "host"

[[definition]]
name = "image_convert"
type = "program.image_convert"
software = "programs/image_convert/image_convert.toml"
cpus = "host"
