description = "SerDes Control and Debug"
[[register]]
  name = "REG_CTRL"
  type = "mixed"
  width = 32
  description = "Miscellaneous control functions for SIOU"
  default = "0x00000000"
  offset = "0x00000000"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "ro"
  [[register.field]]
    name = "SLVERR_ENABLE"
    bits = "0"
    type = "rw"
    shortdesc = '''By default, invalid address requests are ignored.'''
    longdesc = '''However, a maskable interrupt exsists. By enabling this slverr_enable invalid address requests cause a slverr to occur. Enable/Disable SLVERR during address decode failure. 0: SLVERR is disabled. For request address: Writes are ignored. Read returns 0. 1: SLVERR is enabled. For requestes address, SLVERR is asserted. Writes are ignored. Read returns 0.'''
[[register]]
  name = "IR_STATUS"
  type = "mixed"
  width = 32
  description = "Interrupt Status Register for intrN. This is a sticky register that holds the value of the interrupt until cleared by a value of 1."
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "ro"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wtc"
[[register]]
  name = "IR_MASK"
  type = "ro"
  width = 32
  description = "Interrupt Mask Register for intrN. This is a read-only location and can be atomically altered by either the IDR or the IER."
  default = "0x00000001"
  offset = "0x00000008"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "ro"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "ro"
[[register]]
  name = "IR_ENABLE"
  type = "mixed"
  width = 32
  description = "Interrupt Enable Register. A write of to this location will unmask the interrupt. (IMR: 0)"
  default = "0x00000000"
  offset = "0x0000000C"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "ro"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
[[register]]
  name = "IR_DISABLE"
  type = "mixed"
  width = 32
  description = "Interrupt Disable Register. A write of one to this location will mask the interrupt. (IMR: 1)"
  default = "0x00000000"
  offset = "0x00000010"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "ro"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
[[register]]
  name = "SATA_MISC_CTRL"
  type = "mixed"
  width = 32
  description = "Misc Contorls for SATA.This register may only be modified during bootup (while SATA block is disabled)"
  default = "0x00000000"
  offset = "0x00000100"
  [[register.field]]
    name = "RESERVED"
    bits = "31:2"
    type = "ro"
  [[register.field]]
    name = "SATA_PM_CLK_SEL"
    bits = "1:0"
    type = "rw"
[[register]]
  name = "CRX_CTRL"
  type = "mixed"
  width = 32
  description = "crx_ctrl"
  default = "0x00000000"
  offset = "0x00000410"
  [[register.field]]
    name = "RESERVED"
    bits = "31:2"
    type = "ro"
  [[register.field]]
    name = "REFCLK_SEL"
    bits = "1:0"
    type = "rw"
[[register]]
  name = "DP_STC_CLKCTRL"
  type = "mixed"
  width = 32
  description = "dp_stc_ref_clk control register"
  default = "0x00000001"
  offset = "0x00000430"
  [[register.field]]
    name = "RESERVED"
    bits = "31:11"
    type = "ro"
  [[register.field]]
    name = "REFSEL"
    bits = "10"
    type = "rw"
  [[register.field]]
    name = "LANESEL"
    bits = "9:8"
    type = "rw"
  [[register.field]]
    name = "UPTOG"
    bits = "7"
    type = "rw"
  [[register.field]]
    name = "DIVISOR"
    bits = "6:1"
    type = "rw"
  [[register.field]]
    name = "SOFT_RST"
    bits = "0"
    type = "rw"
