description = "S_AXI_HP0_FPD QoS and FIFO Configuration"
[[register]]
  name = "RDCTRL"
  type = "mixed"
  width = 32
  description = "Read Channel Control Register"
  default = "0x000003B0"
  offset = "0x00000000"
  [[register.field]]
    name = "RESERVED"
    bits = "31:11"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "PAUSE"
    bits = "3"
    type = "rw"
    shortdesc = '''Pause the issuing of new read commands to the PS-side.'''
    longdesc = '''Existing outstanding commands will continue to be processed.'''
  [[register.field]]
    name = "FABRIC_QOS_EN"
    bits = "2"
    type = "rw"
    shortdesc = '''Enable control of QoS from the fabric 0: The QoS bits are derived from APB register, AFIFM_RDQoS.'''
    longdesc = '''staticQoS 1: The QoS bits are dynamically driven from the fabric input, axds_arQoS[3:0]'''
  [[register.field]]
    name = "FABRIC_WIDTH"
    bits = "1:0"
    type = "rw"
    shortdesc = '''Configures the Read Channel Fabric interface width.'''
    longdesc = '''2'b11: Reserved 2'b10: 32-bit Fabric 2'b01: 64-bit enabled 2'b00: 128-bit enabled'''
[[register]]
  name = "RDISSUE"
  type = "mixed"
  width = 32
  description = "Read Issuing Capability Register"
  default = "0x00000007"
  offset = "0x00000004"
  [[register.field]]
    name = "RESERVED"
    bits = "31:5"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "CAPABILITY"
    bits = "3:0"
    type = "rw"
[[register]]
  name = "RDQOS"
  type = "mixed"
  width = 32
  description = "QoS Read Channel Register"
  default = "0x00000007"
  offset = "0x00000008"
  [[register.field]]
    name = "RESERVED"
    bits = "31:4"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "VALUE"
    bits = "3:0"
    type = "rw"
[[register]]
  name = "RDDEBUG"
  type = "mixed"
  width = 32
  description = "Read Channel Debug Register"
  default = "0x40000000"
  offset = "0x00000010"
  [[register.field]]
    name = "AFI_VERSION"
    bits = "31:30"
    type = "ro"
  [[register.field]]
    name = "RESERVED"
    bits = "29:6"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
[[register]]
  name = "WRCTRL"
  type = "mixed"
  width = 32
  description = "Write Channel Control Register"
  default = "0x000003B0"
  offset = "0x00000014"
  [[register.field]]
    name = "RESERVED"
    bits = "31:13"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "WR_RELEASE_MODE"
    bits = "12"
    type = "rw"
    shortdesc = '''Mode of Write Command Release.'''
    longdesc = '''1'b0: Release Wr Command on 'Wlast' enqueue into Write Data FIFO (Or, in the case of longer AXI4 style bursts, release when 16 beats are enqueued in to the Write Data FIFO) 1'b1: Release write command immediately it becomes available'''
  [[register.field]]
    name = "RESERVED"
    bits = "11"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "PAUSE"
    bits = "3"
    type = "rw"
    shortdesc = '''Pause the issuing of new write commands to the PS-side.'''
    longdesc = '''Existing write commands will continue to be processed.'''
  [[register.field]]
    name = "FABRIC_QOS_EN"
    bits = "2"
    type = "rw"
    shortdesc = '''Enable control of QoS from the fabric 0: The QoS bits are derived from APB register, AFIFM_WRQoS.'''
    longdesc = '''staticQoS 1: The QoS bits are dynamically driven from the fabric input, axds_awQoS[3:0]'''
  [[register.field]]
    name = "FABRIC_WIDTH"
    bits = "1:0"
    type = "rw"
    shortdesc = '''Configures the Write Channel Fabric interface width.'''
    longdesc = '''2'b11: Reserved 2'b10: 32-bit Fabric 2'b01: 64-bit enabled 2'b00: 128-bit enabled'''
[[register]]
  name = "WRISSUE"
  type = "mixed"
  width = 32
  description = "Write Issuing Capability Register"
  default = "0x00000007"
  offset = "0x00000018"
  [[register.field]]
    name = "RESERVED"
    bits = "31:4"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "CAPABILITY"
    bits = "3:0"
    type = "rw"
[[register]]
  name = "WRQOS"
  type = "mixed"
  width = 32
  description = "QoS Write Channel Register"
  default = "0x00000007"
  offset = "0x0000001C"
  [[register.field]]
    name = "RESERVED"
    bits = "31:4"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "VALUE"
    bits = "3:0"
    type = "rw"
[[register]]
  name = "I_STS"
  type = "mixed"
  width = 32
  description = "Interrupt Status Register"
  default = "0x00000000"
  offset = "0x00000E00"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "INVALID_APB"
    bits = "0"
    type = "wtc"
[[register]]
  name = "I_EN"
  type = "mixed"
  width = 32
  description = "Interrupt Enable"
  default = "0x00000000"
  offset = "0x00000E04"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "INVALID_APB"
    bits = "0"
    type = "wo"
[[register]]
  name = "I_DIS"
  type = "mixed"
  width = 32
  description = "Interrupt Disable"
  default = "0x00000000"
  offset = "0x00000E08"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "INVALID_APB"
    bits = "0"
    type = "wo"
[[register]]
  name = "I_MASK"
  type = "mixed"
  width = 32
  description = "Interrupt Mask"
  default = "0x00000001"
  offset = "0x00000E0C"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "INVALID_APB"
    bits = "0"
    type = "ro"
[[register]]
  name = "CONTROL"
  type = "mixed"
  width = 32
  description = "General Control Register"
  default = "0x00000000"
  offset = "0x00000F04"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
    shortdesc = '''RESERVED.'''
    longdesc = '''Return 0 when read. Writes ignored.'''
  [[register.field]]
    name = "APB_ERR_RESP"
    bits = "0"
    type = "rw"
[[register]]
  name = "SAFETY_CHK"
  type = "rw"
  width = 32
  description = "Safety endpoint connectivity check Register"
  default = "0x00000000"
  offset = "0x00000F0C"
  [[register.field]]
    name = "CHK_VAL"
    bits = "31:0"
    type = "rw"
