actions = [
    "make_config",
    "sbt_run",
    "src",
    "read_verilog_top"
]

[[process]]
name = 'make_config'
processor = 'toml'
filename = 'config.toml'
parameters = [
    "reset_clocks"
]

[[process]]
name = 'sbt_run'
processor = 'sbt'
main_scala = "resetti.scala"
with_build_sbt = true
args = '+runMain Resetti config.toml .. ${name}'

[[process]]
name = 'src'
processor = 'sources'
sources = [{ file = "${outPath}/${name}.v", language = "verilog" }]

[[process]]
name = 'read_verilog_top'
processor = 'read_verilog_top'
source = "${outPath}/${name}.v"
