description = "E-EDID registers"

[[register]]
name = "HEADER"
width = 64
description = "Must equal 0x00FF_FFFF_FFFF_FF00"
offset = "0x0"
[[register]]
name = "ID_MANUFACTORER_NAME_0"
width = 8
description = "5 bit character #1 and 2 bits of #2"
offset = "0x8"
[[register.field]]
name = "CHAR_1"
bits = "6:2"
type = "ro"
[[register.field]]
name = "CHAR_2_HI"
bits = "1:0"
type = "ro"
[[register]]
name = "ID_MANUFACTORER_NAME_1"
width = 8
description = "3 bit character #2 and 5 bits of #3"
offset = "0x9"
[[register.field]]
name = "CHAR_2_LO"
bits = "7:5"
type = "ro"
[[register.field]]
name = "CHAR_3"
bits = "4:0"
type = "ro"

[[register]]
name = "ID_PRODUCT_CODE_0"
width = 8
description = "LSB of Product code"
offset = "0xA"
[[register]]
name = "ID_PRODUCT_CODE_1"
width = 8
description = "MSB of Product code"
offset = "0xB"

[[register]]
name = "ID_SERIAL_NUMBER"
width = 32
description = "Serial Number"
offset = "0xC"

[[register]]
name = "MANUFACTURE_WEEK"
width = 8
description = "Week of manufacture"
offset = "0x10"

[[register]]
name = "MANUFACTURE_YEAR"
width = 8
description = "Year of manufacture"
offset = "0x11"

[[register]]
name = "DISPLAY_PORT_MAJOR_VERSION"
width = 8
description = "Display port major version"
offset = "0x12"

[[register]]
name = "DISPLAY_PORT_MINOR_VERSION"
width = 8
description = "Display port minor version"
offset = "0x13"

[[register]]
name = "VIDEO_INPUT_DEFINITION"
width = 8
description = "Video Input Defination Table 3.6.1"
offset = "0x14"
[[register.field]]
name = "DIGITAL_VIDEO"
bits = 7
type = "ro"
[[register.field]]
name = "ANALOG_SIGNAL_LEVEL"
bits = "6:5"
type = "ro"
[[register.field.enum]]
name = "0_700_0_300_1_000"
value = 0
[[register.field.enum]]
name = "0_714_0_2860_1_000"
value = 1
[[register.field.enum]]
name = "1_000_0_400_1_400"
value = 2
[[register.field.enum]]
name = "0_700_0_000_0_700"
value = 3
[[register.field]]
name = "ANALOG_BLANK_TO_BLACK_SETUP"
bits = 4
[[register.field]]
name = "ANALOG_SEPERATE_SYNC_H_V_SUPPORTED"
bits = 3
[[register.field]]
name = "ANALOG_COMPOSITE_SYNC_ON_HORIZONTAL_SUPPORTED"
bits = 2
[[register.field]]
name = "ANALOG_COMPOSITE_SYNC_ON_GREEN_SUPPORTED"
bits = 1
[[register.field]]
name = "ANALOG_SERRATION_ON_VERTICAL_SYNC_SUPPORTED"
bits = 0

[[register.field]]
name = "DIGITAL_COLOUR_BIT_DEPTH"
bits = "6:4"
[[register.field.enum]]
name = "UNDEFINED"
value = 0
[[register.field.enum]]
name = "6_BITS_PER_PRIMARY_COLOUR"
value = 1
[[register.field.enum]]
name = "8_BITS_PER_PRIMARY_COLOUR"
value = 2
[[register.field.enum]]
name = "10_BITS_PER_PRIMARY_COLOUR"
value = 3
[[register.field.enum]]
name = "12_BITS_PER_PRIMARY_COLOUR"
value = 4
[[register.field.enum]]
name = "14_BITS_PER_PRIMARY_COLOUR"
value = 5
[[register.field.enum]]
name = "16_BITS_PER_PRIMARY_COLOUR"
value = 6
[[register.field]]
name = "DIGITAL_VIDEO_INTERFACE_SUPPORT"
bits = "3:0"
[[register.field.enum]]
name = "NOT_DEFINED"
value = 0
[[register.field.enum]]
name = "DVI_SUPPORTED"
value = 1
[[register.field.enum]]
name = "HDMI_A_SUPPORTED"
value = 2
[[register.field.enum]]
name = "HDMI_B_SUPPORTED"
value = 3
[[register.field.enum]]
name = "MDDI_SUPPORTED"
value = 4
[[register.field.enum]]
name = "DISPLAY_PORT_SUPPORTED"
value = 5

[[register]]
name = "HORIZONTAL_DIMS"
width = 8
description = "Horizontal Screen Size of Aspect Ratio Table 3.12"
offset = "0x15"
[[register]]
name = "VERTICAL_DIMS"
width = 8
description = "Vertical Screen Size or Aspect Ratio Table 3.12"
offset = "0x16"

[[register]]
name = "GAMMA"
width = 8
description = "Display Transfer Characteristics Table 3.13"
offset = "0x17"

[[register]]
name = "FEATURE_SUPPORT"
width = 8
description = "Feature support Table 3.14"
offset = "0x18"
[[register.field]]
name = "STANDBY_SUPPORTED"
bits = 7
[[register.field]]
name = "SUSPEND_SUPPORTED"
bits = 6
[[register.field]]
name = "ACTIVE_OFF_SUPPORTED"
bits = 5
[[register.field]]
name = "DISPLAY_COLOUR_TYPE"
bits = "4:3"
description = "If bit 7 or address 0x14 == 0"
[[register.field.enum]]
name = "GREYSCALE"
value = 0
[[register.field.enum]]
name = "RGB_COLOUR"
value = 1
[[register.field.enum]]
name = "NON_RGB_COLOUR"
value = 2
[[register.field.enum]]
name = "UNDEFINED"
value = 3
[[register.field]]
name = "COLOUR_FORMATS_SUPPORTED"
bits = "4:3"
description = "If bit 7 or address 0x14 == 1"
[[register.field.enum]]
name = "RGB_444"
value = 0
[[register.field.enum]]
name = "RGB_444_YCRCB444"
value = 1
[[register.field.enum]]
name = "RGB_444_YCRCB422"
value = 2
[[register.field.enum]]
name = "RGB_444_YCRCB444_YCRCB422"
value = 3

[[register.field]]
name = "SRGB_STANDARD_IS_DEFAULT"
bits = 2
[[register.field]]
name = "PTM_IS_NATIVE"
bits = 1
[[register.field]]
name = "CONTINUOUS_FREQUENCY"
bits = 0

[[register]]
name = "CHROMATICITY_RG_LOWBUTS"
width = 8
description = "Chromaticity Table 3.16"
offset = "0x19"
[[register]]
name = "CHROMATICITY_BW_LOWBUTS"
width = 8
description = "Chromaticity Table 3.16"
offset = "0x1A"
[[register]]
name = "CHROMATICITY_RED_X"
width = 8
description = "Chromaticity Table 3.14"
offset = "0x1B"
[[register]]
name = "CHROMATICITY_RED_Y"
width = 8
description = "Chromaticity Table 3.14"
offset = "0x1C"
[[register]]
name = "CHROMATICITY_GREEN_X"
width = 8
description = "Chromaticity Table 3.14"
offset = "0x1D"
[[register]]
name = "CHROMATICITY_GREEN_Y"
width = 8
description = "Chromaticity Table 3.14"
offset = "0x1E"
[[register]]
name = "CHROMATICITY_BLUE_X"
width = 8
description = "Chromaticity Table 3.14"
offset = "0x1F"
[[register]]
name = "CHROMATICITY_BLUE_Y"
width = 8
description = "Chromaticity Table 3.14"
offset = "0x20"
[[register]]
name = "CHROMATICITY_WHITE_X"
width = 8
description = "Chromaticity Table 3.14"
offset = "0x21"
[[register]]
name = "CHROMATICITY_WHITE_Y"
width = 8
description = "Chromaticity Table 3.14"
offset = "0x22"

[[register]]
name = "ESTABLISHED_TIMING_1"
width = 8
description = "Established timings Table 3.18"
offset = "0x23"
[[register.field]]
name = "720_400_70HZ"
bits = 7
[[register.field]]
name = "720_400_88HZ"
bits = 6
[[register.field]]
name = "640_480_60HZ"
bits = 5
[[register.field]]
name = "640_480_67HZ"
bits = 4
[[register.field]]
name = "640_480_72HZ"
bits = 3
[[register.field]]
name = "640_480_75HZ"
bits = 2
[[register.field]]
name = "800_600_56HZ"
bits = 1
[[register.field]]
name = "800_600_60HZ"
bits = 0
[[register]]
name = "ESTABLISHED_TIMING_2"
width = 8
description = "Established timings Table 3.18"
offset = "0x24"
[[register.field]]
name = "800_600_72HZ"
bits = 7
[[register.field]]
name = "800_600_75HZ"
bits = 6
[[register.field]]
name = "832_624_75HZ"
bits = 5
[[register.field]]
name = "1024_768_87HZ_I"
bits = 4
[[register.field]]
name = "1024_768_60HZ"
bits = 3
[[register.field]]
name = "1024_768_70HZ"
bits = 2
[[register.field]]
name = "1024_768_75HZ"
bits = 1
[[register.field]]
name = "1280_1024_75HZ"
bits = 0
[[register]]
name = "ESTABLISHED_TIMING_3"
width = 8
description = "Established timings Table 3.18"
offset = "0x25"
[[register.field]]
name = "1152_870_75HZ"
bits = 7

[[register]]
name = "STANDARD_TIMING_1"
width = 8
description = "Standard timings Table 3.19"
offset = "0x26"
[[register]]
name = "STANDARD_TIMING_1_AR"
width = 8
description = "Standard timings Table 3.19"
offset = "0x27"
[[register.field]]
name = "IMAGE_ASPECT_RATIO"
bits = "7:6"
[[register.field.enum]]
name = "16_10"
value = 0
[[register.field.enum]]
name = "4_3"
value = 1
[[register.field.enum]]
name = "5_4"
value = 2
[[register.field.enum]]
name = "16_9"
value = 3
[[register.field]]
name = "FIELD_REFRESH_RATE"
bits = "5:0"

[[register]]
name = "DTD_PIXEL_CLOCK_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x36"
[[register]]
name = "DTD_PIXEL_CLOCK_MSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x37"
[[register]]
name = "DTD_HORIZONTAL_ADDRESSABLE_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x38"
[[register]]
name = "DTD_HORIZONTAL_BLANKING_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x39"
[[register]]
name = "DTD_HA_HB_MSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x3A"
[[register.field]]
name = "HA_MSB"
bits = "7:4"
[[register.field]]
name = "HB_MSB"
bits = "3:0"
[[register]]
name = "DTD_VERTICAL_ADDRESSABLE_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x3B"
[[register]]
name = "DTD_VERTICAL_BLANKING_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x3C"
[[register]]
name = "DTD_VA_VB_MSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x3D"
[[register.field]]
name = "VA_MSB"
bits = "7:4"
[[register.field]]
name = "VB_MSB"
bits = "3:0"
[[register]]
name = "DTD_HORIZONTAL_FRONT_PORCH_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x3E"
[[register]]
name = "DTD_HORIZONTAL_SYNC_PULSE_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x3F"
[[register]]
name = "DTD_VERTICAL_FRONT_PORCH_VERTICAL_SYNC_PULSE_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x40"
[[register.field]]
name = "VFP_LSB"
bits = "7:4"
[[register.field]]
name = "VSP_LSB"
bits = "3:0"
[[register]]
name = "DTD_HFP_HSP_VFP_VSP_MSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x41"
[[register.field]]
name = "HFP_MSB"
bits = "7:6"
[[register.field]]
name = "HSP_MSB"
bits = "5:4"
[[register.field]]
name = "VFP_MSB"
bits = "3:2"
[[register.field]]
name = "VSP_MSB"
bits = "1:0"
[[register]]
name = "DTD_HORIZONTAL_ADDRESSABLE_MM_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x42"
[[register]]
name = "DTD_VERTICAL_ADDRESSABLE_MM_LSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x43"
[[register]]
name = "DTD_HAMM_VAMM_MSB_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x44"
[[register.field]]
name = "HAMM_MSB"
bits = "7:4"
[[register.field]]
name = "VAMM_MSB"
bits = "3:0"
[[register]]
name = "DTD_HORIZONTAL_BORDER_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x45"
[[register]]
name = "DTD_VERTICAL_BORDER_1"
width = 8
description = "Detailed Timing Table 3.21"
offset = "0x46"
[[register]]
name = "DTD_FLAGS_1"
width = 8
description = "Detailed Timing Table 3.22"
offset = "0x47"
[[register.field]]
name = "INTERLACED"
bits = 7
[[register.field]]
name = "STEREO_MSB"
bits = "6:5"
[[register.field]]
name = "SYNC"
bits = "4:3"
[[register.field.enum]]
name = "ANALOG_COMPOSITE_SYNC"
value = 0
[[register.field.enum]]
name = "ANALOG_BIPOLAR_COMPOSITE_SYNC"
value = 1
[[register.field.enum]]
name = "DIGITAL_COMPOSITE_SYNC"
value = 2
[[register.field.enum]]
name = "DIGITAL_SEPERATE_SYNC"
value = 3
[[register.field]]
name = "SERRATIONS_OR_DIGITAL_SEPERATE_SYNC_IS_POSITIVE"
bits = 2
[[register.field]]
name = "DIGITAL_HORIZONTAL_SYNC_IS_POSITIVE"
bits = 1
[[register.field]]
name = "ANALOG_SYNC_ON_RGB"
bits = 1
[[register.field]]
name = "STEREO_LSB"
bits = 0






