actions = [
    "make_config",
    "sbt_run",
    "src",
    "read_verilog_top"
]

[parameters]
size_in_bytes = 1024
bits_per_byte = 8
data_width = 32
address_width = 32


[[process]]
name = 'make_config'
processor = 'toml'
filename = 'config.toml'
parameters = [
    "size_in_bytes",
    "bits_per_byte",
    "data_width",
    "address_width"
]

[[process]]
name = 'sbt_run'
processor = 'sbt'
main_scala = "pmb_bram.scala"
with_build_sbt = true
args = '+runMain PmbBram config.toml .. ${name}'

[[process]]
name = 'src'
processor = 'sources'
sources = [{ file = "${name}.v", language = "verilog" }]

[[process]]
name = 'read_verilog_top'
processor = 'read_verilog_top'
source = "${name}"
