actions = [
    "make_config",
    "sbt_run",
    "src",
    "read_verilog_top"
]

[[process]]
name = 'make_config'
processor = 'toml'
filename = 'config.toml'
parameters = [
    "bus_data_width",
    "bus_address_width",
    "consumers",
    "use_slave_error"
]

[[process]]
name = 'sbt_run'
processor = 'sbt'
main_scala = "advanced_peripheral_bus.scala"
with_build_sbt = true
args = '+runMain AdvancedPeripheralBus config.toml .. ${name}'
path_op = 'push'

[[process]]
name = 'src'
processor = 'sources'
sources = [{ file = "${name}.v", language = "verilog" }]


[[process]]
name = 'read_verilog_top'
processor = 'read_verilog_top'
source = "${name}"
