description = "PCIe Bridge - Egress Addr Translation 0"
[[bank]]
  name = "AXIPCIE_EGRESS0"
  address = "0xfd0e0c00"
[[bank]]
  name = "AXIPCIE_EGRESS1"
  address = "0xfd0e0c20"
[[bank]]
  name = "AXIPCIE_EGRESS2"
  address = "0xfd0e0c40"
[[bank]]
  name = "AXIPCIE_EGRESS3"
  address = "0xfd0e0c60"
[[bank]]
  name = "AXIPCIE_EGRESS4"
  address = "0xfd0e0c80"
[[bank]]
  name = "AXIPCIE_EGRESS5"
  address = "0xfd0e0ca0"
[[bank]]
  name = "AXIPCIE_EGRESS6"
  address = "0xfd0e0cc0"
[[bank]]
  name = "AXIPCIE_EGRESS7"
  address = "0xfd0e0ce0"
[[register]]
  name = "TRAN_EGRESS_CAPABILITIES"
  type = "ro"
  width = 32
  description = "Egress AXI Translation - Capabilities"
  default = "0x1F0C0001"
  offset = "0x00000000"
  [[register.field]]
    name = "EGRESS_SIZE_MAX"
    bits = "31:24"
    type = "ro"
    shortdesc = '''* egress_size supports values between 0 and egress_size_max.'''
    longdesc = '''* Maximum translation size is 2^(egress_size_offset+egress_size_max).'''
  [[register.field]]
    name = "EGRESS_SIZE_OFFSET"
    bits = "23:16"
    type = "ro"
  [[register.field]]
    name = "RESERVED"
    bits = "15:1"
    type = "ro"
  [[register.field]]
    name = "EGRESS_PRESENT"
    bits = "0"
    type = "ro"
[[register]]
  name = "TRAN_EGRESS_STATUS"
  type = "ro"
  width = 32
  description = "Egress AXI Translation - Status"
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "RESERVED"
    bits = "31:25"
    type = "ro"
  [[register.field]]
    name = "WR_PENDING_CTR"
    bits = "24:16"
    type = "ro"
    shortdesc = '''Number of write transactions outstanding for this translation.'''
    longdesc = '''There cannot be more translations outstanding than the number of simultaneously outstanding transactions supported by the Expresso DMA Core (which is always <512 transactions), so the Expresso DMA Core does not need to flow control requests due to this field.'''
  [[register.field]]
    name = "RESERVED"
    bits = "15:9"
    type = "ro"
  [[register.field]]
    name = "RD_PENDING_CTR"
    bits = "8:0"
    type = "ro"
    shortdesc = '''Number of read transactions outstanding for this translation.'''
    longdesc = '''There cannot be more translations outstanding than the number of simultaneously outstanding transactions supported by the Expresso DMA Core (which is always <512 transactions), so the Expresso DMA Core does not need to flow control requests due to this field.'''
[[register]]
  name = "TRAN_EGRESS_CONTROL"
  type = "mixed"
  width = 32
  description = "Egress AXI Translation - Control"
  default = "0x00000000"
  offset = "0x00000008"
  [[register.field]]
    name = "EGRESS_ATTR_W"
    bits = "31:28"
    type = "rw"
    shortdesc = '''Egress Write Attribute Override.'''
    longdesc = '''When egress_attr_enable == 1, the PCIe attributes {ID Based Ordering, Relaxed Ordering, No Snoop} are set to egress_attr_w[2:0] when forwarding write transactions hitting this translation to PCIe. When egress_attr_enable == 0, PCIe attributes are all set to 0 when forwarding write transactions hitting this translation to PCIe. Attributes which are not allowed to be set due to PCI Express Configuration Register enable functionality will be cleared before the transaction is forwarded to PCIe.'''
  [[register.field]]
    name = "EGRESS_ATTR_R"
    bits = "27:24"
    type = "rw"
    shortdesc = '''Egress Read Attribute Override.'''
    longdesc = '''When egress_attr_enable == 1, the PCIe attributes {ID Based Ordering, Relaxed Ordering, No Snoop} are set to egress_attr_r[2:0] when forwarding read transactions hitting this translation to PCIe. When egress_attr_enable == 0, PCIe attributes are all set to 0 when forwarding read transactions hitting this translation to PCIe. Attributes which are not allowed to be set due to PCI Express Configuration Register enable functionality will be cleared before the transaction is forwarded to PCIe.'''
  [[register.field]]
    name = "EGRESS_ATTR_ENABLE"
    bits = "23"
    type = "rw"
  [[register.field]]
    name = "RESERVED"
    bits = "22:21"
    type = "ro"
  [[register.field]]
    name = "EGRESS_SIZE"
    bits = "20:16"
    type = "rw"
    shortdesc = '''Translation Size.'''
    longdesc = '''The translation window size in bytes is configured to be 2^(egress_size_offset+egress_size). egress_size must be <= egress_size_max.'''
  [[register.field]]
    name = "RESERVED"
    bits = "15:14"
    type = "ro"
  [[register.field]]
    name = "RESERVED"
    bits = "13:8"
    type = "ro"
  [[register.field]]
    name = "RESERVED"
    bits = "7:5"
    type = "ro"
  [[register.field]]
    name = "RESERVED"
    bits = "4"
    type = "ro"
  [[register.field]]
    name = "EGRESS_INVALID"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "EGRESS_SECURITY_ENABLE"
    bits = "2"
    type = "rw"
  [[register.field]]
    name = "RESERVED"
    bits = "1"
    type = "ro"
  [[register.field]]
    name = "EGRESS_ENABLE"
    bits = "0"
    type = "rw"
    shortdesc = '''Translation Enable.'''
    longdesc = '''The translation is hit when both of the following are true: * egress_enable == 1 * egress_src_base[63:(12+egress_size)] == AXI Address[63:(12+egress_size)]'''
[[register]]
  name = "TRAN_EGRESS_SRC_BASE_LO"
  type = "mixed"
  width = 32
  description = "Egress AXI Translation - Source Address Low"
  default = "0x00000000"
  offset = "0x00000010"
  [[register.field]]
    name = "EGRESS_SRC_BASE_LO"
    bits = "31:12"
    type = "rw"
  [[register.field]]
    name = "RESERVED"
    bits = "11:0"
    type = "ro"
[[register]]
  name = "TRAN_EGRESS_SRC_BASE_HI"
  type = "rw"
  width = 32
  description = "Egress AXI Translation - Source Address High"
  default = "0x00000000"
  offset = "0x00000014"
  [[register.field]]
    name = "EGRESS_SRC_BASE_HI"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "TRAN_EGRESS_DST_BASE_LO"
  type = "mixed"
  width = 32
  description = "Egress AXI Translation - Destination Address Low"
  default = "0x00000000"
  offset = "0x00000018"
  [[register.field]]
    name = "EGRESS_DST_BASE_LO"
    bits = "31:12"
    type = "rw"
  [[register.field]]
    name = "RESERVED"
    bits = "11:0"
    type = "ro"
[[register]]
  name = "TRAN_EGRESS_DST_BASE_HI"
  type = "rw"
  width = 32
  description = "Egress AXI Translation - Destination Address High"
  default = "0x00000000"
  offset = "0x0000001C"
  [[register.field]]
    name = "EGRESS_DST_BASE_HI"
    bits = "31:0"
    type = "rw"
