description = "System Timestamp Generator"
[[bank]]
  name = "IOU_SCNTR"
  address = "0xff250000"
[[register]]
  name = "CURRENT_COUNTER_VALUE_LOWER_REGISTER"
  type = "rw"
  width = 32
  description = "Reads or writes the lower 32 bits of the current counter value. The read-only programming interface can read but not write to this register. The control interface must clear the CNTCR.EN bit before writing to this register."
  default = "0x00000000"
  offset = "0x00000000"
  [[register.field]]
    name = "CNTCVL_L_32"
    bits = "31:0"
    type = "rw"
    shortdesc = '''Current value of the timestamp counter, lower 32 bits.'''
    longdesc = '''To change the current timestamp value, write the lower 32 bits of the new value to this register before writing the upper 32 bits to CNTCVU. The timestamp value is not changed until the CNTCVU register is written to.'''
[[register]]
  name = "CURRENT_COUNTER_VALUE_UPPER_REGISTER"
  type = "rw"
  width = 32
  description = "Reads or writes the upper 32 bits of the current counter value. The read-only programming interface can read but not write this register. The control interface must clear the CNTCR.EN bit before writing to this register."
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "CNTCVU_U_32"
    bits = "31:0"
    type = "rw"
    shortdesc = '''Current value of the timestamp counter, upper 32 bits.'''
    longdesc = '''To change the current timestamp value, write the lower 32 bits of the new value to CNTCVL before writing the upper 32 bits to this register. The 64-bit timestamp value is updated with the value from both writes when this register is written to.'''
