description = "RSA Data and Configuration"
[[bank]]
  name = "RSA"
  address = "0xffce002c"
[[register]]
  name = "WR_DATA_0"
  type = "wo"
  width = 32
  description = "Write Data 0"
  default = "0x00000000"
  offset = "0x00000000"
  [[register.field]]
    name = "WR_DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Write to all 6 WR_DATA registers to complete the 192-bit word required by the RSA core.'''
    longdesc = '''Once all WR_DATA registers are written to, a write to the WR_ADDR register will commit the data to the RAM. This register contains the LSB of the 192-bit word.'''
[[register]]
  name = "WR_DATA_1"
  type = "wo"
  width = 32
  description = "Write Data 1"
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "WR_DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Write to all 6 WR_DATA registers to complete the 192-bit word required by the RSA core.'''
    longdesc = '''Once all WR_DATA registers are written to, a write to the WR_ADDR register will commit the data to the RAM.'''
[[register]]
  name = "WR_DATA_2"
  type = "wo"
  width = 32
  description = "Write Data 2"
  default = "0x00000000"
  offset = "0x00000008"
  [[register.field]]
    name = "WR_DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Write to all 6 WR_DATA registers to complete the 192-bit word required by the RSA core.'''
    longdesc = '''Once all WR_DATA registers are written to, a write to the WR_ADDR register will commit the data to the RAM.'''
[[register]]
  name = "WR_DATA_3"
  type = "wo"
  width = 32
  description = "Write Data 3"
  default = "0x00000000"
  offset = "0x0000000C"
  [[register.field]]
    name = "WR_DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Write to all 6 WR_DATA registers to complete the 192-bit word required by the RSA core.'''
    longdesc = '''Once all WR_DATA registers are written to, a write to the WR_ADDR register will commit the data to the RAM.'''
[[register]]
  name = "WR_DATA_4"
  type = "wo"
  width = 32
  description = "Write Data 4"
  default = "0x00000000"
  offset = "0x00000010"
  [[register.field]]
    name = "WR_DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Write to all 6 WR_DATA registers to complete the 192-bit word required by the RSA core.'''
    longdesc = '''Once all WR_DATA registers are written to, a write to the WR_ADDR register will commit the data to the RAM.'''
[[register]]
  name = "WR_DATA_5"
  type = "wo"
  width = 32
  description = "Write Data 5"
  default = "0x00000000"
  offset = "0x00000014"
  [[register.field]]
    name = "WR_DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Write to all 6 WR_DATA registers to complete the 192-bit word required by the RSA core.'''
    longdesc = '''Once all WR_DATA registers are written to, a write to the WR_ADDR register will commit the data to the RAM. This register contains the MSB of the 192-bit word.'''
[[register]]
  name = "WR_ADDR"
  type = "wo"
  width = 32
  description = "Write Address"
  default = "0x00000000"
  offset = "0x00000018"
  [[register.field]]
    name = "WR_ADDR"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Write the memory address to this register to commit the 192-bit word stored in WR_DATA[5:0] registers.'''
    longdesc = '''The memory organization is detailed in the RAM map.'''
[[register]]
  name = "RD_DATA_0"
  type = "ro"
  width = 32
  description = "Read Data 0"
  default = "0x00000000"
  offset = "0x0000001C"
  [[register.field]]
    name = "RD_DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''Read data register.'''
    longdesc = '''This register is loaded when a RAM address is written to the RD_ADDR register. This register contains the LSB of the 192-bit word.'''
[[register]]
  name = "RD_DATA_1"
  type = "ro"
  width = 32
  description = "Read Data 1"
  default = "0x00000000"
  offset = "0x00000020"
  [[register.field]]
    name = "RD_DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''Read data register.'''
    longdesc = '''This register is loaded when a RAM address is written to the RD_ADDR register.'''
[[register]]
  name = "RD_DATA_2"
  type = "ro"
  width = 32
  description = "Read Data 2"
  default = "0x00000000"
  offset = "0x00000024"
  [[register.field]]
    name = "RD_DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''Read data register.'''
    longdesc = '''This register is loaded when a RAM address is written to the RD_ADDR register.'''
[[register]]
  name = "RD_DATA_3"
  type = "ro"
  width = 32
  description = "Read Data 3"
  default = "0x00000000"
  offset = "0x00000028"
  [[register.field]]
    name = "RD_DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''Read data register.'''
    longdesc = '''This register is loaded when a RAM address is written to the RD_ADDR register.'''
[[register]]
  name = "RD_DATA_4"
  type = "ro"
  width = 32
  description = "Read Data 4"
  default = "0x00000000"
  offset = "0x0000002C"
  [[register.field]]
    name = "RD_DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''Read data register.'''
    longdesc = '''This register is loaded when a RAM address is written to the RD_ADDR register.'''
[[register]]
  name = "RD_DATA_5"
  type = "ro"
  width = 32
  description = "Read Data 5"
  default = "0x00000000"
  offset = "0x00000030"
  [[register.field]]
    name = "RD_DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''Read data register.'''
    longdesc = '''This register is loaded when a RAM address is written to the RD_ADDR register. This register contains the MSB of the 192-bit word.'''
[[register]]
  name = "RD_ADDR"
  type = "wo"
  width = 32
  description = "Read Address"
  default = "0x00000000"
  offset = "0x00000034"
  [[register.field]]
    name = "RD_ADDR"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Read address register.'''
    longdesc = '''Writing a RAM address to this register loads the 192-bit RAM word into the RD_DATA registers.'''
[[register]]
  name = "RSA_CFG"
  type = "rw"
  width = 32
  description = "RSA Control"
  default = "0x00000000"
  offset = "0x00000038"
  [[register.field]]
    name = "RD_ENDIANNESS"
    bits = "2"
    type = "rw"
    shortdesc = '''When cleared (0), the RD_DATA registers will not change the incoming APB byte ordering.'''
    longdesc = '''When set (1), the incomming APB byte locations will be flipped before saving to the RAM. The byte flip is as follows: - Byte[3] -> Byte[0] - Byte[2] -> Byte[1] - Byte[1] -> Byte[2] - Byte[0] -> Byte[3] This is a static signal and should not be changed while data is being written or read to the RSA data registers.'''
  [[register.field]]
    name = "WR_ENDIANNESS"
    bits = "1"
    type = "rw"
    shortdesc = '''When cleared (0), the WR_DATA registers will not change the incoming APB byte ordering.'''
    longdesc = '''When set (1), the incomming APB byte locations will be flipped before saving to the RAM. The byte flip is as follows: - Byte[3] -> Byte[0] - Byte[2] -> Byte[1] - Byte[1] -> Byte[2] - Byte[0] -> Byte[3] This is a static signal and should not be changed while data is being written or read to the RSA data registers.'''
  [[register.field]]
    name = "SLVERR_EN"
    bits = "0"
    type = "rw"
    shortdesc = '''By default, invalid address requests are ignored.'''
    longdesc = '''However, a maskable interrupt exsists. By enabling this slverr_enable invalid address requests cause a slverr to occur. Enable/Disable SLVERR during address decode failure. 0: SLVERR is disabled. For request address: Writes are ignored. Read returns 0. 1: SLVERR is enabled. For requestes address, SLVERR is asserted. Writes are ignored. Read returns 0.'''
[[register]]
  name = "RSA_ISR"
  type = "wtc"
  width = 32
  description = "RSA Interrupt Status"
  default = "0x00000000"
  offset = "0x0000003C"
  [[register.field]]
    name = "APB_SLVERR"
    bits = "0"
    type = "wtc"
[[register]]
  name = "RSA_IMR"
  type = "ro"
  width = 32
  description = "RSA Interrupt Mask"
  default = "0x00000001"
  offset = "0x00000040"
  [[register.field]]
    name = "APB_SLVERR"
    bits = "0"
    type = "ro"
[[register]]
  name = "RSA_IER"
  type = "wo"
  width = 32
  description = "RSA Interrupt Enable"
  default = "0x00000000"
  offset = "0x00000044"
  [[register.field]]
    name = "APB_SLVERR"
    bits = "0"
    type = "wo"
[[register]]
  name = "RSA_IDR"
  type = "wo"
  width = 32
  description = "RSA Interrupt Disable"
  default = "0x00000000"
  offset = "0x00000048"
  [[register.field]]
    name = "APB_SLVERR"
    bits = "0"
    type = "wo"
