description = "XMPU Sink Configuration"
[[bank]]
  name = "FPD_XMPU_SINK"
  address = "0xfd4f0000"
[[register]]
  name = "ERR_STATUS"
  type = "rw"
  width = 32
  description = "Access Violation Error Status."
  default = "0x00000000"
  offset = "0x0000FF00"
  [[register.field]]
    name = "RDWR"
    bits = "31"
    type = "rw"
    shortdesc = '''R/W type of access violation.'''
    longdesc = '''0: read. 1: write.'''
  [[register.field]]
    name = "ADDR"
    bits = "11:0"
    type = "rw"
    shortdesc = '''Offset Address of access violation.'''
    longdesc = '''Bits[11:0] correspond to APB address bits [11:0].'''
[[register]]
  name = "ISR"
  type = "wtc"
  width = 1
  description = "Interrupt Status and Clear."
  default = "0x00000000"
  offset = "0x0000FF10"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wtc"
    shortdesc = '''Access violation (poisoned AXI transaction or register access error).'''
    longdesc = '''READ: 0: no interrupt. 1: interrupt asserted. WRITE: 0: no effect. 1: clear bit to 0. If a Status bit is 1 and its Mask is 0, then the interrupt signal is active to the interrupt controllers. The ERR_CTRL [PSLVERR] can enable a violation event to cause the XMPU_Sink to assert the PSLVERR signal back to the APB interconnect.'''
[[register]]
  name = "IMR"
  type = "ro"
  width = 1
  description = "Interrupt Mask."
  default = "0x00000001"
  offset = "0x0000FF14"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "ro"
    shortdesc = '''Access violation (poisoned AXI transaction or register access error).'''
    longdesc = '''Read-only. 0: enabled. 1: masked (disabled). If the ISR bit = 1 (asserted interrupt) and the IMR bit = 0 (not masked), then the IRQ to the interrupt controllers is asserted. Software checks the ISR to determine the cause of the interrupt.'''
[[register]]
  name = "IER"
  type = "wo"
  width = 1
  description = "Interrupt Enable."
  default = "0x00000000"
  offset = "0x0000FF18"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
    shortdesc = '''Access violation (poisoned AXI transaction or register access error).'''
    longdesc = '''0: no effect. 1: enable interrupt (sets mask = 0). Write-only.'''
[[register]]
  name = "IDR"
  type = "wo"
  width = 1
  description = "Interrupt Disable."
  default = "0x00000000"
  offset = "0x0000FF1C"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
    shortdesc = '''Access violation (poisoned AXI transaction or register access error).'''
    longdesc = '''0: no effect. 1: disable interrupt (sets mask = 1). Write-only.'''
[[register]]
  name = "ERR_CTRL"
  type = "rw"
  width = 32
  description = "Error Signal Control. APB slave error signal."
  default = "0x00000000"
  offset = "0x0000FFEC"
  [[register.field]]
    name = "PSLVERR"
    bits = "0"
    type = "rw"
    shortdesc = '''Enable the PSLVERR signal back to APB interconnect when an access violation occurs.'''
    longdesc = '''0: disable error signal. 1: assert error signal for access violations. Note: The [addr_decode_err] interrupt bit is set in the ISR regardless of the setting of this bit.'''
