resources = [
    "dma/dma.toml",
    "sysmon/sysmon.toml",
    "timer/timer.toml",
    "ipi/ipi.toml"
]

[[definition]]
type = "other.resetti"
gateware = "resetti/resetti.toml"

[[definition]]
type = "clock.generated"