[[definition]]
type = "cpu.zynqps8.a53"
arch = "arm8-a"
triple = "aarch64-none-elf"
width = 64
core_count = 4
max_atomic_width = 128
max_bitop_type_width = 128
gcc_flags = "-march=armv8-a -Wl,--build-id -mno-outline-atomics"
registers = [
    { resource = "zynqps8/registers/a53_cti" },
    { resource = "zynqps8/registers/a53_dbg" },
    { resource = "zynqps8/registers/a53_etm" },
    { resource = "zynqps8/registers/a53_pmu" },
    { resource = "zynqps8/registers/a53_rom" },
    { resource = "zynqps8/registers/a53_system" },
]

[[definition]]
name = "A53InternalBus"
type = "bus.internal.a53"

[[definition]]
name = "A53_to_mainBus"
type = "bridge.internal.a53_to_mainbus"
address_window_width = 64

[[definition]]
type = "ram.sram.ocm"
size_in_bytes = "256 KiB"
