[[definition]]
type = "cpu.a53.zynqps8"
arch = "arm8-a"
triple = "aarch64-none-elf"
width = 64
core_count = 4
max_atomic_width = 128
max_bitop_type_width = 128
gcc_flags = "-mcpu=cortex-a53 -march=armv8-a+crc+crypto -Wl,--build-id -mno-outline-atomics"
registers = [
    { resource = "registers/a53_rom.toml", name = "CORESIGHT_A53_ROM", base_address = "0xFEC3_0000" },
    { resource = "registers/a53_dbg.toml", name = "CORESIGHT_A53_DBG", base_address = "0xFEC1_0000" },
    { resource = "registers/a53_cti.toml", name = "CORESIGHT_A53_CTI", base_address = "0xFEC2_0000" },
    { resource = "registers/a53_pmu.toml", name = "CORESIGHT_A53_PMU", base_address = "0xFEC3_0000" },
    { resource = "registers/a53_etm.toml", name = "CORESIGHT_A53_ETM", base_address = "0xFEC4_0000" },
    { resource = "registers/a53_system.toml", name = "A53_SYSTEM", base_address = "-1" },
]
buses = [
    { name = "apu0", supplier = true, data_width = 128, address_width = 40 },
]
