[[definition]]
type = "cpu.a53.zynqps8"
arch = "arm8-a"
triple = "aarch64-none-elf"
width = 64
core_count = 4
max_atomic_width = 128
max_bitop_type_width = 128
gcc_flags = "-mcpu=cortex-a53 -march=armv8-a+crc+crypto -Wl,--build-id -mno-outline-atomics"
registers = [
    { resource = "registers/a53_rom.toml", name = "CORESIGHT_A53_ROM", base_address = "0xFEC0_0000" },
    { resource = "registers/a53_dbg.toml", name = "CORESIGHT_A53_DBG0", base_address = "0xFEC1_0000" },
    { resource = "registers/a53_dbg.toml", name = "CORESIGHT_A53_DBG1", base_address = "0xFED1_0000" },
    { resource = "registers/a53_dbg.toml", name = "CORESIGHT_A53_DBG2", base_address = "0xFEE1_0000" },
    { resource = "registers/a53_dbg.toml", name = "CORESIGHT_A53_DBG3", base_address = "0xFEF1_0000" },
    { resource = "registers/a53_cti.toml", name = "CORESIGHT_A53_CTI0", base_address = "0xFEC2_0000" },
    { resource = "registers/a53_cti.toml", name = "CORESIGHT_A53_CTI1", base_address = "0xFED2_0000" },
    { resource = "registers/a53_cti.toml", name = "CORESIGHT_A53_CTI2", base_address = "0xFEE2_0000" },
    { resource = "registers/a53_cti.toml", name = "CORESIGHT_A53_CTI3", base_address = "0xFEF2_0000" },
    { resource = "registers/a53_pmu.toml", name = "CORESIGHT_A53_PMU0", base_address = "0xFEC3_0000" },
    { resource = "registers/a53_pmu.toml", name = "CORESIGHT_A53_PMU1", base_address = "0xFED3_0000" },
    { resource = "registers/a53_pmu.toml", name = "CORESIGHT_A53_PMU2", base_address = "0xFEE3_0000" },
    { resource = "registers/a53_pmu.toml", name = "CORESIGHT_A53_PMU3", base_address = "0xFEF3_0000" },
    { resource = "registers/a53_etm.toml", name = "CORESIGHT_A53_ETM0", base_address = "0xFEC4_0000" },
    { resource = "registers/a53_etm.toml", name = "CORESIGHT_A53_ETM1", base_address = "0xFED4_0000" },
    { resource = "registers/a53_etm.toml", name = "CORESIGHT_A53_ETM2", base_address = "0xFEE4_0000" },
    { resource = "registers/a53_etm.toml", name = "CORESIGHT_A53_ETM3", base_address = "0xFEF4_0000" },
    { resource = "registers/a53_system.toml", name = "A53_SYSTEM", base_address = "-1" },
    { resource = "registers/a53_gic400.toml", name = "ACPU_GIC", base_address = "0xf900_0000" },
    { resource = "registers/a53_gic400_cpu.toml", name = "ACPU_GICC", base_address = "0xf902_0000" },
    { resource = "registers/a53_gic400_dist.toml", name = "ACPU_GICD", base_address = "0xf901_0000" },
]
buses = [
    { name = "apu_cci", supplier = true, base_address = "0xFD00_0000", data_width = 128, address_width = 40 },
]
