[[definition]]
type = "cpu.pmu.zynqps8"
arch = "microblaze"
triple = "microblaze-none-elf"
width = 32
core_count = 1
gcc_flags = "-O1 -mlittle-endian -mxl-barrel-shift -mxl-pattern-compare -mcpu=v9.2 -mxl-soft-mul -Wl,--build-id -Wl,-dT=${CMAKE_CURRENT_LIST_DIR}/empty-file.ld"
max_atomic_width = 32
max_bitop_type_width = 32
registers = [
]
buses = [
    { name = "pmu_pmuswitch", supplier = true, base_address = "0xFD00_0000", data_width = 32 },
]

[[definition]]
type = "switch.internal.pmuswitch"
registers = [
    { resource = "registers/pmu_iomodule.toml", name = "PMU_IOMODULE", base_address = "0x02D4_0000", cpus = "PMU" },
    { resource = "registers/pmu_lmb_bram.toml", name = "PMU_LMB_BRAM", base_address = "0x02D5_0000", cpus = "PMU" },
    { resource = "registers/pmu_local.toml", name = "PMU_LOCAL", base_address = "0x02D6_0000", cpus = "PMU" },
    { resource = "registers/pmu_global.toml", name = "PMU_GLOBAL", base_address = "0x02D8_0000" },
]
buses = [
    { name = "pmu_pmuswitch", supplier = false, data_width = 32 },
    { name = "iopinbound_pmuswitch", supplier = false, data_width = 32 },
    { name = "pmu_pmuoutbound", supplier = true, data_width = 32 },
    { name = "pmuram", supplier = true, data_width = 32, address_width = 18 },
]

[[definition]]
type = "ram.sram.pmuram"
ranges = [
    { address = "0x02DC_0000", size = "128 KiB" }
]
buses = [
    { name = "pmuram", supplier = false, data_width = 32, address_width = 18 }
]
