[[definition]]
type = "cpu.zynqps8.pmu"
arch = "microblaze"
triple = "microblaze-none-elf"
width = 32
core_count = 1
gcc_flags = "-O1 -mlittle-endian -mxl-barrel-shift -mxl-pattern-compare -mcpu=v9.2 -mxl-soft-mul -Wl,--build-id -Wl,-dT=${CMAKE_CURRENT_LIST_DIR}/empty-file.ld"
max_atomic_width = 32
max_bitop_type_width = 32
registers = [
    { resource = "zynqps8/registers/pmu_iomodule" },
    { resource = "zynqps8/registers/pmu_lmb_bram" },
    { resource = "zynqps8/registers/pmu_local" },
    { resource = "zynqps8/registers/pmu_global" },
]

[[definition]]
name = "PMUInternalBus"
type = "bus.internal.pmu"

[[definition]]
name = "PMU_to_mainBus"
type = "bridge.internal.pmu_to_mainbus"
address_window_width = 32

[[definition]]
type = "ram.sram.pmuram"
size_in_bytes = "128 KiB"