[[definition]]
type = "cpu.zynqps8.r5f"
arch = "arm7-a"
triple = "arm-none-eabi"
width = 32
core_count = 2
gcc_flags = "-mcpu=cortex-r5 -mfloat-abi=hard -mfpu=vfpv3-d16 -Wl,--build-id"
max_atomic_width = 64
max_bitop_type_width = 128
registers = [
    { resource = "zynqps8/registers/r5_dbg" },
    { resource = "zynqps8/registers/r5_etm" },
    { resource = "zynqps8/registers/r5_rom" },
]

[[definition]]
type = "ram.sram.tcm"

[[definition]]
name = "R5InternalBus"
type = "bus.internal.r5f"

[[definition]]
name = "R5_to_mainBus"
type = "bridge.internal.r5f_to_mainbus"
address_window_width = 32

[[definition]]
type = "ram.sram.tcm"
size_in_bytes = "256 KiB"

