[[definition]]
type = "cpu.r5f.zynqps8"
arch = "arm7-a"
triple = "arm-none-eabi"
width = 32
core_count = 2
gcc_flags = "-mcpu=cortex-r5 -mfloat-abi=hard -mfpu=vfpv3-d16 -Wl,--build-id"
max_atomic_width = 64
max_bitop_type_width = 128
registers = [
    { resource = "registers/r5_pl390.toml", name = "RCPU_GIC", base_address = "0xf900_0000" },
]
buses = [
    { name = "rpu0", supplier = true, base_address = "0xFD00_0000", data_width = 64, address_width = 32 },
    { name = "rpu1", supplier = true, base_address = "0xFD00_0000", data_width = 64, address_width = 32 },
]

[[definition]]
type = "ram.sram.tcm.zynqps8"
ranges = [
    { address = "0x0_0000", size = "64 KiB", fixed_base_address = true, cpus = "R5F" }, # RPU both see there own ram at 0 and 2, they don't see the other
    { address = "0x2_0000", size = "64 KiB", fixed_base_address = true, cpus = "R5F" },
    # Other units see R5_0_ATCM_SPLIT, etc.
    { address = "0x0_0000", size = "64 KiB", cpus = "A53, PMU" }, # R5_0_ATCM_SPLIT
    { address = "0x2_0000", size = "64 KiB", cpus = "A53, PMU" }, # R5_0_BTCM_SPLIT
    { address = "0x4_0000", size = "32 KiB", cpus = "A53, PMU" }, # R5_0_ICACHE
    { address = "0x5_0000", size = "32 KiB", cpus = "A53, PMU" }, # R5_0_DCACHE

    { address = "0x9_0000", size = "64 KiB", cpus = "A53, PMU" }, # R5_1_ATCM_SPLIT
    { address = "0xB_0000", size = "64 KiB", cpus = "A53, PMU" }, # R5_1_BTCM_SPLIT
    { address = "0xD_0000", size = "32 KiB", cpus = "A53, PMU" }, # R5_1_ICACHE
    { address = "0xD_0000", size = "32 KiB", cpus = "A53, PMU" }, # R5_1_DCACHE

]
buses = [
    { name = "rputcm", supplier = false, data_width = 64, address_width = 18 }
]
