path = "sdio"

[[definition]]
type = "storage.sdio.sdcard.slot"

[[definition]]
type = "storage.sdio.zynqps8"
registers = [
    { resource = "zynqps8/sdio.toml", name = "SD", base_address = "0x0216_0000", address_increment = "0x1_0000" }
]
buses = [
    { name = "iopunitsswitchs_sdio${index}", supplier = false, data_width = 64, address_width = 32 },
    { name = "sdio${index}_iopoutbound", supplier = true, data_width = 32, address_width = 32 },
]
max_instances = 2