#include "core/core.h"
#include "utils/boot_psi.h"
#include "platform/reg_access.h"
#include "platform/memory_map.h"
#include "platform/registers/crl_apb.h"
#include "platform/registers/crf_apb.h"
#include "platform/registers/iou_slcr.h"
#include "platform/registers/fpd_slcr.h"
#include "platform/registers/lpd_slcr.h"

__attribute__((__section__(".hwregs")))
static PSI_IWord const clock_init[] = {
		PSI_SET_REGISTER_BANK(CRL_APB),

		PSI_WRITE_MASKED_32(CRL_APB, GEM3_REF_CTRL,																								// GEM3_REF_CTRL
												HW_REG_FIELD_MASK(CRL_APB, GEM3_REF_CTRL, RX_CLKACT) |
															HW_REG_FIELD_MASK(CRL_APB, GEM3_REF_CTRL, CLKACT) |
															HW_REG_FIELD_MASK(CRL_APB, GEM3_REF_CTRL, DIVISOR1) |
															HW_REG_FIELD_MASK(CRL_APB, GEM3_REF_CTRL, DIVISOR0) |
															HW_REG_FIELD_MASK(CRL_APB, GEM3_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, GEM3_REF_CTRL, RX_CLKACT, 1) |
															HW_REG_ENCODE_FIELD(CRL_APB, GEM3_REF_CTRL, CLKACT, 1) |
															HW_REG_ENCODE_FIELD(CRL_APB, GEM3_REF_CTRL, DIVISOR1, 1) |      // / 1
															HW_REG_ENCODE_FIELD(CRL_APB, GEM3_REF_CTRL, DIVISOR0, 12) |     // / 12 = 125Mhz
															HW_REG_ENCODE_ENUM(CRL_APB, GEM3_REF_CTRL, SRCSEL, IOPLL)       // IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, GEM_TSU_REF_CTRL,																									// GEM_TSU_REF_CTRL
														HW_REG_FIELD_MASK(CRL_APB, GEM_TSU_REF_CTRL, CLKACT) |
														HW_REG_FIELD_MASK(CRL_APB, GEM_TSU_REF_CTRL, DIVISOR1) |
														HW_REG_FIELD_MASK(CRL_APB, GEM_TSU_REF_CTRL, DIVISOR0) |
														HW_REG_FIELD_MASK(CRL_APB, GEM_TSU_REF_CTRL, SRCSEL),
														HW_REG_ENCODE_FIELD(CRL_APB, GEM_TSU_REF_CTRL, CLKACT, 1) |
														HW_REG_ENCODE_FIELD(CRL_APB, GEM_TSU_REF_CTRL, DIVISOR1, 1) |      	// / 1
														HW_REG_ENCODE_FIELD(CRL_APB, GEM_TSU_REF_CTRL, DIVISOR0, 6) |     	// / 6 = 250Mhz
														HW_REG_ENCODE_ENUM(CRL_APB, GEM_TSU_REF_CTRL, SRCSEL, IOPLL)        // IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, USB0_BUS_REF_CTRL,																							// USB0_BUS_REF_CTRL
												HW_REG_FIELD_MASK(CRL_APB, USB0_BUS_REF_CTRL, CLKACT) |
														HW_REG_FIELD_MASK(CRL_APB, USB0_BUS_REF_CTRL, DIVISOR1) |
														HW_REG_FIELD_MASK(CRL_APB, USB0_BUS_REF_CTRL, DIVISOR0) |
														HW_REG_FIELD_MASK(CRL_APB, USB0_BUS_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, USB0_BUS_REF_CTRL, CLKACT, 1) |
														HW_REG_ENCODE_FIELD(CRL_APB, USB0_BUS_REF_CTRL, DIVISOR1, 1) |      // / 1
														HW_REG_ENCODE_FIELD(CRL_APB, USB0_BUS_REF_CTRL, DIVISOR0, 6) |     	// / 6 = 250Mhz
														HW_REG_ENCODE_ENUM(CRL_APB, USB0_BUS_REF_CTRL, SRCSEL, IOPLL)       // IOPLL (1500Mhz)
		),

		PSI_WRITE_MASKED_32(CRL_APB, USB3_DUAL_REF_CTRL,																						// USB3_DUAL_REF_CTRL
												HW_REG_FIELD_MASK(CRL_APB, USB3_DUAL_REF_CTRL, CLKACT) |
														HW_REG_FIELD_MASK(CRL_APB, USB3_DUAL_REF_CTRL, DIVISOR1) |
														HW_REG_FIELD_MASK(CRL_APB, USB3_DUAL_REF_CTRL, DIVISOR0) |
														HW_REG_FIELD_MASK(CRL_APB, USB3_DUAL_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, USB3_DUAL_REF_CTRL, CLKACT, 1) |
														HW_REG_ENCODE_FIELD(CRL_APB, USB3_DUAL_REF_CTRL, DIVISOR1, 3) |     // / 3
														HW_REG_ENCODE_FIELD(CRL_APB, USB3_DUAL_REF_CTRL, DIVISOR0, 25) |    // / (3*25) = 20Mhz
														HW_REG_ENCODE_ENUM(CRL_APB, USB3_DUAL_REF_CTRL, SRCSEL, IOPLL)      // IOPLL (1500Mhz)
		),

		// QSPI, SDIO0, SDIO1 and UART0 share a mask
		PSI_MULTI_WRITE_MASKED_32(CRL_APB, QSPI_REF_CTRL, 4,
															HW_REG_FIELD_MASK(CRL_APB, QSPI_REF_CTRL, CLKACT) |
															HW_REG_FIELD_MASK(CRL_APB, QSPI_REF_CTRL, DIVISOR1) |
															HW_REG_FIELD_MASK(CRL_APB, QSPI_REF_CTRL, DIVISOR0) |
															HW_REG_FIELD_MASK(CRL_APB, QSPI_REF_CTRL, SRCSEL),
															HW_REG_ENCODE_FIELD(CRL_APB, QSPI_REF_CTRL, CLKACT, 1) |      // QSPI active
															HW_REG_ENCODE_FIELD(CRL_APB, QSPI_REF_CTRL, DIVISOR1, 1) |    // /1
															HW_REG_ENCODE_FIELD(CRL_APB, QSPI_REF_CTRL, DIVISOR0, 5) |  	// / 5 = 300Mhz
															HW_REG_ENCODE_ENUM(CRL_APB, QSPI_REF_CTRL, SRCSEL, IOPLL),    // IOPLL (1500Mhz)
															HW_REG_ENCODE_FIELD(CRL_APB, SDIO0_REF_CTRL, CLKACT, 1) |     // SDIO 0 active
															HW_REG_ENCODE_FIELD(CRL_APB, SDIO0_REF_CTRL, DIVISOR1, 1) |   // / 1
															HW_REG_ENCODE_FIELD(CRL_APB, SDIO0_REF_CTRL, DIVISOR0, 4) | 	// / 4  = 200Mhz
															HW_REG_ENCODE_ENUM(CRL_APB, SDIO0_REF_CTRL, SRCSEL, RPLL),    // RPLL (800Mhz)
															HW_REG_ENCODE_FIELD(CRL_APB, SDIO1_REF_CTRL, CLKACT, 1) |     // SDIO 1active
															HW_REG_ENCODE_FIELD(CRL_APB, SDIO1_REF_CTRL, DIVISOR1, 1) |   // / 1
															HW_REG_ENCODE_FIELD(CRL_APB, SDIO1_REF_CTRL, DIVISOR0, 4) | 	// / 4 = 200Mhz
															HW_REG_ENCODE_ENUM(CRL_APB, SDIO1_REF_CTRL, SRCSEL, RPLL),    // RPLL (800Mhz)
															HW_REG_ENCODE_FIELD(CRL_APB, UART0_REF_CTRL, CLKACT, 1) |     // UART0 active
															HW_REG_ENCODE_FIELD(CRL_APB, UART0_REF_CTRL, DIVISOR1, 1) |   //
															HW_REG_ENCODE_FIELD(CRL_APB, UART0_REF_CTRL, DIVISOR0, 15) | 	// / 15 = 100Mhz
															HW_REG_ENCODE_ENUM(CRL_APB, UART0_REF_CTRL, SRCSEL, IOPLL)    // IOPLL (1500Mhz)
		),

		// I2C 0 and 1 are the same
		PSI_WRITE_N_MASKED_32(CRL_APB, I2C0_REF_CTRL, 2,
													HW_REG_FIELD_MASK(CRL_APB, I2C0_REF_CTRL, CLKACT) |
													HW_REG_FIELD_MASK(CRL_APB, I2C0_REF_CTRL, DIVISOR1) |
													HW_REG_FIELD_MASK(CRL_APB, I2C0_REF_CTRL, DIVISOR0) |
													HW_REG_FIELD_MASK(CRL_APB, I2C0_REF_CTRL, SRCSEL),
													HW_REG_ENCODE_FIELD(CRL_APB, I2C0_REF_CTRL, CLKACT, 1) |      // I2C0/1 active
													HW_REG_ENCODE_FIELD(CRL_APB, I2C0_REF_CTRL, DIVISOR1, 1) |    // / 1
													HW_REG_ENCODE_FIELD(CRL_APB, I2C0_REF_CTRL, DIVISOR0, 15) |   // / 15 = 100Mhz
													HW_REG_ENCODE_ENUM(CRL_APB, I2C0_REF_CTRL, SRCSEL, IOPLL)     // IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, CAN1_REF_CTRL,																					// CAN1_REF_CTRL
														HW_REG_FIELD_MASK(CRL_APB, CAN1_REF_CTRL, CLKACT) |
														HW_REG_FIELD_MASK(CRL_APB, CAN1_REF_CTRL, DIVISOR0) |
														HW_REG_FIELD_MASK(CRL_APB, CAN1_REF_CTRL, SRCSEL),
														HW_REG_ENCODE_FIELD(CRL_APB, CAN1_REF_CTRL, CLKACT, 1) |
														HW_REG_ENCODE_FIELD(CRL_APB, CAN1_REF_CTRL, DIVISOR0, 15) | // / 15 = 100Mhz
														HW_REG_ENCODE_ENUM(CRL_APB, CAN1_REF_CTRL, SRCSEL, IOPLL)   // IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, CPU_R5_CTRL,																						// CPU_R5_CTRL
												HW_REG_FIELD_MASK(CRL_APB, CPU_R5_CTRL, CLKACT_CORE) |
														HW_REG_FIELD_MASK(CRL_APB, CPU_R5_CTRL, CLKACT) |
														HW_REG_FIELD_MASK(CRL_APB, CPU_R5_CTRL, DIVISOR0) |
														HW_REG_FIELD_MASK(CRL_APB, CPU_R5_CTRL, SRCSEL),
											HW_REG_ENCODE_FIELD(CRL_APB, CPU_R5_CTRL, CLKACT_CORE, 1) |
													HW_REG_ENCODE_FIELD(CRL_APB, CPU_R5_CTRL, CLKACT, 1) |
													HW_REG_ENCODE_FIELD(CRL_APB, CPU_R5_CTRL, DIVISOR0, 3) |      	// / 3 = 500Mhz
													HW_REG_ENCODE_ENUM(CRL_APB, CPU_R5_CTRL, SRCSEL, IOPLL)         // IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, IOU_SWITCH_CTRL,																					// IOU_SWITCH_CTRL
														HW_REG_FIELD_MASK(CRL_APB, IOU_SWITCH_CTRL, CLKACT) |
														HW_REG_FIELD_MASK(CRL_APB, IOU_SWITCH_CTRL, DIVISOR0) |
														HW_REG_FIELD_MASK(CRL_APB, IOU_SWITCH_CTRL, SRCSEL),
														HW_REG_ENCODE_FIELD(CRL_APB, IOU_SWITCH_CTRL, CLKACT, 1) |
														HW_REG_ENCODE_FIELD(CRL_APB, IOU_SWITCH_CTRL, DIVISOR0, 3) |  // / 3 = 500Mhz
														HW_REG_ENCODE_ENUM(CRL_APB, IOU_SWITCH_CTRL, SRCSEL, IOPLL)   // IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, PCAP_CTRL,																								// PCAP_CTRL
												HW_REG_FIELD_MASK(CRL_APB, PCAP_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRL_APB, PCAP_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRL_APB, PCAP_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, PCAP_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, PCAP_CTRL, DIVISOR0, 8) |      			// / 8 = 187.5Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, PCAP_CTRL, SRCSEL, IOPLL)            	// IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, LPD_SWITCH_CTRL,																					// LPD_SWITCH_CTRL
												HW_REG_FIELD_MASK(CRL_APB, LPD_SWITCH_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRL_APB, LPD_SWITCH_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRL_APB, LPD_SWITCH_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, LPD_SWITCH_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, LPD_SWITCH_CTRL, DIVISOR0, 3) |   		// / 3 = 500Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, LPD_SWITCH_CTRL, SRCSEL, IOPLL)       // IOPLL (1500Mhz)
		),

		PSI_WRITE_MASKED_32(CRL_APB, LPD_LSBUS_CTRL,																				// LPD_LSBUS_CTRL
												HW_REG_FIELD_MASK(CRL_APB, LPD_LSBUS_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRL_APB, LPD_LSBUS_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRL_APB, LPD_LSBUS_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, LPD_LSBUS_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, LPD_LSBUS_CTRL, DIVISOR0, 15) |   	// / 15 = 100Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, LPD_LSBUS_CTRL, SRCSEL, IOPLL)      // IOPLL (1500Mhz)
		),

		PSI_WRITE_MASKED_32(CRL_APB, DBG_LPD_CTRL,																					// DBG_LPD_CTRL
												HW_REG_FIELD_MASK(CRL_APB, DBG_LPD_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRL_APB, DBG_LPD_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRL_APB, DBG_LPD_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, DBG_LPD_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, DBG_LPD_CTRL, DIVISOR0, 6) |  			// / 6 = 250Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, DBG_LPD_CTRL, SRCSEL, IOPLL)    		// IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, LPD_DMA_REF_CTRL,																			// LPD_DMA_REF_CTRL
												HW_REG_FIELD_MASK(CRL_APB, LPD_DMA_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRL_APB, LPD_DMA_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRL_APB, LPD_DMA_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, LPD_DMA_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, LPD_DMA_REF_CTRL, DIVISOR0, 3) |  	// / 3 = 500Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, LPD_DMA_REF_CTRL, SRCSEL, IOPLL)    // IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, PL0_REF_CTRL,																					// PL0_REF_CTRL
												HW_REG_FIELD_MASK(CRL_APB, PL0_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRL_APB, PL0_REF_CTRL, DIVISOR1) |
												HW_REG_FIELD_MASK(CRL_APB, PL0_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRL_APB, PL0_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, PL0_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, PL0_REF_CTRL, DIVISOR1, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, PL0_REF_CTRL, DIVISOR0, 8) |  			// / 8 = 100Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, PL0_REF_CTRL, SRCSEL, RPLL)         // RPLL (800Mhz)
		),

		PSI_WRITE_MASKED_32(CRL_APB, PSSYSMON_REF_CTRL,																			// PSSYSMON_REF_CTRL
												HW_REG_FIELD_MASK(CRL_APB, PSSYSMON_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRL_APB, PSSYSMON_REF_CTRL, DIVISOR1) |
												HW_REG_FIELD_MASK(CRL_APB, PSSYSMON_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRL_APB, PSSYSMON_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, PSSYSMON_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, PSSYSMON_REF_CTRL, DIVISOR1, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, PSSYSMON_REF_CTRL, DIVISOR0, 30) |  	// / 30 = 50Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, PSSYSMON_REF_CTRL, SRCSEL, IOPLL)     // IOPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRL_APB, DLL_REF_CTRL,																						// DLL_REF_CTRL
														HW_REG_FIELD_MASK(CRL_APB, DLL_REF_CTRL, SRCSEL),
														HW_REG_ENCODE_ENUM(CRL_APB, DLL_REF_CTRL, SRCSEL, IOPLL)      // IOPLL (1500Mhz)
		),

		PSI_WRITE_MASKED_32(CRL_APB, TIMESTAMP_REF_CTRL,																			// TIMESTAMP_REF_CTRL
												HW_REG_FIELD_MASK(CRL_APB, TIMESTAMP_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRL_APB, TIMESTAMP_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRL_APB, TIMESTAMP_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRL_APB, TIMESTAMP_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRL_APB, TIMESTAMP_REF_CTRL, DIVISOR0, 1) |  			// / 1 = 33.33Mhz
												HW_REG_ENCODE_ENUM(CRL_APB, TIMESTAMP_REF_CTRL, SRCSEL, PS_REF_CLK)   // PS_REF_CLK (33.3Mhz)
		),
		PSI_SET_REGISTER_BANK(CRF_APB),
		PSI_WRITE_MASKED_32(CRF_APB, PCIE_REF_CTRL,																								// PCIE_REF_CTRL
												HW_REG_FIELD_MASK(CRF_APB, PCIE_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, PCIE_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, PCIE_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, PCIE_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, PCIE_REF_CTRL, DIVISOR0, 2) | 					// / 2 = 250Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, PCIE_REF_CTRL, SRCSEL, IOPLL_TO_FPD)    // IOPLL_TO_FPD (500Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, DP_VIDEO_REF_CTRL,																					// DP_VIDEO_REF_CTRL
												HW_REG_FIELD_MASK(CRF_APB, DP_VIDEO_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, DP_VIDEO_REF_CTRL, DIVISOR1) |
												HW_REG_FIELD_MASK(CRF_APB, DP_VIDEO_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, DP_VIDEO_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, DP_VIDEO_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, DP_VIDEO_REF_CTRL, DIVISOR1, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, DP_VIDEO_REF_CTRL, DIVISOR0, 5) | 			// / 5 = 300Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, DP_VIDEO_REF_CTRL, SRCSEL, VPLL)        // VPLL (1500Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, DP_AUDIO_REF_CTRL,																					// DP_AUDIO_REF_CTRL
												HW_REG_FIELD_MASK(CRF_APB, DP_AUDIO_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, DP_AUDIO_REF_CTRL, DIVISOR1) |
												HW_REG_FIELD_MASK(CRF_APB, DP_AUDIO_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, DP_AUDIO_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, DP_AUDIO_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, DP_AUDIO_REF_CTRL, DIVISOR1, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, DP_AUDIO_REF_CTRL, DIVISOR0, 16) | 		// / 16 = 25Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, DP_AUDIO_REF_CTRL, SRCSEL, RPLL_TO_FPD) // RPLL_TO_FPD (400Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, DP_STC_REF_CTRL,																						// DP_STC_REF_CTRL
												HW_REG_FIELD_MASK(CRF_APB, DP_STC_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, DP_STC_REF_CTRL, DIVISOR1) |
												HW_REG_FIELD_MASK(CRF_APB, DP_STC_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, DP_STC_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, DP_STC_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, DP_STC_REF_CTRL, DIVISOR1, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, DP_STC_REF_CTRL, DIVISOR0, 15) | 			// / 15 = 26.66Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, DP_STC_REF_CTRL, SRCSEL, RPLL_TO_FPD)   // RPLL_TO_FPD (400Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, ACPU_CTRL,																									//ACPU_CTRL
												HW_REG_FIELD_MASK(CRF_APB, ACPU_CTRL, CLKACT_HALF) |
												HW_REG_FIELD_MASK(CRF_APB, ACPU_CTRL, CLKACT_FULL) |
												HW_REG_FIELD_MASK(CRF_APB, ACPU_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, ACPU_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, ACPU_CTRL, CLKACT_HALF, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, ACPU_CTRL, CLKACT_FULL, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, ACPU_CTRL, DIVISOR0, 1) | 						// / 1 = 1200Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, ACPU_CTRL, SRCSEL, APLL)         			// APLL (1200Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, DBG_FPD_CTRL,																						// DBG_FPD_CTRL
												HW_REG_FIELD_MASK(CRF_APB, DBG_FPD_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, DBG_FPD_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, DBG_FPD_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, DBG_FPD_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, DBG_FPD_CTRL, DIVISOR0, 2) | 				// / 2 = 250Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, DBG_FPD_CTRL, SRCSEL, IOPLL_TO_FPD)   // IOPLL_TO_FPD (500Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, DDR_CTRL,																								// DDR_CTRL
												HW_REG_FIELD_MASK(CRF_APB, DDR_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, DDR_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, DDR_CTRL, DIVISOR0, 2) | 						// / 2 = 600Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, DDR_CTRL, SRCSEL, DPLL)     					// DPLL (1200Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, GPU_REF_CTRL,																						// GPU_REF_CTRL
												HW_REG_FIELD_MASK(CRF_APB, GPU_REF_CTRL, PP0_CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, GPU_REF_CTRL, PP1_CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, GPU_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, GPU_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, GPU_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, GPU_REF_CTRL, PP0_CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, GPU_REF_CTRL, PP1_CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, GPU_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, GPU_REF_CTRL, DIVISOR0, 2) | 			// / 2 = 600Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, GPU_REF_CTRL, SRCSEL, DPLL)         // DPLL (1200Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, FPD_DMA_REF_CTRL,																			// FPD_DMA_REF_CTRL
												HW_REG_FIELD_MASK(CRF_APB, FPD_DMA_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, FPD_DMA_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, FPD_DMA_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, FPD_DMA_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, FPD_DMA_REF_CTRL, DIVISOR0, 2) | // / 2 = 600Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, FPD_DMA_REF_CTRL, SRCSEL, DPLL)   // DPLL (1200Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, DPDMA_REF_CTRL,																			// DPDMA_REF_CTRL
												HW_REG_FIELD_MASK(CRF_APB, DPDMA_REF_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, DPDMA_REF_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, DPDMA_REF_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, DPDMA_REF_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, DPDMA_REF_CTRL, DIVISOR0, 2) | 	// / 2 = 600Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, DPDMA_REF_CTRL, SRCSEL, DPLL)     // DPLL (1200Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, TOPSW_MAIN_CTRL,																			// TOPSW_MAIN_CTRL FPD AXI clock
												HW_REG_FIELD_MASK(CRF_APB, TOPSW_MAIN_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, TOPSW_MAIN_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, TOPSW_MAIN_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, TOPSW_MAIN_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, TOPSW_MAIN_CTRL, DIVISOR0, 3) | 	// / 3 = 400Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, TOPSW_MAIN_CTRL, SRCSEL, DPLL)    // DPLL (1200Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, TOPSW_LSBUS_CTRL,																		// TOPSW_LSBUS FPD APB Clock
												HW_REG_FIELD_MASK(CRF_APB, TOPSW_LSBUS_CTRL, CLKACT) |
												HW_REG_FIELD_MASK(CRF_APB, TOPSW_LSBUS_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, TOPSW_LSBUS_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, TOPSW_LSBUS_CTRL, CLKACT, 1) |
												HW_REG_ENCODE_FIELD(CRF_APB, TOPSW_LSBUS_CTRL, DIVISOR0, 5) | 			// / 5 = 100Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, TOPSW_LSBUS_CTRL, SRCSEL, IOPLL_TO_FPD) // IOPLL_TO_FPD (500Mhz)
		),
		PSI_WRITE_MASKED_32(CRF_APB, DBG_TSTMP_CTRL,																						// DBG_TSTMP_CTRL
												HW_REG_FIELD_MASK(CRF_APB, DBG_TSTMP_CTRL, DIVISOR0) |
												HW_REG_FIELD_MASK(CRF_APB, DBG_TSTMP_CTRL, SRCSEL),
												HW_REG_ENCODE_FIELD(CRF_APB, DBG_TSTMP_CTRL, DIVISOR0, 2) | 				// / 2 = 250Mhz
												HW_REG_ENCODE_ENUM(CRF_APB, DBG_TSTMP_CTRL, SRCSEL, IOPLL_TO_FPD) 	// IOPLL_TO_FPD (500Mhz)
		),
		PSI_SET_REGISTER_BANK(IOU_SLCR),
		PSI_WRITE_MASKED_32(IOU_SLCR, SDIO_CLK_CTRL, 0x00020003U, 0x00000000U),
		PSI_WRITE_MASKED_32(IOU_SLCR, WDT_CLK_SEL, 0x00000001U, 0x00000000U),
		PSI_WRITE_MASKED_32(IOU_SLCR, IOU_TTC_APB_CLK, 0x000000FFU, 0x00000000U),

		PSI_FAR_WRITE_MASKED_32(FPD_SLCR, WDT_CLK_SEL, 0x00000001U, 0x00000000U),
		PSI_FAR_WRITE_MASKED_32(LPD_SLCR, CSUPMU_WDT_CLK_SEL, 0x00000001U, 0x00000000U),

		PSI_END_PROGRAM
};

void clockRunInitProgram() {
	psi_RunRegisterProgram(clock_init);
}