[[include]]
resource = "software/software.toml"

[[include]]
resource = "fabric.toml"

[[definition]]
type = "soc.zynqps8.ps8soc"
gateware = "ps8soc/ps8soc.toml"
buses = [
    { name = "lpd", supplier = true, protocol = "axi4", prefix = "psToPlAxiLpd_0_", base_address = "0x8000_0000", data_width = 128, address_width = 40 },
    { name = "hpm0", supplier = true, protocol = "axi4", prefix = "psToPlAxiHpm_0_", base_address = "0xA400_0000", data_width = 128, address_width = 40 },
    { name = "hpm1", supplier = true, protocol = "axi4", prefix = "psToPlAxiHpm_1_", base_address = "0xB000_0000", data_width = 128, address_width = 40 },
    { name = "hpc0", supplier = false, protocol = "axi4", prefix = "plToPsAxiHpc_0_", data_width = 128, address_width = 40 },
    { name = "hpc1", supplier = false, protocol = "axi4", prefix = "plToPsAxiHpc_1_", data_width = 128, address_width = 40 },
    { name = "hp0", supplier = false, protocol = "axi4", prefix = "plToPsAxiHp_0_", data_width = 128, address_width = 40 },
    { name = "hp1", supplier = false, protocol = "axi4", prefix = "plToPsAxiHp_1_", data_width = 128, address_width = 40 },
    { name = "hp2", supplier = false, protocol = "axi4", prefix = "plToPsAxiHp_2_", data_width = 128, address_width = 40 },
    { name = "hp3", supplier = false, protocol = "axi4", prefix = "plToPsAxiHp_3_", data_width = 128, address_width = 40 },
    { name = "lpd", supplier = false, protocol = "axi4", prefix = "plToPsAxiLpd_0_", data_width = 128, address_width = 40 },
    { name = "acp", supplier = false, protocol = "axi4", prefix = "plToPsAxiAcp_0_", data_width = 128, address_width = 40 },
]
registers = [
    { resource = "registers/afifm.toml", name = "S_AXI_HPC0_FPD", base_address = "0xfd36_0000" },
    { resource = "registers/afifm.toml", name = "S_AXI_HPC1_FPD", base_address = "0xfd37_0000" },
    { resource = "registers/afifm.toml", name = "S_AXI_HP0_FPD", base_address = "0xfd38_0000" },
    { resource = "registers/afifm.toml", name = "S_AXI_HP1_FPD", base_address = "0xfd39_0000" },
    { resource = "registers/afifm.toml", name = "S_AXI_HP2_FPD", base_address = "0xfd3a_0000" },
    { resource = "registers/afifm.toml", name = "S_AXI_HP3_FPD", base_address = "0xfd3b_0000" },
    { resource = "registers/afifm.toml", name = "S_AXI_LPD", base_address = "0xff9b_0000" },
]

[[definition]]
type = "other.zynqps8.rawps8"
gateware = "gateware/ps8.toml"
registersX = [
    { resource = "registers/ams" },
    { resource = "registers/apu" },
    { resource = "registers/axipcie_dma" },
    { resource = "registers/axipcie_egress" },
    { resource = "registers/axipcie_ingress" },
    { resource = "registers/axipcie_main" },
    { resource = "registers/bbram" },
    { resource = "registers/can" },
    { resource = "registers/cci400" },
    { resource = "registers/cci_reg" },
    { resource = "registers/crf_apb" },
    { resource = "registers/crl_apb" },
    { resource = "registers/csu" },
    { resource = "registers/csudma" },
    { resource = "registers/dp" },
    { resource = "registers/dpdma" },
    { resource = "registers/dp_dpcd" },
    { resource = "registers/eedid" },
    { resource = "registers/efuse" },
    { resource = "registers/etf4k" },
    { resource = "registers/etf8k" },
    { resource = "registers/etr" },
    { resource = "registers/fpd_gpv" },
    { resource = "registers/fpd_slcr_secure" },
    { resource = "registers/fpd_slcr" },
    { resource = "registers/ftm" },
    { resource = "registers/funnel3p" },
    { resource = "registers/funnel4p" },
    { resource = "registers/gic400" },
    { resource = "registers/gic400_cpu" },
    { resource = "registers/gic400_dist" },
    { resource = "registers/gpio" },
    { resource = "registers/gpu" },
    { resource = "registers/i2c" },
    { resource = "registers/iou_gpv" },
    { resource = "registers/iou_scntr" },
    { resource = "registers/iou_scntrs" },
    { resource = "registers/iou_secure_slcr" },
    { resource = "registers/iou_slcr" },
    { resource = "registers/ipi" },
    { resource = "registers/ipi_buffer" },
    { resource = "registers/lpd_gpv" },
    { resource = "registers/lpd_slcr_secure" },
    { resource = "registers/lpd_slcr" },
    { resource = "registers/mbistjtag" },
    { resource = "registers/ocm" },
    { resource = "registers/pcie_attrib" },
    { resource = "registers/pl390" },
    { resource = "registers/plsysmon" },
    { resource = "registers/pssysmon" },
    { resource = "registers/replic" },
    { resource = "registers/rpu" },
    { resource = "registers/rsa" },
    { resource = "registers/rsa_core" },
    { resource = "registers/rtc" },
    { resource = "registers/serdes" },
    { resource = "registers/serdes2" },
    { resource = "registers/siou" },
    { resource = "registers/smmu500" },
    { resource = "registers/smmu_reg" },
    { resource = "registers/stm" },
    { resource = "registers/swdt" },
    { resource = "registers/tpiu" },
    { resource = "registers/tsgen" },
    { resource = "registers/ttc" },
    { resource = "registers/xmpu_ddr" },
    { resource = "registers/xmpu_fpd" },
    { resource = "registers/xmpu_ocm" },
    { resource = "registers/xmpu_sink" },
    { resource = "registers/xppu" },
    { resource = "registers/xppu_sink" },
    { resource = "registers/zdma" },
    { resource = "registers/pmu_global" },
]

