[[definition]]
type = "switch.internal.cci.zynqps8"
registers = [
    { resource = "registers/cci400.toml", name = "CCI_GPV", base_address = "0xfd6e_0000" },
    { resource = "registers/cci_reg.toml", name = "CCI_REG", base_address = "0xfd5e_0000" },
]
buses = [
    { name = "hpc${index}_cci", supplier = false, data_width = 128, address_width = 40 },
    { name = "siou_cci", supplier = false, data_width = 128, address_width = 40 },
    { name = "cci0_ddr", supplier = true, data_width = 128, address_width = 40 },
    { name = "cci1_ddr", supplier = true, data_width = 128, address_width = 40 },
    { name = "cci_fpd", supplier = true, data_width = 128, address_width = 40 },
]

[[definition]]
type = "switch.internal.fpd.zynqps8"
registers = [
    { resource = "registers/crf_apb.toml", name = "CRF_APB", base_address = "0xfd1a_0000" },
    { resource = "registers/fpd_gpv.toml", name = "FPD_GPV", base_address = "0xfd70_0000" },
]
buses = [
    { name = "cci_fpd", supplier = false, data_width = 128, address_width = 40 },
    { protocol = "internal_splitter_out", supplier = false },
    { name = "fpd_fpddma", supplier = true, data_width = 64, address_width = 40 },
    { name = "fpd_siou", supplier = true, data_width = 64, address_width = 40 },
    { name = "fpd_ocm", supplier = true, base_address = "0xFFFC_0000", data_width = 128, address_width = 18 },
    { name = "fpd_hpm{$index}", supplier = true, base_address = "0xFFFC_0000", data_width = 128, address_width = 18 },
]


[[definition]]
type = "switch.internal.siouswitch.zynqps8"
registers = [
    { resource = "registers/siou.toml", name = "SIOU", base_address = "0xfd3d_0000" },
    { resource = "registers/serdes.toml", name = "SERDES", base_address = "0xfd40_0000" },
    { resource = "registers/serdes2.toml", name = "SERDES2", base_address = "0xfd41_0000" },
]
buses = [
    { name = "fpd_siou", supplier = false, data_width = 64, address_width = 32 },
    { name = "siou_gpu", supplier = true, base_address = "0", data_width = 128 },
    { name = "siou_sata", supplier = true, base_address = "0", data_width = 64 },
    { name = "siou_pcie", supplier = true, base_address = "0", data_width = 64 },
    { name = "siou_dp", supplier = true, base_address = "0", data_width = 64 },
    { name = "siou_fpd_config", supplier = true, base_address = "0", data_width = 64 },
    { name = "siou_fpd_slcr", supplier = true, base_address = "0", data_width = 64 },
]


[[definition]]
type = "switch.internal.siououtbound.zynqps8"
buses = [
    { name = "gpu_siououtbound", supplier = false, data_width = 64, address_width = 32 },
    { name = "sata_siououtbound", supplier = false, data_width = 64, address_width = 32 },
    { name = "pcie_siououtbound", supplier = false, data_width = 64, address_width = 32 },
    { name = "siou_cci", supplier = true, base_address = "0xFFFC_0000", data_width = 128, address_width = 18 },
]

[[definition]]
type = "other.internal.fpd_slcr.zynqps8"
registers = [
    { resource = "registers/fpd_slcr.toml", name = "FPD_SLCR", base_address = "0xfd61_0000" },
    { resource = "registers/fpd_slcr_secure.toml", name = "FPD_SLCR_SECURE", base_address = "0xfd69_0000" },
]
buses = [
    { name = "siou_fpd_slcr", supplier = false, base_address = "0" },
]

[[definition]]
type = "switch.internal.two_to_one_multiplexer.zynqps8"
buses = [
    { protocol = "internal_multiplexer0", supplier = false },
    { protocol = "internal_multiplexer1", supplier = false },
    { protocol = "internal_splitter", supplier = true },
]

[[definition]]
type = "switch.internal.one_to_two_splitter.zynqps8"
buses = [
    { protocol = "internal_splitter", supplier = false },
    { protocol = "internal_splitter_out", supplier = true },
    { protocol = "internal_ddr", supplier = true },
]
