[[definition]]
type = "switch.internal.iopinbound.zynqps8"
buses = [
    { name = "rpuio_iopinbound", supplier = false, data_width = 64 },
    { name = "iopinbound_usb${index}", supplier = true, data_width = 32 },
    { name = "iopinbound_lpddma", supplier = true, data_width = 32 },
    { name = "iopinbound_iopunitsswitch${index}", supplier = true, data_width = 32 },
    { name = "iopinbound_lpdunitsswitch", supplier = true, data_width = 32 },
    { name = "iopinbound_pmuswitch", supplier = true, data_width = 32 },
    { name = "iopinbound_csu", supplier = true, data_width = 32 },
]

[[definition]]
type = "switch.internal.pmuoutbound.zynqps8"
buses = [
    { name = "pmu_pmuoutbound", supplier = false, data_width = 32 },
    { name = "csu_outbound", supplier = false, data_width = 32 },
    { name = "dap_outbound", supplier = false, data_width = 32 },
    { name = "pmuoutbound_iopoutbound", supplier = true, data_width = 32 },
]

[[definition]]
type = "switch.internal.iopoutbound.zynqps8"
buses = [
    { name = "quadspi_iopoutbound", supplier = false, data_width = 32 },
    { name = "gem${index}_iopoutbound", supplier = false, data_width = 32 },
    { name = "nand_iopoutbound", supplier = false, data_width = 32 },
    { name = "sdio${index}_iopoutbound", supplier = false, data_width = 32 },
    { name = "pmuoutbound_iopoutbound", supplier = false, data_width = 32 },
    { name = "iopoutbound_lpd", supplier = true, data_width = 64, address_width = 32 },
]

[[definition]]
type = "switch.internal.iopunitsswitch.zynqps8"
buses = [
    { name = "iopinbound_iopunitsswitch${index}", supplier = false, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_uart${index}", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_can${index}", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_i2c${index}", protocol = "internal_i2c", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_quadspi", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_gem${index}", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_nand", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_sdio${index}", supplier = true, data_width = 32, address_width = 32 },
]
registers = [
    { resource = "registers/iop/iou_gpv.toml", name = "IOU_GPV", base_address = "0x100_0000" },
    { resource = "registers/iop/iou_slcr.toml", name = "IOU_SLCR", base_address = "0x218_0000" }, #0xff180000
    { resource = "registers/iop/iou_secure_slcr.toml", name = "IOU_SECURE_SLCR", base_address = "0x224_0000" }, #0xff240000
]

[[definition]]
type = "switch.internal.iopmasters.zynqps8"
buses = [
    { name = "quadspi_iopmasters", supplier = false, data_width = 32, address_width = 32 },
    { name = "gem${index}_iopmasters", supplier = false, data_width = 32, address_width = 32 },
    { name = "nand_iopmasters", supplier = false, data_width = 32, address_width = 32 },
    { name = "sdio${index}_iopmasters", supplier = false, data_width = 32, address_width = 32 },
    { name = "iopmasters_iopoutbound", supplier = true, data_width = 64, address_width = 32 },
]

[[definition]]
type = "other.internal.csu.zynqps8"
buses = [
    { name = "iopinbound_csu", supplier = false, data_width = 32 },
    { name = "csuram", supplier = true, data_width = 32, address_width = 18 },
    { name = "csu_outbound", supplier = true, data_width = 32 },
]
registers = [
    { resource = "registers/csu/csudma.toml", name = "CSUDMA", base_address = "0x2c80000" },
    { resource = "registers/csu/csu.toml", name = "CSU", base_address = "0x2ca_0000" },
]

[[definition]]
type = "other.internal.dap.zynqps8"
buses = [
    { name = "dap_outbound", supplier = true, data_width = 32 },
]
registers = [
    { resource = "registers/dap/daprom.toml", name = "CORESIGHT_SOC_ROM", base_address = "0x80_0000" },
]
