[[definition]]
type = "switch.internal.lpd.zynqps8"
buses = [
    { name = "rpu_lpd", supplier = false, data_width = 64, address_width = 32 },
    { name = "lpdoutbound_lpd", supplier = false, data_width = 128, address_width = 40 },
    { name = "iooutbound_lpd", supplier = false, data_width = 64, address_width = 40 },
    { name = "rpuio_lpd", supplier = false, data_width = 128, address_width = 40 },
    { name = "lpd_cci", supplier = true, data_width = 128, address_width = 40 },
    { name = "lpd_ocm", supplier = true, base_address = "0xFFFC_0000", data_width = 64, address_width = 18 },
    { name = "lpd_lpdinbound", supplier = true, data_width = 128, address_width = 40 },
]

[[definition]]
type = "switch.internal.lpdunitsswitch.zynqps8"
buses = [
    { name = "iopinbound_lpdunitsswitch", supplier = false, data_width = 32 },
    { name = "lpdunitsswitch_pssysmon", supplier = true, data_width = 32 },
    { name = "lpdunitsswitch_ipi", supplier = true, data_width = 32 },
    { name = "lpdunitsswitch_efuse", supplier = true, data_width = 32 },
    { name = "lpdunitsswitch_spi${index}", supplier = true, data_width = 32 },
    { protocol = "internal_ttc", supplier = true, data_width = 32 },
    { protocol = "internal_swdt", supplier = true, data_width = 32 },
    { name = "lpdunitsswitch_lpdslcr", supplier = true, data_width = 32 },
    { name = "lpdunitsswitch_gpio", supplier = true, data_width = 32 },
    { name = "lpdunitsswitch_rtc", supplier = true, data_width = 32 },
]


[[definition]]
type = "switch.internal.lpdinbound.zynqps8"
buses = [
    { name = "lpd_lpdinbound", supplier = false, data_width = 128, address_width = 40 },
    { name = "fpd_lpdinbound", supplier = false, data_width = 64, address_width = 40 },
    { name = "lpdinbound_rpuio", supplier = true, data_width = 128, address_width = 40 },
]

[[definition]]
type = "switch.internal.lpdoutbound.zynqps8"
buses = [
    { name = "usb${index}_lpdoutbound", supplier = false, data_width = 128, address_width = 40 },
    { name = "lpddma_lpdoutbound", supplier = false, data_width = 128, address_width = 40 },
    { name = "lpdoutbound_lpd", supplier = true, data_width = 128, address_width = 40 },
]

[[definition]]
type = "switch.internal.rpuio.zynqps8"
buses = [
    { name = "lpdinbound_rpuio", supplier = false, data_width = 128, address_width = 40 },
    { name = "rpus${index}", supplier = true, data_width = 64, address_width = 32 },
    { name = "rpuio_lpd", supplier = true, data_width = 128, address_width = 40 },
    { name = "rpuio_rpu", supplier = true, data_width = 64, address_width = 32 },
    { name = "rpuio_iopinbound", supplier = true, base_address = "0xFE00_0000", data_width = 64, address_width = 32 },
]

[[definition]]
type = "switch.internal.rpuswitch.zynqps8"
buses = [
    { name = "rpu${index}", supplier = false, data_width = 64, address_width = 32 },
    { name = "rpu_ocm", supplier = true, base_address = "0xFFFC_0000", data_width = 128, address_width = 18 },
    { name = "rpu_lpd", supplier = true, base_address = "0", data_width = 64, address_width = 32 },
]

[[definition]]
type = "switch.internal.ocm.zynqps8"
buses = [
    { name = "rpu_ocm", supplier = false, data_width = 64, address_width = 18 },
    { name = "lpd_ocm", supplier = false, data_width = 64, address_width = 18 },
    { name = "fpd_ocm", supplier = false, data_width = 128, address_width = 18 },
]

[[definition]]
type = "switch.internal.iopinbound.zynqps8"
buses = [
    { name = "rpuio_iopinbound", supplier = false, data_width = 64 },
    { name = "iopinbound_usb${index}", supplier = true, data_width = 32 },
    { name = "iopinbound_lpddma", supplier = true, data_width = 32 },
    { name = "iopinbound_iopunitsswitch${index}", supplier = true, data_width = 32 },
    { name = "iopinbound_lpdunitsswitch", supplier = true, data_width = 32 },
]

[[definition]]
type = "switch.internal.iopoutbound.zynqps8"
buses = [
    { name = "quadspi_iopoutbound", supplier = false, data_width = 32 },
    { name = "gem${index}_iopoutbound", supplier = false, data_width = 32 },
    { name = "nand_iopoutbound", supplier = false, data_width = 32 },
    { name = "sdio${index}_iopoutbound", supplier = false, data_width = 32 },
    { name = "iopoutbound_lpd", supplier = true, data_width = 64, address_width = 32 },
]

[[definition]]
type = "switch.internal.iopunitsswitch.zynqps8"
buses = [
    { name = "iopinbound_iopunitsswitch${index}", supplier = false, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_uart${index}", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_can${index}", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_i2c${index}", protocol = "internal_i2c", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_quadspi", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_gem${index}", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_nand", supplier = true, data_width = 32, address_width = 32 },
    { name = "iopunitsswitch_sdio${index}", supplier = true, data_width = 32, address_width = 32 },
]

[[definition]]
type = "switch.internal.iopmasters.zynqps8"
buses = [
    { name = "quadspi_iopmasters", supplier = false, data_width = 32, address_width = 32 },
    { name = "gem${index}_iopmasters", supplier = false, data_width = 32, address_width = 32 },
    { name = "nand_iopmasters", supplier = false, data_width = 32, address_width = 32 },
    { name = "sdio${index}_iopmasters", supplier = false, data_width = 32, address_width = 32 },
    { name = "iopmasters_iopoutbound", supplier = true, data_width = 64, address_width = 32 },
]
