[[definition]]
name = "core"
type = "library.core.zynqps8"
cpus = ["a53", "r5f", "pmu"]
software = "software/libraries/core/core.toml"

[[definition]]
name = "utils"
type = "library.utils"
software = "software/libraries/utils/utils.toml"

[[definition]]
name = "hw"
type = "library.hw.zynqps8"
software = "software/libraries/hw/hw.toml"

[[definition]]
name = "dbg"
type = "library.dbg.zynqps8"
software = "software/libraries/dbg/dbg.toml"

[[definition]]
name = "osservices"
type = "library.osservices.zynqps8"
software = "software/libraries/osservices/osservices.toml"

[[definition]]
name = "utils"
type = "library.utils.zynqps8"
software = "software/libraries/utils/utils.toml"

[[definition]]
name = "zynqps8_display_port"
type = "library.display_port.zynqps8"
software = "software/libraries/display_port/display_port.toml"

[[definition]]
name = "zynqps8_dma"
type = "library.dma.zynqps8"
software = "software/libraries/dma/dma.toml"

[[definition]]
name = "gfxdebug"
type = "library.gfxdebug.zynqps8"
software = "software/libraries/gfxdebug/gfxdebug.toml"

[[definition]]
name = "musl_math"
type = "library.musl_math.zynqps8"
software = "software/libraries/musl_math/musl_math.toml"

[[definition]]
name = "xilinx"
type = "library.xilinx.zynqps8"
software = "software/libraries/xilinx/xilinx.toml"

[[definition]]
name = "ikuy_boot"
type = "program.bootrom.zynqps8"
software = "software/programs_a53/ikuy_boot/ikuy_boot.toml"
cpus = "a53"

[[definition]]
name = "pmu_monitor"
type = "program.pmu_monitor"
software = "software/programs_pmu/pmu_monitor/pmu_monitor.toml"
cpus = "pmu"
