[[definition]]
name = "core"
type = "library.core.zynqps8"
cpus = ["a53", "r5f", "pmu"]
software = "software/lib/core/core.toml"

[[definition]]
name = "utils"
type = "library.utils"
software = "software/lib/utils/utils.toml"

[[definition]]
name = "hw"
type = "library.hw.zynqps8"
software = "software/lib/hw/hw.toml"

[[definition]]
name = "dbg"
type = "library.dbg.zynqps8"
software = "software/lib/dbg/dbg.toml"

[[definition]]
name = "osservices"
type = "library.osservices.zynqps8"
software = "software/lib/osservices/osservices.toml"

[[definition]]
name = "utils"
type = "library.utils.zynqps8"
software = "software/lib/utils/utils.toml"

[[definition]]
name = "zynqps8_display_port"
type = "library.display_port.zynqps8"
software = "software/lib/display_port/display_port.toml"

[[definition]]
name = "zynqps8_dma"
type = "library.dma.zynqps8"
software = "software/lib/dma/dma.toml"

[[definition]]
name = "ikuy_boot"
type = "program.bootrom.zynqps8"
software = "software/programs_a53/ikuy_boot/ikuy_boot.toml"
cpus = "a53"

[[definition]]
name = "pmu_monitor"
type = "program.pmu_monitor"
software = "software/programs_pmu/pmu_monitor/pmu_monitor.toml"
cpus = "pmu"
