
[[definition]]
name = "zynqps8_display_port"
type = "library.display_port.zynqps8"
software = "software/libs/display_port/display_port.toml"
cpus = "a53"

[[definition]]
name = "zynqps8_dma"
type = "library.dma.zynqps8"
software = "software/libs/dma/dma.toml"

[[definition]]
name = "xilinx"
type = "library.xilinx.zynqps8"
software = "software/libs/xilinx/xilinx.toml"

[[definition]]
name = "ikuy_boot"
type = "program.bootrom.zynqps8"
software = "software/programs_a53/ikuy_boot/ikuy_boot.toml"
cpus = "a53"

[[definition]]
name = "pmu_monitor"
type = "program.pmu_monitor"
software = "software/programs_pmu/pmu_monitor/pmu_monitor.toml"
cpus = "pmu"
