path = "socs/zynqps8"

[[definition]]
type = "other.zynqps8.rawps8"
gateware = "gateware/ps8.toml"

[[definition]]
type = "cpu.a53"
arch = "arm8-a"
triple = "aarch64-none-elf"
width = 64
core_count = 4

software = [
    { registers = "registers/a53_cti" },
    { registers = "registers/a53_dbg" },
    { registers = "registers/a53_etm" },
    { registers = "registers/a53_pmu" },
    { registers = "registers/a53_rom" },
]

[[definition]]
type = "cpu.r5f"
arch = "arm7-a"
triple = "arm-none-eabi"
width = 32
core_count = 2
software = [
    { registers = "registers/r5_dbg" },
    { registers = "registers/r5_etm" },
    { registers = "registers/r5_rom" },
]

[[definition]]
type = "cpu.pmu"
arch = "microblaze"
triple = "microblaze-none-elf"
width = 32
core_count = 1
software = [
    { registers = "registers/pmu_global" },
    { registers = "registers/pmu_iomodule" },
    { registers = "registers/pmu_local" },
]

[[definition]]
type = "ram.sram.tcm"
size_in_bytes = "256 KiB"

[[definition]]
type = "ram.sram.pmuram"
size_in_bytes = "128 KiB"

[[definition]]
type = "ram.sram.ocp"
size_in_bytes = "256 KiB"

[[definition]]
type = "ram.ddr.ddr4.MT40A256M16LY"
size_in_bytes = "4 GiB"

[[definition]]
type = "bus.axi4"

[[definition]]
type = "bus.apb"

[[definition]]
type = "bridge.i2c.axi4"

[[definition]]
type = "bridge.apb.axi4"

[[definition]]
type = "other.uart.zynqps8"
software = [{registers = "registers/uart", bankPrefix = "USB"}]
hardware = [{max_cores = 2}]

[[definition]]
type = "net.ethernet.zynqps8"
software = [{registers = "registers/gem", bankPrefix = "ENET"}]
hardware = [{max_cores = 4}]

[[definition]]
type = "storage.sdio.zynqps8"
software = [{registers = "registers/sdio", bankPrefix = "SD"}]
hardware = [{max_cores = 2}]

[[definition]]
type = "storage.qspi.zynqps8"
software = [{registers = "registers/qspi", bankPrefix = "QSPI"}]

