path = "socs/zynqps8"

[[include]]
resource = "software"

[[definition]]
type = "other.zynqps8.rawps8"
gateware = "gateware/ps8.toml"
registers = [
    { resource = "registers/afifm" },
    { resource = "registers/ams" },
    { resource = "registers/apu" },
    { resource = "registers/axipcie_dma" },
    { resource = "registers/axipcie_egress" },
    { resource = "registers/axipcie_ingress" },
    { resource = "registers/axipcie_main" },
    { resource = "registers/bbram" },
    { resource = "registers/can" },
    { resource = "registers/cci400" },
    { resource = "registers/cci_reg" },
    { resource = "registers/crf_apb" },
    { resource = "registers/crl_apb" },
    { resource = "registers/csu" },
    { resource = "registers/csudma" },
    { resource = "registers/dp" },
    { resource = "registers/dpdma" },
    { resource = "registers/dp_dpcd" },
    { resource = "registers/eedid" },
    { resource = "registers/efuse" },
    { resource = "registers/etf4k" },
    { resource = "registers/etf8k" },
    { resource = "registers/etr" },
    { resource = "registers/fpd_gpv" },
    { resource = "registers/fpd_slcr_secure" },
    { resource = "registers/fpd_slcr" },
    { resource = "registers/ftm" },
    { resource = "registers/funnel3p" },
    { resource = "registers/funnel4p" },
    { resource = "registers/gic400" },
    { resource = "registers/gpio" },
    { resource = "registers/iou_gpv" },
    { resource = "registers/iou_scntr" },
    { resource = "registers/iou_scntrs" },
    { resource = "registers/iou_secure_slcr" },
    { resource = "registers/iou_slcr" },
    { resource = "registers/ipi" },
    { resource = "registers/ipi_buffer" },
    { resource = "registers/lpd_gpv" },
    { resource = "registers/lpd_slcr_secure" },
    { resource = "registers/lpd_slcr" },
    { resource = "registers/mbistjtag" },
    { resource = "registers/ocm" },
    { resource = "registers/pcie_attrib" },
    { resource = "registers/pl390" },
    { resource = "registers/plsysmon" },
    { resource = "registers/pssysmon" },
    { resource = "registers/replic" },
    { resource = "registers/rpu" },
    { resource = "registers/rsa" },
    { resource = "registers/rsa_core" },
    { resource = "registers/rtc" },
    { resource = "registers/serdes" },
    { resource = "registers/serdes2" },
    { resource = "registers/siou" },
    { resource = "registers/smmu500" },
    { resource = "registers/smmu_reg" },
    { resource = "registers/stm" },
    { resource = "registers/swdt" },
    { resource = "registers/tpiu" },
    { resource = "registers/tsgen" },
    { resource = "registers/ttc" },
    { resource = "registers/usb3_regs" },
    { resource = "registers/usb3_xhci" },
    { resource = "registers/xmpu_ddr" },
    { resource = "registers/xmpu_fpd" },
    { resource = "registers/xmpu_ocm" },
    { resource = "registers/xmpu_sink" },
    { resource = "registers/xppu" },
    { resource = "registers/xppu_sink" },
    { resource = "registers/zdma" },
    { resource = "registers/pmu_global" },
]

[[definition]]
type = "bus.apb.zynqps8"

[[definition]]
type = "bus.axi4.zynqps8"

[[definition]]
type = "bridge.i2c.axi4"

[[definition]]
type = "bridge.internal.mainbus_to_apb"


