[[definition]]
type = "switch.axi.width_adapter.alexforencich"
gateware = "axi_width_adapter.toml"
buses = [
    { name = "in", protocol = "axi4", supplier = false, prefix = "s_axi_" },
    { name = "out", protocol = "axi4", supplier = true, prefix = "m_axi_" },
]

[[definition]]
type = "switch.axi.axil_adapter.alexforencich"
gateware = "axi_axil_adapter.toml"
buses = [
    { name = "in", protocol = "axi4", supplier = false, prefix = "s_axi_" },
    { name = "out", protocol = "axilite4", supplier = true, prefix = "m_axil_" },
]
