# Describe whats in a Ps8
# SRAMs
[[instance]]
  name = "tcm"
  type = "ram.sram.tcm"
  count = 2

[[instance]]
  name = "pmuram"
  type = "ram.sram.pmuram"

[[instance]]
  name = "ocp"
  type = "ram.sram.ocp"

# CPUs
[[instance]]
  name = "pmu"
  type = "cpu.pmu"

[[instance]]
  name = "a53"
  type = "cpu.a53"
  count = 4

[[instance]]
  name = "r5f"
  type = "cpu.r5f"
  count = 2

# Interconnects
[[instance]]
  name = "interconnect.main"
  type = "bus.axi4"

[[instance]]
  name = "interconnect.apb"
  type = "bus.apb"

# Bridges
[[instance]]
  name = "bridge.apb"
  type = "bridge.apb.axi4"

# connect every thing up
[[connection]]
  name = "connection.apb->main"
  type = "connection.axi4"
  connection = "bridge.apb -> interconnect.main"

[[connection]]
  name = "connection.arm_peri_bus->bridge"
  type = "connection.apb"
  connection = "interconnect.apb -> bridge.apb"

[[connection]]
  name = "connection.r5f->tcm"
  type = "connection.tcm"
  connection = "r5f -> tcm"

[[connection]]
  name = "connection.r5f->main"
  type = "connection.axi4"
  connection = "r5f -> interconnect.main"

[[connection]]
  name = "connection.pmu->pmuram"
  type = "connection.pmuram"
  connection = "pmu -> pmuram"

[[connection]]
  name = "connection.pmu->main"
  type = "connection.axi4"
  connection = "pmu -> interconnect.main"

[[connection]]
  name = "connection.a53->ocp"
  type = "connection.ocp"
  connection = "a53 -> ocp"

[[connection]]
  name = "connection.a53->main"
  type = "connection.axi4"
  connection = "a53 -> interconnect.main"