actions = [
    "make_config",
    "sbt_run",
    "src",
    "read_verilog_top"
]


[[process]]
name = 'make_config'
processor = 'toml'
filename = 'config.toml'
parameters = [
    "reset_clocks"
]

[[process]]
name = 'sbt_run'
processor = 'sbt'
main_scala = "apb_ctrl.scala"
with_build_sbt = true
args = '+runMain UartApbCtrl config.toml .. ${name}'
path_op = 'push'

[[process]]
name = 'src'
processor = 'source'
sources = [{ file ="${name}.v", language="verilog"}]

[[process]]
name = 'read_verilog_top'
processor = 'read_verilog_top'
source = "${name}"
