[[definition]]
type = "other.timer.watchdog.zynqps8"
registers = [
    { resource = "zynqps8/swdt.toml", base_address = "0x1cb0000" },
]
buses = [
    { protocol = "internal_swdt", supplier = false, data_width = 32 },
]
max_instances = 3