path = "qspi"

[[definition]]
type = "storage.qspi.zynqps8"
registers = [
    { resource = "zynqps8/qspi.toml", name = "QSPI", base_address = "0x020f_0000" }
]
buses = [
    { name = "iopunitsswitch_quadspi", supplier = false, data_width = 64, address_width = 32 },
    { name = "quadspi_iopoutbound", supplier = true, data_width = 32, address_width = 32 },
]