actions = [
    "templates"
]

[[process]]
name = 'templates'
processor = 'templates'
sources = [
    { in = "CMakeLists.txt", out = "CMakeLists.txt" },
    { in = "include/hw/reg_access.h", out = "include/hw/reg_access.h" },
    { in = "include/hw/cache.h", out = "include/hw/cache.h" },
    { in = "include/hw/memory_map.h", out = "include/hw/memory_map.h" },
    { in = "include/hw/cpu.h", out = "include/hw/cpu.h" },
    { in = "include/hw/cpu_percpu.h", out = "include/hw/${cpuName}/cpu.h", cpus = "_" },
    { in = "include/hw/memory_map_percpu.h", out = "include/hw/${cpuName}/memory_map.h", cpus = "_" },
    { in = "include/hw/aarch64/intrinsics_gcc.h", out = "include/hw/aarch64/intrinsics_gcc.h" },
    { in = "include/hw/microblaze/intrinsics_gcc.h", out = "include/hw/microblaze/intrinsics_gcc.h" },
    { in = "include/hw/zynqmp/pll_helper.h", out = "include/hw/zynqmp/pll_helper.h" },
    { in = "src/aarch64/cache.c", out = "src/aarch64/cache.c" },
    { in = "src/pmu/cache.c", out = "src/pmu/cache.c" },
    { in = "src/microblaze/disable_exceptions.S", out = "src/microblaze/disable_exceptions.S" },
    { in = "src/microblaze/enable_exceptions.S", out = "src/microblaze/enable_exceptions.S" },
    { in = "src/microblaze/disable_interrupts.S", out = "src/microblaze/disable_interrupts.S" },
    { in = "src/microblaze/enable_interrupts.S", out = "src/microblaze/enable_interrupts.S" },
    { in = "src/zynqmp/pll_helper.c", out = "src/zynqmp/pll_helper.c" }
]
