[[instance]]
name = "SDIO0"
type = "storage.sdio.zynqps8"
instance = 0

[[instance]]
name = "sdcard.slot0"
type = "storage.sdio.sdcard.slot"

[[instance]]
name = "DDR"
type = "ram.ddr.ddr4.zynqps8"
ranges = [
    { address = "0x0_0000_0000", fixed_address = true, size = "2 GiB" },
    { address = "0x8_0000_0000", fixed_address = true, size = "2 GiB" },
]

[[instance]]
name = "I2C0"
type = "switch.i2c.zynqps8"
instance = 0
visible_to_software = true

[[instance]]
name = "I2C1"
type = "switch.i2c.zynqps8"
instance = 1
visible_to_software = true

[[instance]]
name = "UART1"
type = "io.uart.zynqps8"
instance = 1

[[instance]]
name = "USB0"
type = "io.internal.usb.zynqps8"
instance = 0

[[instance]]
name = "QSPI"
type = "storage.qspi.zynqps8"

[[connection]]
type = "port"
connection = "SDIO0._ <- sdcard.slot0"

[[connection]]
type = "logical"
connection = "sdcard -> sdcard.slot0"

[[connection]]
type = "logical"
connection = "DDRController -> DDR"

[[connection]]
type = "port_group"
connection = "I2C0 -> BOARD.I2C0._"

[[connection]]
type = "logical"
connection = "kv260 -> PS8"
