[[instance]]
name = "sdcard"
type = "storage.sdio.zynqps8"
instance = 0

[[instance]]
name = "sdcard.slot0"
type = "storage.sdio.sdcard.slot"

[[instance]]
name = "ddr4.kv260"
type = "ram.ddr.ddr4.kv260"
size = "4 GiB"

[[instance]]
name = "uart.debug"
type = "io.uart.zynqps8"
instance = 1

[[connection]]
type = "port"
connection = "SDIO0._ <- sdcard.slot0"

[[connection]]
type = "bus"
connection = "mainBus -> mainDDR4"
address_offset = [["0x0000_0000", "2 GiB"], ["0x8_0000_0000", "2 GiB"], ]

[[connection]]
type = "bus"
connection = "apbBus -> sdcard"

[[connection]]
type = "bus"
connection = "apbBus -> uart._"

[[connection]]
type = "logical"
connection = "sdcard -> sdcard.slot0"

[[connection]]
type = "logical"
connection = "mainDDR4 -> ddr4.kv260"