[[instance]]
name = "sdcard"
type = "storage.sdio.zynqps8"
instance = 0

[[instance]]
name = "sdcard.slot0"
type = "storage.sdio.sdcard.slot"

[[instance]]
name = "emmc"
type = "storage.sdio.zynqps8"
instance = 1

[[instance]]
name = "emmc.MTFC8GAKAJCN"
type = "storage.sdio.emmc.MTFC8GAKAJCN"

[[instance]]
name = "qspi.MT25QU256ABA1EW9"
type = "storage.qspi.zynqps8"
size = "32 MiB"

[[instance]]
name = "ddr4.MT40A256M16LY"
type = "ram.ddr.ddr4.MT40A256M16LY"
size = "4 GiB"

[[instance]]
name = "uart.debug"
type = "io.uart.zynqps8"
instance = 0

[[connection]]
type = "port"
connection = "SDIO0._ <- sdcard.slot0"

[[connection]]
type = "port"
connection = "SDIO1._ <- emmc.MTFC8GAKAJCN"

#[[connection]]
#type = "bus"
#connection = "CCI -> DDRController"

#[[connection]]
#type = "bus"
#connection = "apbBus -> sdcard"

#[[connection]]
#type = "bus"
#connection = "apbBus -> emmc"

#[[connection]]
#type = "bus"
#connection = "apbBus -> qspi._"

#[[connection]]
#type = "bus"
#connection = "apbBus -> uart._"

[[connection]]
type = "logical"
connection = "sdcard -> sdcard.slot0"

[[connection]]
type = "logical"
connection = "emmc -> emmc.MTFC8GAKAJCN"

[[connection]]
type = "logical"
connection = "mainDDR4 -> ddr4.MT40A256M16LY"