/******************************************************************************
*
* Copyright (C) 2010-2020 Xilinx, Inc.  All rights reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/
/****************************************************************************/
/**
*
* @file psu_init.c
*
* This file is automatically generated
*
*****************************************************************************/

#include <xil_io.h>
#include <sleep.h>
#include "platform/reg_access.h"
//#include "platform/memory_map.h"
//#include "platform/registers/serdes.h"
#include "dbg/print.h"
#include "psu_init.h"
//Kishore -- ILL calibration code begins
//ILL calibration code begins
#define SERDES_L0_TM_PLL_DIG_33 		0XFD402084
#define SERDES_L1_TM_PLL_DIG_33 		0XFD406084
#define SERDES_L2_TM_PLL_DIG_33 		0XFD40A084
#define SERDES_L3_TM_PLL_DIG_33 		0XFD40E084

#define SERDES_L0_TM_ANA_BYP_4	 		0XFD401010
#define SERDES_L1_TM_ANA_BYP_4	 		0XFD405010
#define SERDES_L2_TM_ANA_BYP_4	 		0XFD409010
#define SERDES_L3_TM_ANA_BYP_4	 		0XFD40D010

#define SERDES_L0_TM_ANA_BYP_7	 		0XFD401018
#define SERDES_L1_TM_ANA_BYP_7	 		0XFD405018
#define SERDES_L2_TM_ANA_BYP_7	 		0XFD409018
#define SERDES_L3_TM_ANA_BYP_7	 		0XFD40D018

#define SERDES_L0_TM_E_ILL7	 		0XFD40193C
#define SERDES_L1_TM_E_ILL7	 		0XFD40593C
#define SERDES_L2_TM_E_ILL7	 		0XFD40993C
#define SERDES_L3_TM_E_ILL7	 		0XFD40D93C

#define SERDES_L0_TM_IQ_ILL7	 		0XFD401910
#define SERDES_L1_TM_IQ_ILL7	 		0XFD405910
#define SERDES_L2_TM_IQ_ILL7	 		0XFD409910
#define SERDES_L3_TM_IQ_ILL7	 		0XFD40D910

#define SERDES_L0_TX_DIG_TM_61	 		0XFD4000F4
#define SERDES_L1_TX_DIG_TM_61	 		0XFD4040F4
#define SERDES_L2_TX_DIG_TM_61	 		0XFD4080F4
#define SERDES_L3_TX_DIG_TM_61	 		0XFD40C0F4

#define SERDES_L0_TM_DIG_6	 		0XFD40106C
#define SERDES_L1_TM_DIG_6	 		0XFD40506C
#define SERDES_L2_TM_DIG_6	 		0XFD40906C
#define SERDES_L3_TM_DIG_6	 		0XFD40D06C

#define SERDES_L0_TM_IQ_ILL1                    0XFD4018F8
#define SERDES_L0_TM_IQ_ILL2                    0XFD4018FC
#define SERDES_L0_TM_ILL11                      0XFD40198C
#define SERDES_L0_TM_ILL12                      0XFD401990
#define SERDES_L0_TM_E_ILL1                     0XFD401924
#define SERDES_L0_TM_E_ILL2                     0XFD401928
#define SERDES_L0_TM_IQ_ILL3                    0XFD401900
#define SERDES_L0_TM_E_ILL3                     0XFD40192C
#define SERDES_L0_TM_ILL8                       0XFD401980
#define SERDES_L0_TM_IQ_ILL8                    0XFD401914
#define SERDES_L0_TM_IQ_ILL9                    0XFD401918
#define SERDES_L0_TM_E_ILL8                     0XFD401940
#define SERDES_L0_TM_E_ILL9                     0XFD401944
#define SERDES_L0_TM_ILL13                      0XFD401994
#define SERDES_L1_TM_MISC2                      0XFD40589C
#define SERDES_L1_TM_IQ_ILL1                    0XFD4058F8
#define SERDES_L1_TM_IQ_ILL2                    0XFD4058FC
#define SERDES_L1_TM_ILL11                      0XFD40598C
#define SERDES_L1_TM_ILL12                      0XFD405990
#define SERDES_L1_TM_E_ILL1                     0XFD405924
#define SERDES_L1_TM_E_ILL2                     0XFD405928
#define SERDES_L1_TM_IQ_ILL3                    0XFD405900
#define SERDES_L1_TM_E_ILL3                     0XFD40592C
#define SERDES_L1_TM_ILL8                       0XFD405980
#define SERDES_L1_TM_IQ_ILL8                    0XFD405914
#define SERDES_L1_TM_IQ_ILL9                    0XFD405918
#define SERDES_L1_TM_E_ILL8                     0XFD405940
#define SERDES_L1_TM_E_ILL9                     0XFD405944
#define SERDES_L1_TM_ILL13                      0XFD405994
#define SERDES_L2_TM_MISC2                      0XFD40989C
#define SERDES_L2_TM_IQ_ILL1                    0XFD4098F8
#define SERDES_L2_TM_IQ_ILL2                    0XFD4098FC
#define SERDES_L2_TM_ILL11                      0XFD40998C
#define SERDES_L2_TM_ILL12                      0XFD409990
#define SERDES_L2_TM_E_ILL1                     0XFD409924
#define SERDES_L2_TM_E_ILL2                     0XFD409928
#define SERDES_L2_TM_IQ_ILL3                    0XFD409900
#define SERDES_L2_TM_E_ILL3                     0XFD40992C
#define SERDES_L2_TM_ILL8                       0XFD409980
#define SERDES_L2_TM_IQ_ILL8                    0XFD409914
#define SERDES_L2_TM_IQ_ILL9                    0XFD409918
#define SERDES_L2_TM_E_ILL8                     0XFD409940
#define SERDES_L2_TM_E_ILL9                     0XFD409944
#define SERDES_L2_TM_ILL13                      0XFD409994
#define SERDES_L3_TM_MISC2                      0XFD40D89C
#define SERDES_L3_TM_IQ_ILL1                    0XFD40D8F8
#define SERDES_L3_TM_IQ_ILL2                    0XFD40D8FC
#define SERDES_L3_TM_ILL11                      0XFD40D98C
#define SERDES_L3_TM_ILL12                      0XFD40D990
#define SERDES_L3_TM_E_ILL1                     0XFD40D924
#define SERDES_L3_TM_E_ILL2                     0XFD40D928
#define SERDES_L3_TM_IQ_ILL3                    0XFD40D900
#define SERDES_L3_TM_E_ILL3                     0XFD40D92C
#define SERDES_L3_TM_ILL8                       0XFD40D980
#define SERDES_L3_TM_IQ_ILL8                    0XFD40D914
#define SERDES_L3_TM_IQ_ILL9                    0XFD40D918
#define SERDES_L3_TM_E_ILL8                     0XFD40D940
#define SERDES_L3_TM_E_ILL9                     0XFD40D944
#define SERDES_L3_TM_ILL13                      0XFD40D994
#undef SERDES_UPHY_SPARE0
#define SERDES_UPHY_SPARE0                      0XFD410098
#undef SERDES_UPHY_SPARE1
#define SERDES_UPHY_SPARE1                      0XFD41009C
#undef SERDES_UPHY_SPARE2
#define SERDES_UPHY_SPARE2                      0XFD4100A0
#undef SERDES_UPHY_SPARE3
#define SERDES_UPHY_SPARE3                      0XFD4100A4

#define SERDES_L0_PLL_FBDIV_FRAC_3_MSB 		0xFD402360
#define SERDES_L1_PLL_FBDIV_FRAC_3_MSB 		0xFD406360
#define SERDES_L2_PLL_FBDIV_FRAC_3_MSB 		0xFD40A360
#define SERDES_L3_PLL_FBDIV_FRAC_3_MSB 		0xFD40E360

#define SERDES_L0_PLL_STATUS_READ_1             0XFD4023E4
#define SERDES_L0_TM_MISC_ST_0	                0XFD401AC8
#define SERDES_L1_PLL_STATUS_READ_1             0XFD4063E4
#define SERDES_L1_TM_MISC_ST_0	                0XFD405AC8
#define SERDES_L2_PLL_STATUS_READ_1             0XFD40A3E4
#define SERDES_L2_TM_MISC_ST_0	                0XFD409AC8
#define SERDES_L3_PLL_STATUS_READ_1             0XFD40E3E4
#define SERDES_L3_TM_MISC_ST_0	                0XFD40DAC8

#define SERDES_L0_BIST_CTRL_1     		0xFD403004
#define SERDES_L0_BIST_CTRL_2     		0xFD403008
#define SERDES_L0_BIST_RUN_LEN_L     		0xFD40300C
#define SERDES_L0_BIST_ERR_INJ_POINT_L     	0xFD403010
#define SERDES_L0_BIST_RUNLEN_ERR_INJ_H     	0xFD403014
#define SERDES_L0_BIST_IDLE_TIME     		0xFD403018
#define SERDES_L0_BIST_MARKER_L     		0xFD40301C
#define SERDES_L0_BIST_IDLE_CHAR_L     		0xFD403020
#define SERDES_L0_BIST_MARKER_IDLE_H     	0xFD403024
#define SERDES_L0_BIST_LOW_PULSE_TIME     	0xFD403028
#define SERDES_L0_BIST_TOTAL_PULSE_TIME     	0xFD40302C
#define SERDES_L0_BIST_TEST_PAT_1     		0xFD403030
#define SERDES_L0_BIST_TEST_PAT_2     		0xFD403034
#define SERDES_L0_BIST_TEST_PAT_3     		0xFD403038
#define SERDES_L0_BIST_TEST_PAT_4     		0xFD40303C
#define SERDES_L0_BIST_TEST_PAT_MSBS     	0xFD403040
#define SERDES_L0_BIST_PKT_NUM     		0xFD403044
#define SERDES_L0_BIST_FRM_IDLE_TIME     	0xFD403048
#define SERDES_L0_BIST_PKT_CTR_L     		0xFD40304C
#define SERDES_L0_BIST_PKT_CTR_H     		0xFD403050
#define SERDES_L0_BIST_ERR_CTR_L     		0xFD403054
#define SERDES_L0_BIST_ERR_CTR_H     		0xFD403058
#define SERDES_L0_BIST_FILLER_OUT     		0xFD403068
#define SERDES_L0_BIST_FORCE_MK_RST     	0xFD40306C

#define SERDES_L1_BIST_CTRL_1     		0xFD407004
#define SERDES_L1_BIST_CTRL_2     		0xFD407008
#define SERDES_L1_BIST_RUN_LEN_L     		0xFD40700C
#define SERDES_L1_BIST_ERR_INJ_POINT_L     	0xFD407010
#define SERDES_L1_BIST_RUNLEN_ERR_INJ_H     	0xFD407014
#define SERDES_L1_BIST_IDLE_TIME     		0xFD407018
#define SERDES_L1_BIST_MARKER_L     		0xFD40701C
#define SERDES_L1_BIST_IDLE_CHAR_L     		0xFD407020
#define SERDES_L1_BIST_MARKER_IDLE_H     	0xFD407024
#define SERDES_L1_BIST_LOW_PULSE_TIME     	0xFD407028
#define SERDES_L1_BIST_TOTAL_PULSE_TIME     	0xFD40702C
#define SERDES_L1_BIST_TEST_PAT_1     		0xFD407030
#define SERDES_L1_BIST_TEST_PAT_2     		0xFD407034
#define SERDES_L1_BIST_TEST_PAT_3     		0xFD407038
#define SERDES_L1_BIST_TEST_PAT_4     		0xFD40703C
#define SERDES_L1_BIST_TEST_PAT_MSBS     	0xFD407040
#define SERDES_L1_BIST_PKT_NUM     		0xFD407044
#define SERDES_L1_BIST_FRM_IDLE_TIME     	0xFD407048
#define SERDES_L1_BIST_PKT_CTR_L     		0xFD40704C
#define SERDES_L1_BIST_PKT_CTR_H     		0xFD407050
#define SERDES_L1_BIST_ERR_CTR_L     		0xFD407054
#define SERDES_L1_BIST_ERR_CTR_H     		0xFD407058
#define SERDES_L1_BIST_FILLER_OUT     		0xFD407068
#define SERDES_L1_BIST_FORCE_MK_RST     	0xFD40706C

#define SERDES_L2_BIST_CTRL_1     		0xFD40B004
#define SERDES_L2_BIST_CTRL_2     		0xFD40B008
#define SERDES_L2_BIST_RUN_LEN_L     		0xFD40B00C
#define SERDES_L2_BIST_ERR_INJ_POINT_L     	0xFD40B010
#define SERDES_L2_BIST_RUNLEN_ERR_INJ_H     	0xFD40B014
#define SERDES_L2_BIST_IDLE_TIME     		0xFD40B018
#define SERDES_L2_BIST_MARKER_L     		0xFD40B01C
#define SERDES_L2_BIST_IDLE_CHAR_L     		0xFD40B020
#define SERDES_L2_BIST_MARKER_IDLE_H     	0xFD40B024
#define SERDES_L2_BIST_LOW_PULSE_TIME     	0xFD40B028
#define SERDES_L2_BIST_TOTAL_PULSE_TIME     	0xFD40B02C
#define SERDES_L2_BIST_TEST_PAT_1     		0xFD40B030
#define SERDES_L2_BIST_TEST_PAT_2     		0xFD40B034
#define SERDES_L2_BIST_TEST_PAT_3     		0xFD40B038
#define SERDES_L2_BIST_TEST_PAT_4     		0xFD40B03C
#define SERDES_L2_BIST_TEST_PAT_MSBS     	0xFD40B040
#define SERDES_L2_BIST_PKT_NUM     		0xFD40B044
#define SERDES_L2_BIST_FRM_IDLE_TIME     	0xFD40B048
#define SERDES_L2_BIST_PKT_CTR_L     		0xFD40B04C
#define SERDES_L2_BIST_PKT_CTR_H     		0xFD40B050
#define SERDES_L2_BIST_ERR_CTR_L     		0xFD40B054
#define SERDES_L2_BIST_ERR_CTR_H     		0xFD40B058
#define SERDES_L2_BIST_FILLER_OUT     		0xFD40B068
#define SERDES_L2_BIST_FORCE_MK_RST     	0xFD40B06C

#define SERDES_L3_BIST_CTRL_1     		0xFD40F004
#define SERDES_L3_BIST_CTRL_2     		0xFD40F008
#define SERDES_L3_BIST_RUN_LEN_L     		0xFD40F00C
#define SERDES_L3_BIST_ERR_INJ_POINT_L     	0xFD40F010
#define SERDES_L3_BIST_RUNLEN_ERR_INJ_H     	0xFD40F014
#define SERDES_L3_BIST_IDLE_TIME     		0xFD40F018
#define SERDES_L3_BIST_MARKER_L     		0xFD40F01C
#define SERDES_L3_BIST_IDLE_CHAR_L     		0xFD40F020
#define SERDES_L3_BIST_MARKER_IDLE_H     	0xFD40F024
#define SERDES_L3_BIST_LOW_PULSE_TIME     	0xFD40F028
#define SERDES_L3_BIST_TOTAL_PULSE_TIME     	0xFD40F02C
#define SERDES_L3_BIST_TEST_PAT_1     		0xFD40F030
#define SERDES_L3_BIST_TEST_PAT_2     		0xFD40F034
#define SERDES_L3_BIST_TEST_PAT_3     		0xFD40F038
#define SERDES_L3_BIST_TEST_PAT_4     		0xFD40F03C
#define SERDES_L3_BIST_TEST_PAT_MSBS     	0xFD40F040
#define SERDES_L3_BIST_PKT_NUM     		0xFD40F044
#define SERDES_L3_BIST_FRM_IDLE_TIME     	0xFD40F048
#define SERDES_L3_BIST_PKT_CTR_L     		0xFD40F04C
#define SERDES_L3_BIST_PKT_CTR_H     		0xFD40F050
#define SERDES_L3_BIST_ERR_CTR_L     		0xFD40F054
#define SERDES_L3_BIST_ERR_CTR_H     		0xFD40F058
#define SERDES_L3_BIST_FILLER_OUT     		0xFD40F068
#define SERDES_L3_BIST_FORCE_MK_RST     	0xFD40F06C

#define SERDES_TX_PROT_BUS_WIDTH     		0xFD410040
#define SERDES_RX_PROT_BUS_WIDTH     		0xFD410044
#define SERDES_LPBK_CTRL0     			0xFD410038
#define SERDES_LPBK_CTRL1     			0xFD41003C
#define SERDES_L0_TM_DIG_22    			0xFD4010AC
#define SERDES_L1_TM_DIG_22    			0xFD4050AC
#define SERDES_L2_TM_DIG_22    			0xFD4090AC
#define SERDES_L3_TM_DIG_22    			0xFD40D0AC
#define SERDES_L0_DATA_BUS_WID     		0xFD403060
#define SERDES_L1_DATA_BUS_WID     		0xFD407060
#define SERDES_L2_DATA_BUS_WID     		0xFD40B060
#define SERDES_L3_DATA_BUS_WID     		0xFD40F060
#define SERDES_L0_TX_ANA_TM_3     		0XFD40000C
#define SERDES_L1_TX_ANA_TM_3     		0XFD40400C
#define SERDES_L2_TX_ANA_TM_3     		0XFD40800C
#define SERDES_L3_TX_ANA_TM_3     		0XFD40C00C

#undef SERDES_PLL_REF_SEL0_OFFSET
#define SERDES_PLL_REF_SEL0_OFFSET  		0xFD410000
#undef SERDES_PLL_REF_SEL1_OFFSET
#define SERDES_PLL_REF_SEL1_OFFSET  		0xFD410004
#undef SERDES_PLL_REF_SEL2_OFFSET
#define SERDES_PLL_REF_SEL2_OFFSET  		0xFD410008
#undef SERDES_PLL_REF_SEL3_OFFSET
#define SERDES_PLL_REF_SEL3_OFFSET  		0xFD41000C
#undef SERDES_ICM_CFG0_OFFSET
#define SERDES_ICM_CFG0_OFFSET     		0xFD410010
#undef SERDES_ICM_CFG1_OFFSET
#define SERDES_ICM_CFG1_OFFSET     		0xFD410014
#undef SERDES_PLL_REF_SEL0_OFFSET
#define SERDES_PLL_REF_SEL0_OFFSET                                                 0XFD410000
#undef SERDES_PLL_REF_SEL1_OFFSET
#define SERDES_PLL_REF_SEL1_OFFSET                                                 0XFD410004
#undef SERDES_PLL_REF_SEL2_OFFSET
#define SERDES_PLL_REF_SEL2_OFFSET                                                 0XFD410008
#undef SERDES_PLL_REF_SEL3_OFFSET
#define SERDES_PLL_REF_SEL3_OFFSET                                                 0XFD41000C
#undef SERDES_L0_L0_REF_CLK_SEL_OFFSET
#define SERDES_L0_L0_REF_CLK_SEL_OFFSET                                            0XFD402860
#undef SERDES_L0_L1_REF_CLK_SEL_OFFSET
#define SERDES_L0_L1_REF_CLK_SEL_OFFSET                                            0XFD402864
#undef SERDES_L0_L2_REF_CLK_SEL_OFFSET
#define SERDES_L0_L2_REF_CLK_SEL_OFFSET                                            0XFD402868
#undef SERDES_L0_L3_REF_CLK_SEL_OFFSET
#define SERDES_L0_L3_REF_CLK_SEL_OFFSET                                            0XFD40286C
#undef SERDES_L2_TM_PLL_DIG_37_OFFSET
#define SERDES_L2_TM_PLL_DIG_37_OFFSET                                             0XFD40A094
#undef SERDES_L3_TM_PLL_DIG_37_OFFSET
#define SERDES_L3_TM_PLL_DIG_37_OFFSET                                             0XFD40E094
#undef SERDES_L2_PLL_SS_STEPS_0_LSB_OFFSET
#define SERDES_L2_PLL_SS_STEPS_0_LSB_OFFSET                                        0XFD40A368
#undef SERDES_L2_PLL_SS_STEPS_1_MSB_OFFSET
#define SERDES_L2_PLL_SS_STEPS_1_MSB_OFFSET                                        0XFD40A36C
#undef SERDES_L3_PLL_SS_STEPS_0_LSB_OFFSET
#define SERDES_L3_PLL_SS_STEPS_0_LSB_OFFSET                                        0XFD40E368
#undef SERDES_L3_PLL_SS_STEPS_1_MSB_OFFSET
#define SERDES_L3_PLL_SS_STEPS_1_MSB_OFFSET                                        0XFD40E36C
#undef SERDES_L0_PLL_SS_STEPS_0_LSB_OFFSET
#define SERDES_L0_PLL_SS_STEPS_0_LSB_OFFSET                                        0XFD402368
#undef SERDES_L0_PLL_SS_STEPS_1_MSB_OFFSET
#define SERDES_L0_PLL_SS_STEPS_1_MSB_OFFSET                                        0XFD40236C
#undef SERDES_L1_PLL_SS_STEPS_0_LSB_OFFSET
#define SERDES_L1_PLL_SS_STEPS_0_LSB_OFFSET                                        0XFD406368
#undef SERDES_L1_PLL_SS_STEPS_1_MSB_OFFSET
#define SERDES_L1_PLL_SS_STEPS_1_MSB_OFFSET                                        0XFD40636C
#undef SERDES_L0_PLL_SS_STEP_SIZE_0_LSB_OFFSET
#define SERDES_L0_PLL_SS_STEP_SIZE_0_LSB_OFFSET                                    0XFD402370
#undef SERDES_L0_PLL_SS_STEP_SIZE_1_OFFSET
#define SERDES_L0_PLL_SS_STEP_SIZE_1_OFFSET                                        0XFD402374
#undef SERDES_L0_PLL_SS_STEP_SIZE_2_OFFSET
#define SERDES_L0_PLL_SS_STEP_SIZE_2_OFFSET                                        0XFD402378
#undef SERDES_L0_PLL_SS_STEP_SIZE_3_MSB_OFFSET
#define SERDES_L0_PLL_SS_STEP_SIZE_3_MSB_OFFSET                                    0XFD40237C
#undef SERDES_L1_PLL_SS_STEP_SIZE_0_LSB_OFFSET
#define SERDES_L1_PLL_SS_STEP_SIZE_0_LSB_OFFSET                                    0XFD406370
#undef SERDES_L1_PLL_SS_STEP_SIZE_1_OFFSET
#define SERDES_L1_PLL_SS_STEP_SIZE_1_OFFSET                                        0XFD406374
#undef SERDES_L1_PLL_SS_STEP_SIZE_2_OFFSET
#define SERDES_L1_PLL_SS_STEP_SIZE_2_OFFSET                                        0XFD406378
#undef SERDES_L1_PLL_SS_STEP_SIZE_3_MSB_OFFSET
#define SERDES_L1_PLL_SS_STEP_SIZE_3_MSB_OFFSET                                    0XFD40637C
#undef SERDES_L2_PLL_SS_STEP_SIZE_0_LSB_OFFSET
#define SERDES_L2_PLL_SS_STEP_SIZE_0_LSB_OFFSET                                    0XFD40A370
#undef SERDES_L2_PLL_SS_STEP_SIZE_1_OFFSET
#define SERDES_L2_PLL_SS_STEP_SIZE_1_OFFSET                                        0XFD40A374
#undef SERDES_L2_PLL_SS_STEP_SIZE_2_OFFSET
#define SERDES_L2_PLL_SS_STEP_SIZE_2_OFFSET                                        0XFD40A378
#undef SERDES_L2_PLL_SS_STEP_SIZE_3_MSB_OFFSET
#define SERDES_L2_PLL_SS_STEP_SIZE_3_MSB_OFFSET                                    0XFD40A37C
#undef SERDES_L3_PLL_SS_STEP_SIZE_0_LSB_OFFSET
#define SERDES_L3_PLL_SS_STEP_SIZE_0_LSB_OFFSET                                    0XFD40E370
#undef SERDES_L3_PLL_SS_STEP_SIZE_1_OFFSET
#define SERDES_L3_PLL_SS_STEP_SIZE_1_OFFSET                                        0XFD40E374
#undef SERDES_L3_PLL_SS_STEP_SIZE_2_OFFSET
#define SERDES_L3_PLL_SS_STEP_SIZE_2_OFFSET                                        0XFD40E378
#undef SERDES_L3_PLL_SS_STEP_SIZE_3_MSB_OFFSET
#define SERDES_L3_PLL_SS_STEP_SIZE_3_MSB_OFFSET                                    0XFD40E37C
#undef SERDES_L2_TM_DIG_6_OFFSET
#define SERDES_L2_TM_DIG_6_OFFSET                                                  0XFD40906C
#undef SERDES_L2_TX_DIG_TM_61_OFFSET
#define SERDES_L2_TX_DIG_TM_61_OFFSET                                              0XFD4080F4
#undef SERDES_L3_TM_DIG_6_OFFSET
#define SERDES_L3_TM_DIG_6_OFFSET                                                  0XFD40D06C
#undef SERDES_L3_TX_DIG_TM_61_OFFSET
#define SERDES_L3_TX_DIG_TM_61_OFFSET                                              0XFD40C0F4
#undef SERDES_L2_TM_AUX_0_OFFSET
#define SERDES_L2_TM_AUX_0_OFFSET                                                  0XFD4090CC
#undef SERDES_L3_TM_AUX_0_OFFSET
#define SERDES_L3_TM_AUX_0_OFFSET                                                  0XFD40D0CC
#undef SERDES_L0_TM_DIG_8_OFFSET
#define SERDES_L0_TM_DIG_8_OFFSET                                                  0XFD401074
#undef SERDES_L1_TM_DIG_8_OFFSET
#define SERDES_L1_TM_DIG_8_OFFSET                                                  0XFD405074
#undef SERDES_L2_TM_DIG_8_OFFSET
#define SERDES_L2_TM_DIG_8_OFFSET                                                  0XFD409074
#undef SERDES_L3_TM_DIG_8_OFFSET
#define SERDES_L3_TM_DIG_8_OFFSET                                                  0XFD40D074
#undef SERDES_L0_TM_ILL13_OFFSET
#define SERDES_L0_TM_ILL13_OFFSET                                                  0XFD401994
#undef SERDES_L1_TM_ILL13_OFFSET
#define SERDES_L1_TM_ILL13_OFFSET                                                  0XFD405994
#undef SERDES_L2_TM_MISC2_OFFSET
#define SERDES_L2_TM_MISC2_OFFSET                                                  0XFD40989C
#undef SERDES_L2_TM_IQ_ILL1_OFFSET
#define SERDES_L2_TM_IQ_ILL1_OFFSET                                                0XFD4098F8
#undef SERDES_L2_TM_IQ_ILL2_OFFSET
#define SERDES_L2_TM_IQ_ILL2_OFFSET                                                0XFD4098FC
#undef SERDES_L2_TM_ILL12_OFFSET
#define SERDES_L2_TM_ILL12_OFFSET                                                  0XFD409990
#undef SERDES_L2_TM_E_ILL1_OFFSET
#define SERDES_L2_TM_E_ILL1_OFFSET                                                 0XFD409924
#undef SERDES_L2_TM_E_ILL2_OFFSET
#define SERDES_L2_TM_E_ILL2_OFFSET                                                 0XFD409928
#undef SERDES_L2_TM_IQ_ILL3_OFFSET
#define SERDES_L2_TM_IQ_ILL3_OFFSET                                                0XFD409900
#undef SERDES_L2_TM_E_ILL3_OFFSET
#define SERDES_L2_TM_E_ILL3_OFFSET                                                 0XFD40992C
#undef SERDES_L2_TM_ILL8_OFFSET
#define SERDES_L2_TM_ILL8_OFFSET                                                   0XFD409980
#undef SERDES_L2_TM_IQ_ILL8_OFFSET
#define SERDES_L2_TM_IQ_ILL8_OFFSET                                                0XFD409914
#undef SERDES_L2_TM_IQ_ILL9_OFFSET
#define SERDES_L2_TM_IQ_ILL9_OFFSET                                                0XFD409918
#undef SERDES_L2_TM_E_ILL8_OFFSET
#define SERDES_L2_TM_E_ILL8_OFFSET                                                 0XFD409940
#undef SERDES_L2_TM_E_ILL9_OFFSET
#define SERDES_L2_TM_E_ILL9_OFFSET                                                 0XFD409944
#undef SERDES_L2_TM_ILL13_OFFSET
#define SERDES_L2_TM_ILL13_OFFSET                                                  0XFD409994
#undef SERDES_L3_TM_MISC2_OFFSET
#define SERDES_L3_TM_MISC2_OFFSET                                                  0XFD40D89C
#undef SERDES_L3_TM_IQ_ILL1_OFFSET
#define SERDES_L3_TM_IQ_ILL1_OFFSET                                                0XFD40D8F8
#undef SERDES_L3_TM_IQ_ILL2_OFFSET
#define SERDES_L3_TM_IQ_ILL2_OFFSET                                                0XFD40D8FC
#undef SERDES_L3_TM_ILL12_OFFSET
#define SERDES_L3_TM_ILL12_OFFSET                                                  0XFD40D990
#undef SERDES_L3_TM_E_ILL1_OFFSET
#define SERDES_L3_TM_E_ILL1_OFFSET                                                 0XFD40D924
#undef SERDES_L3_TM_E_ILL2_OFFSET
#define SERDES_L3_TM_E_ILL2_OFFSET                                                 0XFD40D928
#undef SERDES_L3_TM_IQ_ILL3_OFFSET
#define SERDES_L3_TM_IQ_ILL3_OFFSET                                                0XFD40D900
#undef SERDES_L3_TM_E_ILL3_OFFSET
#define SERDES_L3_TM_E_ILL3_OFFSET                                                 0XFD40D92C
#undef SERDES_L3_TM_ILL8_OFFSET
#define SERDES_L3_TM_ILL8_OFFSET                                                   0XFD40D980
#undef SERDES_L3_TM_IQ_ILL8_OFFSET
#define SERDES_L3_TM_IQ_ILL8_OFFSET                                                0XFD40D914
#undef SERDES_L3_TM_IQ_ILL9_OFFSET
#define SERDES_L3_TM_IQ_ILL9_OFFSET                                                0XFD40D918
#undef SERDES_L3_TM_E_ILL8_OFFSET
#define SERDES_L3_TM_E_ILL8_OFFSET                                                 0XFD40D940
#undef SERDES_L3_TM_E_ILL9_OFFSET
#define SERDES_L3_TM_E_ILL9_OFFSET                                                 0XFD40D944
#undef SERDES_L3_TM_ILL13_OFFSET
#define SERDES_L3_TM_ILL13_OFFSET                                                  0XFD40D994
#undef SERDES_L0_TM_DIG_10_OFFSET
#define SERDES_L0_TM_DIG_10_OFFSET                                                 0XFD40107C
#undef SERDES_L1_TM_DIG_10_OFFSET
#define SERDES_L1_TM_DIG_10_OFFSET                                                 0XFD40507C
#undef SERDES_L2_TM_DIG_10_OFFSET
#define SERDES_L2_TM_DIG_10_OFFSET                                                 0XFD40907C
#undef SERDES_L3_TM_DIG_10_OFFSET
#define SERDES_L3_TM_DIG_10_OFFSET                                                 0XFD40D07C
#undef SERDES_L0_TM_RST_DLY_OFFSET
#define SERDES_L0_TM_RST_DLY_OFFSET                                                0XFD4019A4
#undef SERDES_L0_TM_ANA_BYP_15_OFFSET
#define SERDES_L0_TM_ANA_BYP_15_OFFSET                                             0XFD401038
#undef SERDES_L0_TM_ANA_BYP_12_OFFSET
#define SERDES_L0_TM_ANA_BYP_12_OFFSET                                             0XFD40102C
#undef SERDES_L1_TM_RST_DLY_OFFSET
#define SERDES_L1_TM_RST_DLY_OFFSET                                                0XFD4059A4
#undef SERDES_L1_TM_ANA_BYP_15_OFFSET
#define SERDES_L1_TM_ANA_BYP_15_OFFSET                                             0XFD405038
#undef SERDES_L1_TM_ANA_BYP_12_OFFSET
#define SERDES_L1_TM_ANA_BYP_12_OFFSET                                             0XFD40502C
#undef SERDES_L2_TM_RST_DLY_OFFSET
#define SERDES_L2_TM_RST_DLY_OFFSET                                                0XFD4099A4
#undef SERDES_L2_TM_ANA_BYP_15_OFFSET
#define SERDES_L2_TM_ANA_BYP_15_OFFSET                                             0XFD409038
#undef SERDES_L2_TM_ANA_BYP_12_OFFSET
#define SERDES_L2_TM_ANA_BYP_12_OFFSET                                             0XFD40902C
#undef SERDES_L3_TM_RST_DLY_OFFSET
#define SERDES_L3_TM_RST_DLY_OFFSET                                                0XFD40D9A4
#undef SERDES_L3_TM_ANA_BYP_15_OFFSET
#define SERDES_L3_TM_ANA_BYP_15_OFFSET                                             0XFD40D038
#undef SERDES_L3_TM_ANA_BYP_12_OFFSET
#define SERDES_L3_TM_ANA_BYP_12_OFFSET                                             0XFD40D02C
#undef SERDES_L0_TM_MISC3_OFFSET
#define SERDES_L0_TM_MISC3_OFFSET                                                  0XFD4019AC
#undef SERDES_L1_TM_MISC3_OFFSET
#define SERDES_L1_TM_MISC3_OFFSET                                                  0XFD4059AC
#undef SERDES_L2_TM_MISC3_OFFSET
#define SERDES_L2_TM_MISC3_OFFSET                                                  0XFD4099AC
#undef SERDES_L3_TM_MISC3_OFFSET
#define SERDES_L3_TM_MISC3_OFFSET                                                  0XFD40D9AC
#undef SERDES_L0_TM_EQ11_OFFSET
#define SERDES_L0_TM_EQ11_OFFSET                                                   0XFD401978
#undef SERDES_L1_TM_EQ11_OFFSET
#define SERDES_L1_TM_EQ11_OFFSET                                                   0XFD405978
#undef SERDES_L2_TM_EQ11_OFFSET
#define SERDES_L2_TM_EQ11_OFFSET                                                   0XFD409978
#undef SERDES_L3_TM_EQ11_OFFSET
#define SERDES_L3_TM_EQ11_OFFSET                                                   0XFD40D978
#undef SERDES_ICM_CFG0_OFFSET
#define SERDES_ICM_CFG0_OFFSET                                                     0XFD410010
#undef SERDES_ICM_CFG1_OFFSET
#define SERDES_ICM_CFG1_OFFSET                                                     0XFD410014
#undef SERDES_L0_TXPMD_TM_45_OFFSET
#define SERDES_L0_TXPMD_TM_45_OFFSET                                               0XFD400CB4
#undef SERDES_L1_TXPMD_TM_45_OFFSET
#define SERDES_L1_TXPMD_TM_45_OFFSET                                               0XFD404CB4
#undef SERDES_L0_TX_ANA_TM_118_OFFSET
#define SERDES_L0_TX_ANA_TM_118_OFFSET                                             0XFD4001D8
#undef SERDES_L1_TX_ANA_TM_118_OFFSET
#define SERDES_L1_TX_ANA_TM_118_OFFSET                                             0XFD4041D8
#undef SERDES_L1_TXPMD_TM_48_OFFSET
#define SERDES_L1_TXPMD_TM_48_OFFSET                                               0XFD404CC0
#undef SERDES_L0_TXPMD_TM_48_OFFSET
#define SERDES_L0_TXPMD_TM_48_OFFSET                                               0XFD400CC0
#undef SERDES_L1_TX_ANA_TM_18_OFFSET
#define SERDES_L1_TX_ANA_TM_18_OFFSET                                              0XFD404048
#undef SERDES_L0_TX_ANA_TM_18_OFFSET
#define SERDES_L0_TX_ANA_TM_18_OFFSET                                              0XFD400048

void mask_delay(uint32_t delay)
{
	usleep(delay);
}



void PSU_Mask_Write(unsigned long offset, unsigned long mask,
										unsigned long val)
{
	unsigned long RegVal = 0x0;

	RegVal = Xil_In32(offset);
	RegVal &= ~(mask);
	RegVal |= (val & mask);
	Xil_Out32(offset, RegVal);
}

#if 0
unsigned long psu_apply_master_tz(void)
{
	/*
	* RPU
	*/
	/*
	* DP TZ
	*/
	/*
	* Register : slcr_dpdma @ 0XFD690040

	* TrustZone classification for DisplayPort DMA
	*  PSU_FPD_SLCR_SECURE_SLCR_DPDMA_TZ                           1

	* DPDMA TrustZone Settings
	* (OFFSET, MASK, VALUE)      (0XFD690040, 0x00000001U ,0x00000001U)
	*/
	PSU_Mask_Write(FPD_SLCR_SECURE_SLCR_DPDMA_OFFSET,
								 0x00000001U, 0x00000001U);
	/*##################################################################### */

	/*
	* SATA TZ
	*/
	/*
	* PCIE TZ
	*/
	/*
	* Register : slcr_pcie @ 0XFD690030

	* TrustZone classification for DMA Channel 0
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_DMA_0                      1

	* TrustZone classification for DMA Channel 1
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_DMA_1                      1

	* TrustZone classification for DMA Channel 2
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_DMA_2                      1

	* TrustZone classification for DMA Channel 3
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_DMA_3                      1

	* TrustZone classification for Ingress Address Translation 0
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_INGR_0                  1

	* TrustZone classification for Ingress Address Translation 1
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_INGR_1                  1

	* TrustZone classification for Ingress Address Translation 2
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_INGR_2                  1

	* TrustZone classification for Ingress Address Translation 3
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_INGR_3                  1

	* TrustZone classification for Ingress Address Translation 4
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_INGR_4                  1

	* TrustZone classification for Ingress Address Translation 5
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_INGR_5                  1

	* TrustZone classification for Ingress Address Translation 6
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_INGR_6                  1

	* TrustZone classification for Ingress Address Translation 7
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_INGR_7                  1

	* TrustZone classification for Egress Address Translation 0
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_EGR_0                   1

	* TrustZone classification for Egress Address Translation 1
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_EGR_1                   1

	* TrustZone classification for Egress Address Translation 2
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_EGR_2                   1

	* TrustZone classification for Egress Address Translation 3
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_EGR_3                   1

	* TrustZone classification for Egress Address Translation 4
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_EGR_4                   1

	* TrustZone classification for Egress Address Translation 5
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_EGR_5                   1

	* TrustZone classification for Egress Address Translation 6
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_EGR_6                   1

	* TrustZone classification for Egress Address Translation 7
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_AT_EGR_7                   1

	* TrustZone classification for DMA Registers
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_DMA_REGS                   1

	* TrustZone classification for MSIx Table
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_MSIX_TABLE                 1

	* TrustZone classification for MSIx PBA
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_MSIX_PBA                   1

	* TrustZone classification for ECAM
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_ECAM                       1

	* TrustZone classification for Bridge Common Registers
	*  PSU_FPD_SLCR_SECURE_SLCR_PCIE_TZ_BRIDGE_REGS                1

	* PCIe TrustZone settings. This register may only be modified during bootu
	* p (while PCIe block is disabled)
	* (OFFSET, MASK, VALUE)      (0XFD690030, 0x01FFFFFFU ,0x01FFFFFFU)
	*/
	PSU_Mask_Write(FPD_SLCR_SECURE_SLCR_PCIE_OFFSET,
								 0x01FFFFFFU, 0x01FFFFFFU);
	/*##################################################################### */

	/*
	* USB TZ
	*/
	/*
	* Register : slcr_usb @ 0XFF4B0034

	* TrustZone Classification for USB3_0
	*  PSU_LPD_SLCR_SECURE_SLCR_USB_TZ_USB3_0                      1

	* TrustZone Classification for USB3_1
	*  PSU_LPD_SLCR_SECURE_SLCR_USB_TZ_USB3_1                      1

	* USB3 TrustZone settings
	* (OFFSET, MASK, VALUE)      (0XFF4B0034, 0x00000003U ,0x00000003U)
	*/
	PSU_Mask_Write(LPD_SLCR_SECURE_SLCR_USB_OFFSET,
								 0x00000003U, 0x00000003U);
	/*##################################################################### */

	/*
	* SD TZ
	*/
	/*
	* Register : IOU_AXI_RPRTCN @ 0XFF240004

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_RPRTCN_SD0_AXI_ARPROT           2

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_RPRTCN_SD1_AXI_ARPROT           2

	* AXI read protection type selection
	* (OFFSET, MASK, VALUE)      (0XFF240004, 0x003F0000U ,0x00120000U)
	*/
	PSU_Mask_Write(IOU_SECURE_SLCR_IOU_AXI_RPRTCN_OFFSET,
								 0x003F0000U, 0x00120000U);
	/*##################################################################### */

	/*
	* Register : IOU_AXI_WPRTCN @ 0XFF240000

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_WPRTCN_SD0_AXI_AWPROT           2

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_WPRTCN_SD1_AXI_AWPROT           2

	* AXI write protection type selection
	* (OFFSET, MASK, VALUE)      (0XFF240000, 0x003F0000U ,0x00120000U)
	*/
	PSU_Mask_Write(IOU_SECURE_SLCR_IOU_AXI_WPRTCN_OFFSET,
								 0x003F0000U, 0x00120000U);
	/*##################################################################### */

	/*
	* GEM TZ
	*/
	/*
	* Register : IOU_AXI_RPRTCN @ 0XFF240004

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_RPRTCN_GEM0_AXI_ARPROT          2

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_RPRTCN_GEM1_AXI_ARPROT          2

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_RPRTCN_GEM2_AXI_ARPROT          2

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_RPRTCN_GEM3_AXI_ARPROT          2

	* AXI read protection type selection
	* (OFFSET, MASK, VALUE)      (0XFF240004, 0x00000FFFU ,0x00000492U)
	*/
	PSU_Mask_Write(IOU_SECURE_SLCR_IOU_AXI_RPRTCN_OFFSET,
								 0x00000FFFU, 0x00000492U);
	/*##################################################################### */

	/*
	* Register : IOU_AXI_WPRTCN @ 0XFF240000

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_WPRTCN_GEM0_AXI_AWPROT          2

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_WPRTCN_GEM1_AXI_AWPROT          2

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_WPRTCN_GEM2_AXI_AWPROT          2

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_WPRTCN_GEM3_AXI_AWPROT          2

	* AXI write protection type selection
	* (OFFSET, MASK, VALUE)      (0XFF240000, 0x00000FFFU ,0x00000492U)
	*/
	PSU_Mask_Write(IOU_SECURE_SLCR_IOU_AXI_WPRTCN_OFFSET,
								 0x00000FFFU, 0x00000492U);
	/*##################################################################### */

	/*
	* QSPI TZ
	*/
	/*
	* Register : IOU_AXI_WPRTCN @ 0XFF240000

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_WPRTCN_QSPI_AXI_AWPROT          2

	* AXI write protection type selection
	* (OFFSET, MASK, VALUE)      (0XFF240000, 0x0E000000U ,0x04000000U)
	*/
	PSU_Mask_Write(IOU_SECURE_SLCR_IOU_AXI_WPRTCN_OFFSET,
								 0x0E000000U, 0x04000000U);
	/*##################################################################### */

	/*
	* NAND TZ
	*/
	/*
	* Register : IOU_AXI_RPRTCN @ 0XFF240004

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_RPRTCN_NAND_AXI_ARPROT          2

	* AXI read protection type selection
	* (OFFSET, MASK, VALUE)      (0XFF240004, 0x01C00000U ,0x00800000U)
	*/
	PSU_Mask_Write(IOU_SECURE_SLCR_IOU_AXI_RPRTCN_OFFSET,
								 0x01C00000U, 0x00800000U);
	/*##################################################################### */

	/*
	* Register : IOU_AXI_WPRTCN @ 0XFF240000

	* AXI protection [0] = '0' : Normal access [0] = '1' : Previleged access [
	* 1] = '0' : Secure access [1] = '1' : No secure access [2] = '0' : Data a
	* ccess [2] = '1'' : Instruction access
	*  PSU_IOU_SECURE_SLCR_IOU_AXI_WPRTCN_NAND_AXI_AWPROT          2

	* AXI write protection type selection
	* (OFFSET, MASK, VALUE)      (0XFF240000, 0x01C00000U ,0x00800000U)
	*/
	PSU_Mask_Write(IOU_SECURE_SLCR_IOU_AXI_WPRTCN_OFFSET,
								 0x01C00000U, 0x00800000U);
	/*##################################################################### */

	/*
	* DMA TZ
	*/
	/*
	* Register : slcr_adma @ 0XFF4B0024

	* TrustZone Classification for ADMA
	*  PSU_LPD_SLCR_SECURE_SLCR_ADMA_TZ                            0xFF

	* RPU TrustZone settings
	* (OFFSET, MASK, VALUE)      (0XFF4B0024, 0x000000FFU ,0x000000FFU)
	*/
	PSU_Mask_Write(LPD_SLCR_SECURE_SLCR_ADMA_OFFSET,
								 0x000000FFU, 0x000000FFU);
	/*##################################################################### */

	/*
	* Register : slcr_gdma @ 0XFD690050

	* TrustZone Classification for GDMA
	*  PSU_FPD_SLCR_SECURE_SLCR_GDMA_TZ                            0xFF

	* GDMA Trustzone Settings
	* (OFFSET, MASK, VALUE)      (0XFD690050, 0x000000FFU ,0x000000FFU)
	*/
	PSU_Mask_Write(FPD_SLCR_SECURE_SLCR_GDMA_OFFSET,
								 0x000000FFU, 0x000000FFU);
	/*##################################################################### */


	return 1;
}


unsigned long psu_ps_pl_isolation_removal_data(void)
{
	/*
	* PS-PL POWER UP REQUEST
	*/
	/*
	* Register : REQ_PWRUP_INT_EN @ 0XFFD80118

	* Power-up Request Interrupt Enable for PL
	*  PSU_PMU_GLOBAL_REQ_PWRUP_INT_EN_PL                          1

	* Power-up Request Interrupt Enable Register. Writing a 1 to this location
	*  will unmask the interrupt.
	* (OFFSET, MASK, VALUE)      (0XFFD80118, 0x00800000U ,0x00800000U)
	*/
	PSU_Mask_Write(PMU_GLOBAL_REQ_PWRUP_INT_EN_OFFSET,
								 0x00800000U, 0x00800000U);
	/*##################################################################### */

	/*
	* Register : REQ_PWRUP_TRIG @ 0XFFD80120

	* Power-up Request Trigger for PL
	*  PSU_PMU_GLOBAL_REQ_PWRUP_TRIG_PL                            1

	* Power-up Request Trigger Register. A write of one to this location will
	* generate a power-up request to the PMU.
	* (OFFSET, MASK, VALUE)      (0XFFD80120, 0x00800000U ,0x00800000U)
	*/
	PSU_Mask_Write(PMU_GLOBAL_REQ_PWRUP_TRIG_OFFSET,
								 0x00800000U, 0x00800000U);
	/*##################################################################### */

	/*
	* POLL ON PL POWER STATUS
	*/
	/*
	* Register : REQ_PWRUP_STATUS @ 0XFFD80110

	* Power-up Request Status for PL
	*  PSU_PMU_GLOBAL_REQ_PWRUP_STATUS_PL                          1
	* (OFFSET, MASK, VALUE)      (0XFFD80110, 0x00800000U ,0x00000000U)
	*/
	mask_pollOnValue(PMU_GLOBAL_REQ_PWRUP_STATUS_OFFSET,
									 0x00800000U, 0x00000000U);

	/*##################################################################### */


	return 1;
}
unsigned long psu_ps_pl_reset_config_data(void)
{
	/*
	* PS PL RESET SEQUENCE
	*/
	/*
	* FABRIC RESET USING EMIO
	*/
	/*
	* Register : MASK_DATA_5_MSW @ 0XFF0A002C

	* Operation is the same as MASK_DATA_0_LSW[MASK_0_LSW]
	*  PSU_GPIO_MASK_DATA_5_MSW_MASK_5_MSW                         0x8000

	* Maskable Output Data (GPIO Bank5, EMIO, Upper 16bits)
	* (OFFSET, MASK, VALUE)      (0XFF0A002C, 0xFFFF0000U ,0x80000000U)
	*/
	PSU_Mask_Write(GPIO_MASK_DATA_5_MSW_OFFSET,
								 0xFFFF0000U, 0x80000000U);
	/*##################################################################### */

	/*
	* Register : DIRM_5 @ 0XFF0A0344

	* Operation is the same as DIRM_0[DIRECTION_0]
	*  PSU_GPIO_DIRM_5_DIRECTION_5                                 0x80000000

	* Direction mode (GPIO Bank5, EMIO)
	* (OFFSET, MASK, VALUE)      (0XFF0A0344, 0xFFFFFFFFU ,0x80000000U)
	*/
	PSU_Mask_Write(GPIO_DIRM_5_OFFSET, 0xFFFFFFFFU, 0x80000000U);
	/*##################################################################### */

	/*
	* Register : OEN_5 @ 0XFF0A0348

	* Operation is the same as OEN_0[OP_ENABLE_0]
	*  PSU_GPIO_OEN_5_OP_ENABLE_5                                  0x80000000

	* Output enable (GPIO Bank5, EMIO)
	* (OFFSET, MASK, VALUE)      (0XFF0A0348, 0xFFFFFFFFU ,0x80000000U)
	*/
	PSU_Mask_Write(GPIO_OEN_5_OFFSET, 0xFFFFFFFFU, 0x80000000U);
	/*##################################################################### */

	/*
	* Register : DATA_5 @ 0XFF0A0054

	* Output Data
	*  PSU_GPIO_DATA_5_DATA_5                                      0x80000000

	* Output Data (GPIO Bank5, EMIO)
	* (OFFSET, MASK, VALUE)      (0XFF0A0054, 0xFFFFFFFFU ,0x80000000U)
	*/
	PSU_Mask_Write(GPIO_DATA_5_OFFSET, 0xFFFFFFFFU, 0x80000000U);
	/*##################################################################### */

	mask_delay(1);

	/*##################################################################### */

	/*
	* FABRIC RESET USING DATA_5 TOGGLE
	*/
	/*
	* Register : DATA_5 @ 0XFF0A0054

	* Output Data
	*  PSU_GPIO_DATA_5_DATA_5                                      0X00000000

	* Output Data (GPIO Bank5, EMIO)
	* (OFFSET, MASK, VALUE)      (0XFF0A0054, 0xFFFFFFFFU ,0x00000000U)
	*/
	PSU_Mask_Write(GPIO_DATA_5_OFFSET, 0xFFFFFFFFU, 0x00000000U);
	/*##################################################################### */

	mask_delay(1);

	/*##################################################################### */

	/*
	* FABRIC RESET USING DATA_5 TOGGLE
	*/
	/*
	* Register : DATA_5 @ 0XFF0A0054

	* Output Data
	*  PSU_GPIO_DATA_5_DATA_5                                      0x80000000

	* Output Data (GPIO Bank5, EMIO)
	* (OFFSET, MASK, VALUE)      (0XFF0A0054, 0xFFFFFFFFU ,0x80000000U)
	*/
	PSU_Mask_Write(GPIO_DATA_5_OFFSET, 0xFFFFFFFFU, 0x80000000U);
	/*##################################################################### */


	return 1;
}
#endif