description = "IOP System-level Control - Secure"
[[register]]
  name = "IOU_AXI_WPRTCN"
  type = "mixed"
  width = 32
  description = "AXI write protection type selection"
  default = "0x00000000"
  offset = "0x00000000"
  [[register.field]]
    name = "RESERVED"
    bits = "31:28"
    type = "raz"
    shortdesc = '''Reserved.'''
    longdesc = '''Writes are ignored, read data is zero.'''
  [[register.field]]
    name = "QSPI_AXI_AWPROT"
    bits = "27:25"
    type = "rw"
  [[register.field]]
    name = "NAND_AXI_AWPROT"
    bits = "24:22"
    type = "rw"
  [[register.field]]
    name = "SD1_AXI_AWPROT"
    bits = "21:19"
    type = "rw"
  [[register.field]]
    name = "SD0_AXI_AWPROT"
    bits = "18:16"
    type = "rw"
  [[register.field]]
    name = "RESERVED"
    bits = "15:12"
    type = "raz"
    shortdesc = '''Reserved.'''
    longdesc = '''Writes are ignored, read data is zero.'''
  [[register.field]]
    name = "GEM3_AXI_AWPROT"
    bits = "11:9"
    type = "rw"
  [[register.field]]
    name = "GEM2_AXI_AWPROT"
    bits = "8:6"
    type = "rw"
  [[register.field]]
    name = "GEM1_AXI_AWPROT"
    bits = "5:3"
    type = "rw"
  [[register.field]]
    name = "GEM0_AXI_AWPROT"
    bits = "2:0"
    type = "rw"
[[register]]
  name = "IOU_AXI_RPRTCN"
  type = "mixed"
  width = 32
  description = "AXI read protection type selection"
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "RESERVED"
    bits = "31:25"
    type = "raz"
    shortdesc = '''Reserved.'''
    longdesc = '''Writes are ignored, read data is zero.'''
  [[register.field]]
    name = "NAND_AXI_ARPROT"
    bits = "24:22"
    type = "rw"
  [[register.field]]
    name = "SD1_AXI_ARPROT"
    bits = "21:19"
    type = "rw"
  [[register.field]]
    name = "SD0_AXI_ARPROT"
    bits = "18:16"
    type = "rw"
  [[register.field]]
    name = "RESERVED"
    bits = "15:12"
    type = "raz"
    shortdesc = '''Reserved.'''
    longdesc = '''Writes are ignored, read data is zero.'''
  [[register.field]]
    name = "GEM3_AXI_ARPROT"
    bits = "11:9"
    type = "rw"
  [[register.field]]
    name = "GEM2_AXI_ARPROT"
    bits = "8:6"
    type = "rw"
  [[register.field]]
    name = "GEM1_AXI_ARPROT"
    bits = "5:3"
    type = "rw"
  [[register.field]]
    name = "GEM0_AXI_ARPROT"
    bits = "2:0"
    type = "rw"
[[register]]
  name = "CTRL"
  type = "rw"
  width = 1
  description = "General control register for the IOU SLCR"
  default = "0x00000000"
  offset = "0x00000040"
  [[register.field]]
    name = "SLVERR_ENABLE"
    bits = "0"
    type = "rw"
    shortdesc = '''By default, invalid address requests are ignored.'''
    longdesc = '''However, a maskable interrupt exsists. By enabling this slverr_enable invalid address requests cause a slverr to occur. Enable/Disable SLVERR during address decode failure. 0: SLVERR is disabled. For request address: Writes are ignored. Read returns 0. 1: SLVERR is enabled. For requestes address, SLVERR is asserted. Writes are ignored. Read returns 0.'''
[[register]]
  name = "ISR"
  type = "wtc"
  width = 1
  description = "Interrupt Status Register"
  default = "0x00000000"
  offset = "0x00000044"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wtc"
    shortdesc = '''Status for an address decode error.'''
    longdesc = '''0: No Event 1: Event Occurred'''
[[register]]
  name = "IMR"
  type = "ro"
  width = 1
  description = "Interrupt Mask Register"
  default = "0x00000001"
  offset = "0x00000048"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "ro"
    shortdesc = '''Mask for an address decode error.'''
    longdesc = '''0: Interrupt Enabled 1: Interrupt Disabled'''
[[register]]
  name = "IER"
  type = "wo"
  width = 1
  description = "Interrupt Enable Register"
  default = "0x00000000"
  offset = "0x0000004C"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
    shortdesc = '''Enable for an address decode error.'''
    longdesc = '''0: Ignored 1: iou_slcr_imr -> 0'''
[[register]]
  name = "IDR"
  type = "wo"
  width = 1
  description = "Interrupt Disable Register"
  default = "0x00000000"
  offset = "0x00000050"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
    shortdesc = '''Mask for an address decode error.'''
    longdesc = '''0: Ignored 1: iou_slcr_imr -> 1'''
[[register]]
  name = "ITR"
  type = "wo"
  width = 1
  description = "Interrupt Trigger Register"
  default = "0x00000000"
  offset = "0x00000054"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
    shortdesc = '''Trigger an address decode error interrupt.'''
    longdesc = '''0: Ignored 1: iou_slcr_isr -> 1'''
