description = "VCU Encoder"
[[bank]]
  name = "VCU_PL_ENCODE"
  address = "0xa0000000"
[[register]]
  name = "MCU_RESET"
  type = "mixed"
  width = 32
  description = "MCU Subsystem Reset"
  default = "0x00000000"
  offset = "0x00009000"
  [[register.field]]
    name = "RESERVED"
    bits = "31:2"
    type = "raz"
  [[register.field]]
    name = "MCUREGSOFTRESET"
    bits = "1"
    type = "wo"
    shortdesc = '''MCU registers soft reset: writing 1 into this bit resets the MCU/ITC top-level registers.'''
    longdesc = '''Read accesses return 0.'''
  [[register.field]]
    name = "MCUSOFTRESET"
    bits = "0"
    type = "wo"
    shortdesc = '''MCU soft reset: writing 1 into this bit resets the MCU subsystem (except the top-level registers).'''
    longdesc = '''Read accesses return 0.'''
[[register]]
  name = "MCU_RESET_MODE"
  type = "mixed"
  width = 32
  description = "MCU Reset Mode"
  default = "0x00000001"
  offset = "0x00009004"
  [[register.field]]
    name = "RESERVED"
    bits = "31:2"
    type = "raz"
  [[register.field]]
    name = "MCURESETMODE"
    bits = "1:0"
    type = "rw"
[[register]]
  name = "MCU_STA"
  type = "mixed"
  width = 32
  description = "MCU Status"
  default = "0x00000000"
  offset = "0x00009008"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
  [[register.field]]
    name = "MCUSLEEPSTATUS"
    bits = "0"
    type = "ro"
[[register]]
  name = "MCU_WAKEUP"
  type = "mixed"
  width = 32
  description = "MCU Wake-up"
  default = "0x00000000"
  offset = "0x0000900C"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
  [[register.field]]
    name = "MCUWAKEUP"
    bits = "0"
    type = "rw"
    shortdesc = '''MCU wake-up: writing 1 into this bit wakes the MCU from sleep mode (it is ignored if the MCU is not in sleep mode).'''
    longdesc = '''It should be set to 0 after the MCU sleep status bit gets back to 0.'''
[[register]]
  name = "MCU_ADDR_OFFSET_IC0"
  type = "rw"
  width = 32
  description = "MCU Instruction Cache Address Offset 0"
  default = "0x00000000"
  offset = "0x00009010"
  [[register.field]]
    name = "MCUICADDROFFSET0"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "MCU_ADDR_OFFSET_IC1"
  type = "rw"
  width = 32
  description = "MCU Instruction Cache Address Offset 1"
  default = "0x00000000"
  offset = "0x00009014"
  [[register.field]]
    name = "MCUICADDROFFSET1"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "MCU_ADDR_OFFSET_DC0"
  type = "rw"
  width = 32
  description = "MCU Data Cache Address Offset 0"
  default = "0x00000000"
  offset = "0x00009018"
  [[register.field]]
    name = "MCUDCADDROFFSET0"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "MCU_ADDR_OFFSET_DC1"
  type = "rw"
  width = 32
  description = "MCU Data Cache Address Offset 1"
  default = "0x00000000"
  offset = "0x0000901C"
  [[register.field]]
    name = "MCUDCADDROFFSET1"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "ITC_MCU_IRQ"
  type = "mixed"
  width = 32
  description = "MCU Interrupt Trigger"
  default = "0x00000000"
  offset = "0x00009100"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
  [[register.field]]
    name = "MCUINTERRUPTTRIGGER"
    bits = "0"
    type = "wo"
    shortdesc = '''MCU interrupt trigger: writing 1 into this bit triggers an interrupt towards the MCU.'''
    longdesc = '''Read accesses return 0.'''
[[register]]
  name = "ITC_CPU_IRQ_MSK"
  type = "rw"
  width = 32
  description = "CPU Interrupt Mask"
  default = "0x00000000"
  offset = "0x00009104"
  [[register.field]]
    name = "RESERVED"
    bits = "31:8"
    type = "rw"
  [[register.field]]
    name = "EXTIRQ1INTERRUPTMASK"
    bits = "7"
    type = "rw"
  [[register.field]]
    name = "EXTIRQ0INTERRUPTMASK"
    bits = "6"
    type = "rw"
  [[register.field]]
    name = "RRESP1INTERRUPTMASK"
    bits = "5"
    type = "rw"
  [[register.field]]
    name = "BRESP1INTERRUPTMASK"
    bits = "4"
    type = "rw"
  [[register.field]]
    name = "RRESP0INTERRUPTMASK"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "BRESP0INTERRUPTMASK"
    bits = "2"
    type = "rw"
  [[register.field]]
    name = "RESERVED"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "MCUTOCPUINTERRUPTMASK"
    bits = "0"
    type = "rw"
[[register]]
  name = "ITC_CPU_IRQ_CLR"
  type = "mixed"
  width = 32
  description = "CPU Interrupt Clear"
  default = "0x00000000"
  offset = "0x00009108"
  [[register.field]]
    name = "RESERVED"
    bits = "31:8"
    type = "raz"
  [[register.field]]
    name = "EXTIRQ1INTERRUPTCLEAR"
    bits = "7"
    type = "wo"
    shortdesc = '''EXTIRQ1 interrupt clear: writing 1 into this bit acknowledges and clears the EXTIRQ1 interrupt source (generated by the AXI master port 1 EXTIRQ input).'''
    longdesc = '''Read accesses return 0.'''
  [[register.field]]
    name = "EXTIRQ0INTERRUPTCLEAR"
    bits = "6"
    type = "wo"
    shortdesc = '''EXTIRQ0 interrupt clear: writing 1 into this bit acknowledges and clears the EXTIRQ0 interrupt source (generated by the AXI master port 0 EXTIRQ input).'''
    longdesc = '''Read accesses return 0.'''
  [[register.field]]
    name = "RRESP1INTERRUPTCLEAR"
    bits = "5"
    type = "wo"
    shortdesc = '''RRESP1 interrupt clear: writing 1 into this bit acknowledges and clears the RRESP1 interrupt source (generated by the AXI master port 1 RRESP input).'''
    longdesc = '''Read accesses return 0.'''
  [[register.field]]
    name = "BRESP1INTERRUPTCLEAR"
    bits = "4"
    type = "wo"
    shortdesc = '''BRESP1 interrupt clear: writing 1 into this bit acknowledges and clears the BRESP1 interrupt source (generated by the AXI master port 1 BRESP input).'''
    longdesc = '''Read accesses return 0.'''
  [[register.field]]
    name = "RRESP0INTERRUPTCLEAR"
    bits = "3"
    type = "wo"
    shortdesc = '''RRESP0 interrupt clear: writing 1 into this bit acknowledges and clears the RRESP0 interrupt source (generated by the AXI master port 0 RRESP input).'''
    longdesc = '''Read accesses return 0.'''
  [[register.field]]
    name = "BRESP0INTERRUPTCLEAR"
    bits = "2"
    type = "wo"
    shortdesc = '''BRESP0 interrupt clear: writing 1 into this bit acknowledges and clears the BRESP0 interrupt source (generated by the AXI master port 0 BRESP input).'''
    longdesc = '''Read accesses return 0.'''
  [[register.field]]
    name = "RESERVED"
    bits = "1"
    type = "raz"
  [[register.field]]
    name = "MCUTOCPUINTERRUPTCLEAR"
    bits = "0"
    type = "wo"
    shortdesc = '''MCU-to-CPU interrupt clear: writing 1 into this bit acknowledges and clears the MCU-to-CPU interrupt source (generated by the MCU using the INTERRUPT_MCU2CPU global hardware register).'''
    longdesc = '''Read accesses return 0.'''
[[register]]
  name = "ITC_CPU_IRQ_STA"
  type = "mixed"
  width = 32
  description = "CPU Interrupt Status"
  default = "0x00000000"
  offset = "0x0000910C"
  [[register.field]]
    name = "RESERVED"
    bits = "31:8"
    type = "raz"
  [[register.field]]
    name = "EXTIRQ1INTERRUPTSTATUS"
    bits = "7"
    type = "ro"
  [[register.field]]
    name = "EXTIRQ0INTERRUPTSTATUS"
    bits = "6"
    type = "ro"
  [[register.field]]
    name = "RRESP1INTERRUPTSTATUS"
    bits = "5"
    type = "ro"
  [[register.field]]
    name = "BRESP1INTERRUPTSTATUS"
    bits = "4"
    type = "ro"
  [[register.field]]
    name = "RRESP0INTERRUPTSTATUS"
    bits = "3"
    type = "ro"
  [[register.field]]
    name = "BRESP0INTERRUPTSTATUS"
    bits = "2"
    type = "ro"
  [[register.field]]
    name = "RESERVED"
    bits = "1"
    type = "raz"
  [[register.field]]
    name = "MCUTOCPUINTERRUPTSTATUS"
    bits = "0"
    type = "ro"
[[register]]
  name = "AXI_BW"
  type = "rw"
  width = 32
  description = "AXI Bandwidth Measurement Window"
  default = "0x00000000"
  offset = "0x00009204"
  [[register.field]]
    name = "AXIBANDWIDTHWINDOW"
    bits = "31:0"
    type = "rw"
    shortdesc = '''Time window of the bandwidth counters for the 128-bit AXI master ports.'''
    longdesc = '''It sets the number of aclk clock cycles during which average bandwidth figures are measured. A zero value disables the counters.'''
[[register]]
  name = "AXI_ADDR_OFFSET_IP"
  type = "rw"
  width = 32
  description = "Video Data Address Offset"
  default = "0x00000000"
  offset = "0x00009208"
  [[register.field]]
    name = "VIDEODATAADDROFFSET"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "AXI_RBW0"
  type = "ro"
  width = 32
  description = "AXI Read Bandwidth Status 0"
  default = "0x00000000"
  offset = "0x00009210"
  [[register.field]]
    name = "AXIREADBWSTATUS0"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "AXI_RBW1"
  type = "ro"
  width = 32
  description = "AXI Read Bandwidth Status 1"
  default = "0x00000000"
  offset = "0x00009214"
  [[register.field]]
    name = "AXIREADBWSTATUS1"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "AXI_WBW0"
  type = "ro"
  width = 32
  description = "AXI Write Bandwidth Status 0"
  default = "0x00000000"
  offset = "0x00009218"
  [[register.field]]
    name = "AXIWRITEBWSTATUS0"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "AXI_WBW1"
  type = "ro"
  width = 32
  description = "AXI Write Bandwidth Status 1"
  default = "0x00000000"
  offset = "0x0000921C"
  [[register.field]]
    name = "AXIWRITEBWSTATUS1"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "AXI_RBL0"
  type = "rw"
  width = 32
  description = "AXI Read Bandwidth Limiter 0"
  default = "0x00000000"
  offset = "0x00009220"
  [[register.field]]
    name = "AXIREADBWLIMTHR0"
    bits = "31:16"
    type = "rw"
    shortdesc = '''Port 0 Read Bandwidth Limiter Threshold: threshold, in units of 128-bit words, for the number of read accesses that can be requested on the AXI master port 0 during the read bandwidth limiter time window.'''
    longdesc = '''As soon as the threshold is exceeded at the end of an AXI burst, read requests are stalled until the end of the time window.'''
  [[register.field]]
    name = "AXIREADBWLIMWIN0"
    bits = "15:0"
    type = "rw"
    shortdesc = '''Port 0 Read Bandwidth Limiter Window: this field configures the time window, in units of aclk clock cycles, of the read bandwidth limiter for the 128-bit AXI master port 0.'''
    longdesc = '''A zero value disables the bandwidth limiter.'''
[[register]]
  name = "AXI_RBL1"
  type = "rw"
  width = 32
  description = "AXI Read Bandwidth Limiter 1"
  default = "0x00000000"
  offset = "0x00009224"
  [[register.field]]
    name = "AXIREADBWLIMTHR1"
    bits = "31:16"
    type = "rw"
    shortdesc = '''Port 1 Read Bandwidth Limiter Threshold: threshold, in units of 128-bit words, for the number of read accesses that can be requested on the AXI master port 1 during the read bandwidth limiter time window.'''
    longdesc = '''As soon as the threshold is exceeded at the end of an AXI burst, read requests are stalled until the end of the time window.'''
  [[register.field]]
    name = "AXIREADBWLIMWIN1"
    bits = "15:0"
    type = "rw"
    shortdesc = '''Port 1 Read Bandwidth Limiter Window: this field configures the time window, in units of aclk clock cycles, of the read bandwidth limiter for the 128-bit AXI master port 1.'''
    longdesc = '''A zero value disables the bandwidth limiter.'''
