description = "CCI APM Control and Configuration"
[[bank]]
  name = "APM_CCI_INTC"
  address = "0xfd490000"
[[bank]]
  name = "APM_INTC_OCM"
  address = "0xffa00000"
[[bank]]
  name = "APM_LPD_FPD"
  address = "0xffa10000"
[[register]]
  name = "GCCR_H"
  type = "ro"
  width = 32
  description = "Global Clock Counter"
  default = "0x00000000"
  offset = "0x00000000"
  [[register.field]]
    name = "GLBCLKCNT_HIGHER"
    bits = "31:0"
    type = "ro"
    shortdesc = '''Higher 32-bit data of the Global Clock Counter Register.'''
    longdesc = '''If C_GLOBAL_COUNT_WIDTH=32, only Lower 32 bits of the register are valid'''
[[register]]
  name = "GCCR_L"
  type = "ro"
  width = 32
  description = "Global Clock Counter"
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "GLBCLKCNT_LOWER"
    bits = "31:0"
    type = "ro"
    shortdesc = '''Lower 32-bit data of the Global Clock Counter Register.'''
    longdesc = '''If C_GLOBAL_COUNT_WIDTH=32, only Lower 32 Bits of the register are valid'''
[[register]]
  name = "SIR"
  type = "rw"
  width = 32
  description = "Sample Interval Time Configuration"
  default = "0x00000000"
  offset = "0x00000024"
  [[register.field]]
    name = "SMPL_INTRVL_SIR"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "SICR"
  type = "mixed"
  width = 32
  description = "Sample Interval Control"
  default = "0x00000100"
  offset = "0x00000028"
  [[register.field]]
    name = "RESERVED"
    bits = "31:9"
    type = "raz"
  [[register.field]]
    name = "MET_CNT_RST"
    bits = "8"
    type = "rw"
    shortdesc = '''1: Resets metric counters when sample interval timer expires or when the sample register is read.'''
    longdesc = '''0: Metric Counters are not reset when sample interval counter lapses or when the sample register is read.'''
  [[register.field]]
    name = "RESERVED"
    bits = "7:2"
    type = "raz"
  [[register.field]]
    name = "LOAD"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "ENABLE"
    bits = "0"
    type = "rw"
    shortdesc = '''1: Enables the down counter.'''
    longdesc = '''Before enabling, the counter should be loaded with the sample Interval Register value.'''
[[register]]
  name = "SISR"
  type = "rw"
  width = 32
  description = "Sample Interval Sample. Reading this initiates sampling of Metric Counters data to the Sample Metric Counters."
  default = "0x00000000"
  offset = "0x0000002C"
  [[register.field]]
    name = "SMPL_READ"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "GIER"
  type = "mixed"
  width = 32
  description = "Global Interrupt Enable Register"
  default = "0x00000000"
  offset = "0x00000030"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
  [[register.field]]
    name = "GIE"
    bits = "0"
    type = "rw"
    shortdesc = '''Master enable for the device interrupt output to the system interrupt controller: 1: Enabled.'''
    longdesc = '''0: Disabled'''
[[register]]
  name = "IER"
  type = "mixed"
  width = 32
  description = "Interrupt Enable"
  default = "0x00000000"
  offset = "0x00000034"
  [[register.field]]
    name = "MET_CT7_OVFLINT_EN"
    bits = "10"
    type = "rw"
  [[register.field]]
    name = "MET_CT6_OVFLINT_EN"
    bits = "9"
    type = "rw"
  [[register.field]]
    name = "MET_CT5_OVFLINT_EN"
    bits = "8"
    type = "rw"
  [[register.field]]
    name = "MET_CT4_OVFLINT_EN"
    bits = "7"
    type = "rw"
  [[register.field]]
    name = "MET_CT3_OVFLINT_EN"
    bits = "6"
    type = "rw"
  [[register.field]]
    name = "MET_CT2_OVFLINT_EN"
    bits = "5"
    type = "rw"
  [[register.field]]
    name = "MET_CT1_OVFLINT_EN"
    bits = "4"
    type = "rw"
  [[register.field]]
    name = "MET_CT0_OVFLINT_EN"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "SMPL_INTRVL_OVFLINT_EN"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "GLBCLKCNT_OVFLINT_EN"
    bits = "0"
    type = "rw"
[[register]]
  name = "ISR"
  type = "mixed"
  width = 32
  description = "Interrupt Status"
  default = "0x00000000"
  offset = "0x00000038"
  [[register.field]]
    name = "MET_CT7_OVFLINT"
    bits = "10"
    type = "rw"
  [[register.field]]
    name = "MET_CT6_OVFLINT"
    bits = "9"
    type = "rw"
  [[register.field]]
    name = "MET_CT5_OVFLINT"
    bits = "8"
    type = "rw"
  [[register.field]]
    name = "MET_CT4_OVFLINT"
    bits = "7"
    type = "rw"
  [[register.field]]
    name = "MET_CT3_OVFLINT"
    bits = "6"
    type = "rw"
  [[register.field]]
    name = "MET_CT2_OVFLINT"
    bits = "5"
    type = "rw"
  [[register.field]]
    name = "MET_CT1_OVFLINT"
    bits = "4"
    type = "rw"
  [[register.field]]
    name = "MET_CT0_OVFLINT"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "SMPL_INTRVL_OVFLINT"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "GLBCLKCNT_OVFLINT"
    bits = "0"
    type = "rw"
[[register]]
  name = "MSR_0"
  type = "rw"
  width = 32
  description = "Metric Selector, Counters 0, 1, 2, and 3"
  default = "0x00000000"
  offset = "0x00000044"
  [[register.field]]
    name = "MET_CT3_SLOT"
    bits = "31:29"
    type = "rw"
  [[register.field]]
    name = "MET_CT3_SEL"
    bits = "28:24"
    type = "rw"
  [[register.field]]
    name = "MET_CT2_SLOT"
    bits = "23:21"
    type = "rw"
  [[register.field]]
    name = "MET_CT2_SEL"
    bits = "20:16"
    type = "rw"
  [[register.field]]
    name = "MET_CT1_SLOT"
    bits = "15:13"
    type = "rw"
  [[register.field]]
    name = "MET_CT1_SEL"
    bits = "12:8"
    type = "rw"
  [[register.field]]
    name = "MET_CT0_SLOT"
    bits = "7:5"
    type = "rw"
  [[register.field]]
    name = "MET_CT0_SEL"
    bits = "4:0"
    type = "rw"
[[register]]
  name = "MSR_1"
  type = "rw"
  width = 32
  description = "Metric Selector, Counters 4, 5, 6, and 7"
  default = "0x00000000"
  offset = "0x00000048"
  [[register.field]]
    name = "MET_CT7_SLOT"
    bits = "31:29"
    type = "rw"
  [[register.field]]
    name = "MET_CT7_SEL"
    bits = "28:24"
    type = "rw"
  [[register.field]]
    name = "MET_CT6_SLOT"
    bits = "23:21"
    type = "rw"
  [[register.field]]
    name = "MET_CT6_SEL"
    bits = "20:16"
    type = "rw"
  [[register.field]]
    name = "MET_CT5_SLOT"
    bits = "15:13"
    type = "rw"
  [[register.field]]
    name = "MET_CT5_SEL"
    bits = "12:8"
    type = "rw"
  [[register.field]]
    name = "MET_CT4_SLOT"
    bits = "7:5"
    type = "rw"
  [[register.field]]
    name = "MET_CT4_SEL"
    bits = "4:0"
    type = "rw"
[[register]]
  name = "IR_0"
  type = "ro"
  width = 32
  description = "Incrementer"
  default = "0x00000000"
  offset = "0x00000104"
  [[register.field]]
    name = "MET_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "RR_0"
  type = "rw"
  width = 32
  description = "Range"
  default = "0x00000000"
  offset = "0x00000108"
  [[register.field]]
    name = "RANGE_HIGH"
    bits = "31:16"
    type = "rw"
  [[register.field]]
    name = "RANGE_LOW"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "MCLER_0"
  type = "rw"
  width = 32
  description = "Metric Count Log Enable"
  default = "0x00000000"
  offset = "0x0000010C"
  [[register.field]]
    name = "MET_CUTOFF"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "IR_1"
  type = "ro"
  width = 32
  description = "Incrementer"
  default = "0x00000000"
  offset = "0x00000114"
  [[register.field]]
    name = "MET_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "RR_1"
  type = "rw"
  width = 32
  description = "Range"
  default = "0x00000000"
  offset = "0x00000118"
  [[register.field]]
    name = "RANGE_HIGH"
    bits = "31:16"
    type = "rw"
  [[register.field]]
    name = "RANGE_LOW"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "MCLER_1"
  type = "rw"
  width = 32
  description = "Metric Count Log Enable"
  default = "0x00000000"
  offset = "0x0000011C"
  [[register.field]]
    name = "MET_CUTOFF"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "IR_2"
  type = "ro"
  width = 32
  description = "Incrementer"
  default = "0x00000000"
  offset = "0x00000124"
  [[register.field]]
    name = "MET_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "RR_2"
  type = "rw"
  width = 32
  description = "Range"
  default = "0x00000000"
  offset = "0x00000128"
  [[register.field]]
    name = "RANGE_HIGH"
    bits = "31:16"
    type = "rw"
  [[register.field]]
    name = "RANGE_LOW"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "MCLER_2"
  type = "rw"
  width = 32
  description = "Metric Count Log Enable"
  default = "0x00000000"
  offset = "0x0000012C"
  [[register.field]]
    name = "MET_CUTOFF"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "IR_3"
  type = "ro"
  width = 32
  description = "Incrementer"
  default = "0x00000000"
  offset = "0x00000134"
  [[register.field]]
    name = "MET_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "RR_3"
  type = "rw"
  width = 32
  description = "Range"
  default = "0x00000000"
  offset = "0x00000138"
  [[register.field]]
    name = "RANGE_HIGH"
    bits = "31:16"
    type = "rw"
  [[register.field]]
    name = "RANGE_LOW"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "MCLER_3"
  type = "rw"
  width = 32
  description = "Metric Count Log Enable"
  default = "0x00000000"
  offset = "0x0000013C"
  [[register.field]]
    name = "MET_CUTOFF"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "IR_4"
  type = "ro"
  width = 32
  description = "Incrementer"
  default = "0x00000000"
  offset = "0x00000144"
  [[register.field]]
    name = "MET_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "RR_4"
  type = "rw"
  width = 32
  description = "Range"
  default = "0x00000000"
  offset = "0x00000148"
  [[register.field]]
    name = "RANGE_HIGH"
    bits = "31:16"
    type = "rw"
  [[register.field]]
    name = "RANGE_LOW"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "MCLER_4"
  type = "rw"
  width = 32
  description = "Metric Count Log Enable"
  default = "0x00000000"
  offset = "0x0000014C"
  [[register.field]]
    name = "MET_CUTOFF"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "IR_5"
  type = "ro"
  width = 32
  description = "Incrementer"
  default = "0x00000000"
  offset = "0x00000154"
  [[register.field]]
    name = "MET_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "RR_5"
  type = "rw"
  width = 32
  description = "Range"
  default = "0x00000000"
  offset = "0x00000158"
  [[register.field]]
    name = "RANGE_HIGH"
    bits = "31:16"
    type = "rw"
  [[register.field]]
    name = "RANGE_LOW"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "MCLER_5"
  type = "rw"
  width = 32
  description = "Metric Count Log Enable"
  default = "0x00000000"
  offset = "0x0000015C"
  [[register.field]]
    name = "MET_CUTOFF"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "IR_6"
  type = "ro"
  width = 32
  description = "Incrementer"
  default = "0x00000000"
  offset = "0x00000164"
  [[register.field]]
    name = "MET_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "RR_6"
  type = "rw"
  width = 32
  description = "Range"
  default = "0x00000000"
  offset = "0x00000168"
  [[register.field]]
    name = "RANGE_HIGH"
    bits = "31:16"
    type = "rw"
  [[register.field]]
    name = "RANGE_LOW"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "MCLER_6"
  type = "rw"
  width = 32
  description = "Metric Count Log Enable"
  default = "0x00000000"
  offset = "0x0000016C"
  [[register.field]]
    name = "MET_CUTOFF"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "IR_7"
  type = "ro"
  width = 32
  description = "Incrementer"
  default = "0x00000000"
  offset = "0x00000174"
  [[register.field]]
    name = "MET_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "RR_7"
  type = "rw"
  width = 32
  description = "Range"
  default = "0x00000000"
  offset = "0x00000178"
  [[register.field]]
    name = "RANGE_HIGH"
    bits = "31:16"
    type = "rw"
  [[register.field]]
    name = "RANGE_LOW"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "MCLER_7"
  type = "rw"
  width = 32
  description = "Metric Count Log Enable"
  default = "0x00000000"
  offset = "0x0000017C"
  [[register.field]]
    name = "MET_CUTOFF"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "SMCR_0"
  type = "ro"
  width = 32
  description = "Sampled Metric Counter"
  default = "0x00000000"
  offset = "0x00000200"
  [[register.field]]
    name = "SMPL_CNT"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SIR_0"
  type = "ro"
  width = 32
  description = "Sampled Incrementer"
  default = "0x00000000"
  offset = "0x00000204"
  [[register.field]]
    name = "SMPL_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SMCR_1"
  type = "ro"
  width = 32
  description = "Sampled Metric Counter"
  default = "0x00000000"
  offset = "0x00000210"
  [[register.field]]
    name = "SMPL_CNT"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SIR_1"
  type = "ro"
  width = 32
  description = "Sampled Incrementer"
  default = "0x00000000"
  offset = "0x00000214"
  [[register.field]]
    name = "SMPL_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SMCR_2"
  type = "ro"
  width = 32
  description = "Sampled Metric Counter"
  default = "0x00000000"
  offset = "0x00000220"
  [[register.field]]
    name = "SMPL_CNT"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SIR_2"
  type = "ro"
  width = 32
  description = "Sampled Incrementer"
  default = "0x00000000"
  offset = "0x00000224"
  [[register.field]]
    name = "SMPL_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SMCR_3"
  type = "ro"
  width = 32
  description = "Sampled Metric Counter"
  default = "0x00000000"
  offset = "0x00000230"
  [[register.field]]
    name = "SMPL_CNT"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SIR_3"
  type = "ro"
  width = 32
  description = "Sampled Incrementer"
  default = "0x00000000"
  offset = "0x00000234"
  [[register.field]]
    name = "SMPL_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SMCR_4"
  type = "ro"
  width = 32
  description = "Sampled Metric Counter"
  default = "0x00000000"
  offset = "0x00000240"
  [[register.field]]
    name = "SMPL_CNT"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SIR_4"
  type = "ro"
  width = 32
  description = "Sampled Incrementer"
  default = "0x00000000"
  offset = "0x00000244"
  [[register.field]]
    name = "SMPL_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SMCR_5"
  type = "ro"
  width = 32
  description = "Sampled Metric Counter"
  default = "0x00000000"
  offset = "0x00000250"
  [[register.field]]
    name = "SMPL_CNT"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SIR_5"
  type = "ro"
  width = 32
  description = "Sampled Incrementer"
  default = "0x00000000"
  offset = "0x00000254"
  [[register.field]]
    name = "SMPL_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SMCR_6"
  type = "ro"
  width = 32
  description = "Sampled Metric Counter"
  default = "0x00000000"
  offset = "0x00000260"
  [[register.field]]
    name = "SMPL_CNT"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SIR_6"
  type = "ro"
  width = 32
  description = "Sampled Incrementer"
  default = "0x00000000"
  offset = "0x00000264"
  [[register.field]]
    name = "SMPL_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SMCR_7"
  type = "ro"
  width = 32
  description = "Sampled Metric Counter"
  default = "0x00000000"
  offset = "0x00000270"
  [[register.field]]
    name = "SMPL_CNT"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "SIR_7"
  type = "ro"
  width = 32
  description = "Sampled Incrementer"
  default = "0x00000000"
  offset = "0x00000274"
  [[register.field]]
    name = "SMPL_INC"
    bits = "31:0"
    type = "ro"
[[register]]
  name = "CR"
  type = "mixed"
  width = 32
  description = "Control"
  default = "0x00000000"
  offset = "0x00000300"
  [[register.field]]
    name = "STR_FIFO_RST"
    bits = "25"
    type = "rw"
  [[register.field]]
    name = "GCCR_RST"
    bits = "17"
    type = "rw"
  [[register.field]]
    name = "GCCR_EN"
    bits = "16"
    type = "rw"
  [[register.field]]
    name = "LATENCY_READ_END"
    bits = "7"
    type = "rw"
    shortdesc = '''Read Latency End Point.'''
    longdesc = '''1: Enables first read as read latency end point 0: Enables last read as read latency end point'''
  [[register.field]]
    name = "LATENCY_READ_START"
    bits = "6"
    type = "rw"
    shortdesc = '''Read Latency Start Point.'''
    longdesc = '''0: Enables address issuance by the master interface as read latency start point (ARVALID)1: Enables address acceptance by slave as read latency start point (ARVALID and ARREADY)'''
  [[register.field]]
    name = "LATENCY_WRITE_END"
    bits = "5"
    type = "rw"
    shortdesc = '''Write Latency End Point.'''
    longdesc = '''1: Enables first write as write latency end point. 0: Enables Last write as write latency end point'''
  [[register.field]]
    name = "LATENCY_WRITE_START"
    bits = "4"
    type = "rw"
    shortdesc = '''Write Latency Start Point.'''
    longdesc = '''0: Enables address issuance by master interface as write latency start point (AWVALID). 1: Enables address acceptance by the slave interface as write latency start point (AWVALID and AWREADY)'''
  [[register.field]]
    name = "ID_MASKING_EN"
    bits = "3"
    type = "rw"
    shortdesc = '''Enable ID Based Filtering/Masking.'''
    longdesc = '''This bit is only valid in Advanced mode.0: Ignore ID for metric calculation 1: Enables ID filtering and masking. When enabled, all metric corresponds to the ID configured in the IDR and IDMR registers.'''
  [[register.field]]
    name = "MET_CNT_RST"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "MET_CNT_EN"
    bits = "0"
    type = "rw"
[[register]]
  name = "WIDR"
  type = "rw"
  width = 32
  description = "WID"
  default = "0x00000000"
  offset = "0x00000304"
  [[register.field]]
    name = "WID"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "WIDMR"
  type = "rw"
  width = 32
  description = "WID Mask"
  default = "0x00000000"
  offset = "0x00000308"
  [[register.field]]
    name = "WIDM"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "RIDR"
  type = "rw"
  width = 32
  description = "RID"
  default = "0x00000000"
  offset = "0x0000030C"
  [[register.field]]
    name = "RID"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "RIDMR"
  type = "rw"
  width = 32
  description = "RID Mask"
  default = "0x00000000"
  offset = "0x00000310"
  [[register.field]]
    name = "RIDM"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "FECR"
  type = "mixed"
  width = 32
  description = "Flag Enable"
  default = "0x00000000"
  offset = "0x00000400"
  [[register.field]]
    name = "SMP_CNT_LAPSE_FLG"
    bits = "21"
    type = "rw"
  [[register.field]]
    name = "GCC_OFVL_FLG"
    bits = "20"
    type = "rw"
  [[register.field]]
    name = "SFT_DATA_FLG_EN"
    bits = "16"
    type = "rw"
  [[register.field]]
    name = "LAST_READ_FLG"
    bits = "6"
    type = "rw"
  [[register.field]]
    name = "FIRST_READ_FLG"
    bits = "5"
    type = "rw"
  [[register.field]]
    name = "READ_ADDR_FLG"
    bits = "4"
    type = "rw"
  [[register.field]]
    name = "RESPONSE_FLG"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "LAST_WRITE_FLG"
    bits = "2"
    type = "rw"
  [[register.field]]
    name = "FIRST_WRITE_FLG"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "WRITE_ADDR_FLG"
    bits = "0"
    type = "rw"
