description = "Battery-backed RAM control"
[[bank]]
  name = "BBRAM"
  address = "0xffcd0000"
[[register]]
  name = "BBRAM_STATUS"
  type = "ro"
  width = 32
  description = "BBRAM Status"
  default = "0x00000000"
  offset = "0x00000000"
  [[register.field]]
    name = "AES_CRC_PASS"
    bits = "9"
    type = "ro"
    shortdesc = '''Indicates that the AES key integrity check passed.'''
    longdesc = '''This bit is only valid when AES_CRC_DONE is set.'''
  [[register.field]]
    name = "AES_CRC_DONE"
    bits = "8"
    type = "ro"
    shortdesc = '''Indicates that the AES key integrity check has finished.'''
    longdesc = '''Pass/Fail is indicated in the AES_CRC_PASS bit.'''
  [[register.field]]
    name = "RESERVED"
    bits = "7:5"
    type = "ro"
  [[register.field]]
    name = "BBRAM_ZEROIZED"
    bits = "4"
    type = "ro"
    shortdesc = '''This bit indicates when a zerization command has been successful.'''
    longdesc = '''This bit will only get set after a zerize command is issued (either BBRAM_CTRL[ZEROIZE] or PGM_MODE).'''
  [[register.field]]
    name = "RESERVED"
    bits = "3:1"
    type = "ro"
  [[register.field]]
    name = "PGM_MODE"
    bits = "0"
    type = "ro"
    shortdesc = '''This bit indicates that the BBRAM is in programming mode.'''
    longdesc = '''Entering programming mode will zeroize the current contents of the BBRAM and enable new contents to be loaded. The AES key integrity check can also be performed when the BBRAM is in programming mode.'''
[[register]]
  name = "BBRAM_CTRL"
  type = "wo"
  width = 32
  description = "BBRAM Control"
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "ZEROIZE"
    bits = "0"
    type = "wo"
    shortdesc = '''Writing to this bit will zeroize the contents of the BBRAM.'''
    longdesc = '''Zeroization status is reported in the BBRAM_STATUS. (This bit is self clearing)'''
[[register]]
  name = "PGM_MODE"
  type = "rw"
  width = 32
  description = "BBRAM Program Mode"
  default = "0x00000000"
  offset = "0x00000008"
  [[register.field]]
    name = "PGM_MODE_VALUE"
    bits = "31:0"
    type = "rw"
    shortdesc = '''Writing 0x757BDF0D to this register will put the BBRAM into programming mode.'''
    longdesc = '''WARNING, entering programming mode will erase all data in the BBRAM. New data can be loaded into the BBRAM once the PGM_MODE bit is set on the BBRAM_STATUS register.'''
[[register]]
  name = "BBRAM_AES_CRC"
  type = "wo"
  width = 32
  description = "BBRAM AES Key Integrity Check"
  default = "0x00000000"
  offset = "0x0000000C"
  [[register.field]]
    name = "AES_CRC_VALUE"
    bits = "31:0"
    type = "wo"
    shortdesc = '''Writing the AES key CRC value to this register will start the AES integrity check.'''
    longdesc = '''When the check is finished the AES_CRC_DONE bit will be set in the BBRAM_STATUS register. If the value calculated by the BBRAM controller matches the value writen to this register, then the AES_CRC_PASS bit will also be set. The CRC check can only be performed when the BBRAM is in programming mode.'''
[[register]]
  name = "BBRAM_0"
  type = "wo"
  width = 32
  description = "BBRAM Data 0"
  default = "0x00000000"
  offset = "0x00000010"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM AES key value [31:0].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_1"
  type = "wo"
  width = 32
  description = "BBRAM Data 1"
  default = "0x00000000"
  offset = "0x00000014"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM AES key value [63:32].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_2"
  type = "wo"
  width = 32
  description = "BBRAM Data 2"
  default = "0x00000000"
  offset = "0x00000018"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM AES key value [95:64].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_3"
  type = "wo"
  width = 32
  description = "BBRAM Data 3"
  default = "0x00000000"
  offset = "0x0000001C"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM AES key value [127:96].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_4"
  type = "wo"
  width = 32
  description = "BBRAM Data 4"
  default = "0x00000000"
  offset = "0x00000020"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM AES key value [159:128].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_5"
  type = "wo"
  width = 32
  description = "BBRAM Data 5"
  default = "0x00000000"
  offset = "0x00000024"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM AES key value [191:160].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_6"
  type = "wo"
  width = 32
  description = "BBRAM Data 6"
  default = "0x00000000"
  offset = "0x00000028"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM AES key value [223:192].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_7"
  type = "wo"
  width = 32
  description = "BBRAM Data 7"
  default = "0x00000000"
  offset = "0x0000002C"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM AES key value [255:224].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_8"
  type = "wo"
  width = 32
  description = "BBRAM Data 8"
  default = "0x00000000"
  offset = "0x00000030"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "wo"
    shortdesc = '''This register writes the BBRAM extra value [31:0].'''
    longdesc = '''The BBRAM must be in PGM_MODE before writing this register.'''
[[register]]
  name = "BBRAM_SLVERR"
  type = "rw"
  width = 32
  description = "BBRAM Slave Error Control"
  default = "0x00000000"
  offset = "0x00000034"
  [[register.field]]
    name = "ENABLE"
    bits = "0"
    type = "rw"
    shortdesc = '''By default, invalid address requests are ignored.'''
    longdesc = '''However, a maskable interrupt exsists. By enabling this slverr_enable invalid address requests cause a slverr to occur. Enable/Disable SLVERR during address decode failure. 0: SLVERR is disabled. For request address: Writes are ignored. Read returns 0. 1: SLVERR is enabled. For requestes address, SLVERR is asserted. Writes are ignored. Read returns 0.'''
[[register]]
  name = "BBRAM_ISR"
  type = "wtc"
  width = 32
  description = "BBRAM Interrupt Status"
  default = "0x00000000"
  offset = "0x00000038"
  [[register.field]]
    name = "APB_SLVERR"
    bits = "0"
    type = "wtc"
[[register]]
  name = "BBRAM_IMR"
  type = "ro"
  width = 32
  description = "BBRAM Interrupt Mask"
  default = "0x00000001"
  offset = "0x0000003C"
  [[register.field]]
    name = "APB_SLVERR"
    bits = "0"
    type = "ro"
[[register]]
  name = "BBRAM_IER"
  type = "wo"
  width = 32
  description = "BBRAM Interrupt Enable"
  default = "0x00000000"
  offset = "0x00000040"
  [[register.field]]
    name = "APB_SLVERR"
    bits = "0"
    type = "wo"
[[register]]
  name = "BBRAM_IDR"
  type = "wo"
  width = 32
  description = "BBRAM Interrupt Disable"
  default = "0x00000000"
  offset = "0x00000044"
  [[register.field]]
    name = "APB_SLVERR"
    bits = "0"
    type = "wo"
