description = "APU GIC Interrupt Controller; GICv2 base registers"
[[bank]]
name = "ACPU_GICC"
address = "0xf9020000"
[[register]]
name = "GICC_CTLR"
type = "rw"
width = 32
description = "CPU Interface Control Register"
default = "0x00000000"
offset = "0x00000000"
[[register.field]]
name = "ENABLE_GROUP_0"
description = "Should Group 0 interrupts signal this CPU?"
bits = "0"
type = "rw"
[[register.field]]
name = "ENABLE_GROUP_1"
description = "Should Group 1 interrupts signal this CPU?"
bits = "1"
type = "rw"
[[register.field]]
name = "GROUP_0_FIQ"
description = "Should Group 0 use FIQ?"
bits = "3"
type = "rw"
[[register.field]]
name = "CBPR"
description = "0 = use BPR for Group 0 and ABPR for Group 1, 1 = BPR for both"
bits = "4"
type = "rw"
[[register.field]]
name = "GROUP_0_FIQ_BYPASS"
description = "0 = Bypass FIQ is signalled to CPU, 1 = not signalled"
bits = "5"
type = "rw"
[[register.field]]
name = "GROUP_1_IRQ_BYPASS"
description = "0 = Bypass IRQ is signalled to CPU, 1 = not signalled"
bits = "7"
type = "rw"
[[register.field]]
name = "GROUP_1_FIQ_BYPASS"
description = "0 = Bypass FIQ is signalled to CPU, 1 = not signalled"
bits = "8"
type = "rw"
[[register.field]]
name = "GROUP_0_IRQ_BYPASS"
description = "0 = Bypass IRQ is signalled to CPU, 1 = not signalled"
bits = "6"
type = "rw"
[[register.field]]
name = "EOI_MODE_S"
description = "Secure 0 = EOIR has both priority drop and de-actavate, 1 = drop only"
bits = "9"
type = "rw"
[[register.field]]
name = "EOI_MODE_NS"
description = "Non Secure 0 = EOIR has both priority drop and de-actavate, 1 = drop only"
bits = "10"
type = "rw"

[[register]]
name = "GICC_PMR"
type = "rw"
width = 32
description = "Interrupt Priority Mask Register"
default = "0x00000000"
offset = "0x00000004"
[[register.field]]
name = "PRIORITY"
description = "if interrupt priorirt is higher than the CPU is signalled"
bits = "[7:0]"
type = "rw"

[[register]]
name = "GICC_BPR"
type = "rw"
width = 32
description = "Binary Point Register"
default = "0x00000002"
offset = "0x00000008"
[[register.field]]
name = "BINARY_POINT"
description = "How the priority field is split"
bits = "[2:0]"
type = "rw"

[[register]]
name = "GICC_IAR"
type = "ro"
width = 32
description = "Interrupt Acknowledge Register"
default = "0x000003FF"
offset = "0x0000000C"
[[register.field]]
name = "INTERRUPT_ID"
description = "ID of this interrupt"
bits = "[9:0]"
type = "ro"
[[register.field]]
name = "CPU_ID"
description = "CPU that requested this interrupt"
bits = "[12:10]"
type = "ro"

[[register]]
name = "GICC_EOIR"
type = "wo"
width = 32
description = "End of Interrupt Register"
default = "0x00000000"
offset = "0x00000010"
[[register.field]]
name = "INTERRUPT_ID"
description = "ID of this interrupt"
bits = "[9:0]"
type = "wo"
[[register.field]]
name = "CPU_ID"
description = "CPU that requested this interrupt"
bits = "[12:10]"
type = "wo"

[[register]]
name = "GICC_RPR"
type = "ro"
width = 32
description = "Running Priority Register"
default = "0x000000FF"
offset = "0x00000014"
[[register.field]]
name = "PRIORITY"
description = "Current running priority"
bits = "[7:0]"
type = "ro"

[[register]]
name = "GICC_HPPIR"
type = "ro"
width = 32
description = "Highest Priority Pending Interrupt Register"
default = "0x000003FF"
offset = "0x00000018"
[[register.field]]
name = "PENDING_ID"
description = "ID of the highest not active pending interrupt"
bits = "[9:0]"
type = "wo"
[[register.field]]
name = "CPU_ID"
description = "CPU that requested this interrupt"
bits = "[12:10]"
type = "wo"

[[register]]
name = "GICC_ABPR"
type = "rw"
width = 32
description = "Aliased Binary Point Register"
default = "0x00000003"
offset = "0x0000001C"
[[register]]
name = "GICC_AIAR"
type = "ro"
width = 32
description = "Aliased Interrupt Acknowledge Register"
default = "0x000003FF"
offset = "0x00000020"
[[register]]
name = "GICC_AEOIR"
type = "wo"
width = 32
description = "Aliased End of Interrupt Register"
default = "0x00000000"
offset = "0x00000024"
[[register]]
name = "GICC_AHPPIR"
type = "ro"
width = 32
description = "Aliased Highest Priority Pending Interrupt Register"
default = "0x000003FF"
offset = "0x00000028"
[[register]]
name = "GICC_APR0"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x000000D0"
[[register]]
name = "GICC_NSAPR0"
type = "rw"
width = 32
description = "Non-Secure Active Priority Register"
default = "0x00000000"
offset = "0x000000E0"
[[register]]
name = "GICC_IIDR"
type = "ro"
width = 32
description = "CPU Interface Identification Register"
default = "0x0202143B"
offset = "0x000000FC"
[[register.field]]
name = "IMPLEMENTER"
description = "JEP106 code, ARM = 0x43B"
bits = "[11:0]"
type = "ro"
[[register.field]]
name = "REVISION"
description = "Implementation defined revision code"
bits = "[15:12]"
type = "ro"
[[register.field]]
name = "ARCH_VERSION"
description = "0x1 = GICv1, 0x2 =GICv2"
bits = "[19:16]"
type = "ro"
[[register.field]]
name = "PRODUCT_ID"
description = "Implementation defined product ID"
bits = "[32:20]"
type = "ro"

[[register]]
name = "GICC_DIR"
type = "wo"
width = 32
description = "Deactivate Interrupt Register"
default = "0x00000000"
offset = "0x00010000"
[[register.field]]
name = "INTERRUPT_ID"
description = "Id of this interrupt"
bits = "[9:]"
type = "ro"
[[register.field]]
name = "CPU_ID"
description = "For SWI, CPU id that request interrupt else 0"
bits = "[12:10]"
type = "rw"
