description = "APU GIC Interrupt Controller; GICv2"
[[bank]]
name = "ACPU_GIC"
address = "0xf9000000"

[[register]]
name = "GICH_HCR"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00040000"
[[register]]
name = "GICH_VTR"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00040004"
[[register]]
name = "GICH_VMCR"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00040008"
[[register]]
name = "GICH_MISR"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00040010"
[[register]]
name = "GICH_EISR0"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00040020"
[[register]]
name = "GICH_ELSR0"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00040030"
[[register]]
name = "GICH_APR0"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x000400F0"
[[register]]
name = "GICH_LR0"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00040100"
[[register]]
name = "GICH_LR1"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00040104"
[[register]]
name = "GICH_LR2"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00040108"
[[register]]
name = "GICH_LR3"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x0004010C"
[[register]]
name = "GICH_HCR_ALIAS0"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00050000"
[[register]]
name = "GICH_VTR_ALIAS0"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00050004"
[[register]]
name = "GICH_VMCR_ALIAS0"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00050008"
[[register]]
name = "GICH_MISR_ALIAS0"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00050010"
[[register]]
name = "GICH_EISR0_ALIAS0"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00050020"
[[register]]
name = "GICH_ELSR0_ALIAS0"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00050030"
[[register]]
name = "GICH_APR0_ALIAS0"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x000500F0"
[[register]]
name = "GICH_LR0_ALIAS0"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00050100"
[[register]]
name = "GICH_LR1_ALIAS0"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00050104"
[[register]]
name = "GICH_LR2_ALIAS0"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00050108"
[[register]]
name = "GICH_LR3_ALIAS0"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x0005010C"
[[register]]
name = "GICH_HCR_ALIAS1"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00050200"
[[register]]
name = "GICH_VTR_ALIAS1"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00050204"
[[register]]
name = "GICH_VMCR_ALIAS1"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00050208"
[[register]]
name = "GICH_MISR_ALIAS1"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00050210"
[[register]]
name = "GICH_EISR0_ALIAS1"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00050220"
[[register]]
name = "GICH_ELSR0_ALIAS1"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00050230"
[[register]]
name = "GICH_APR0_ALIAS1"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x000502F0"
[[register]]
name = "GICH_LR0_ALIAS1"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00050300"
[[register]]
name = "GICH_LR1_ALIAS1"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00050304"
[[register]]
name = "GICH_LR2_ALIAS1"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00050308"
[[register]]
name = "GICH_LR3_ALIAS1"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x0005030C"
[[register]]
name = "GICH_HCR_ALIAS2"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00050400"
[[register]]
name = "GICH_VTR_ALIAS2"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00050404"
[[register]]
name = "GICH_VMCR_ALIAS2"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00050408"
[[register]]
name = "GICH_MISR_ALIAS2"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00050410"
[[register]]
name = "GICH_EISR0_ALIAS2"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00050420"
[[register]]
name = "GICH_ELSR0_ALIAS2"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00050430"
[[register]]
name = "GICH_APR0_ALIAS2"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x000504F0"
[[register]]
name = "GICH_LR0_ALIAS2"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00050500"
[[register]]
name = "GICH_LR1_ALIAS2"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00050504"
[[register]]
name = "GICH_LR2_ALIAS2"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00050508"
[[register]]
name = "GICH_LR3_ALIAS2"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x0005050C"
[[register]]
name = "GICH_HCR_ALIAS3"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00050600"
[[register]]
name = "GICH_VTR_ALIAS3"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00050604"
[[register]]
name = "GICH_VMCR_ALIAS3"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00050608"
[[register]]
name = "GICH_MISR_ALIAS3"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00050610"
[[register]]
name = "GICH_EISR0_ALIAS3"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00050620"
[[register]]
name = "GICH_ELSR0_ALIAS3"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00050630"
[[register]]
name = "GICH_APR0_ALIAS3"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x000506F0"
[[register]]
name = "GICH_LR0_ALIAS3"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00050700"
[[register]]
name = "GICH_LR1_ALIAS3"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00050704"
[[register]]
name = "GICH_LR2_ALIAS3"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00050708"
[[register]]
name = "GICH_LR3_ALIAS3"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x0005070C"
[[register]]
name = "GICH_HCR_ALIAS4"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00050800"
[[register]]
name = "GICH_VTR_ALIAS4"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00050804"
[[register]]
name = "GICH_VMCR_ALIAS4"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00050808"
[[register]]
name = "GICH_MISR_ALIAS4"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00050810"
[[register]]
name = "GICH_EISR0_ALIAS4"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00050820"
[[register]]
name = "GICH_ELSR0_ALIAS4"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00050830"
[[register]]
name = "GICH_APR0_ALIAS4"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x000508F0"
[[register]]
name = "GICH_LR0_ALIAS4"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00050900"
[[register]]
name = "GICH_LR1_ALIAS4"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00050904"
[[register]]
name = "GICH_LR2_ALIAS4"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00050908"
[[register]]
name = "GICH_LR3_ALIAS4"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x0005090C"
[[register]]
name = "GICH_HCR_ALIAS5"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00050A00"
[[register]]
name = "GICH_VTR_ALIAS5"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00050A04"
[[register]]
name = "GICH_VMCR_ALIAS5"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00050A08"
[[register]]
name = "GICH_MISR_ALIAS5"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00050A10"
[[register]]
name = "GICH_EISR0_ALIAS5"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00050A20"
[[register]]
name = "GICH_ELSR0_ALIAS5"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00050A30"
[[register]]
name = "GICH_APR0_ALIAS5"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x00050AF0"
[[register]]
name = "GICH_LR0_ALIAS5"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00050B00"
[[register]]
name = "GICH_LR1_ALIAS5"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00050B04"
[[register]]
name = "GICH_LR2_ALIAS5"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00050B08"
[[register]]
name = "GICH_LR3_ALIAS5"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x00050B0C"
[[register]]
name = "GICH_HCR_ALIAS6"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00050C00"
[[register]]
name = "GICH_VTR_ALIAS6"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00050C04"
[[register]]
name = "GICH_VMCR_ALIAS6"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00050C08"
[[register]]
name = "GICH_MISR_ALIAS6"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00050C10"
[[register]]
name = "GICH_EISR0_ALIAS6"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00050C20"
[[register]]
name = "GICH_ELSR0_ALIAS6"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00050C30"
[[register]]
name = "GICH_APR0_ALIAS6"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x00050CF0"
[[register]]
name = "GICH_LR0_ALIAS6"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00050D00"
[[register]]
name = "GICH_LR1_ALIAS6"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00050D04"
[[register]]
name = "GICH_LR2_ALIAS6"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00050D08"
[[register]]
name = "GICH_LR3_ALIAS6"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x00050D0C"
[[register]]
name = "GICH_HCR_ALIAS7"
type = "rw"
width = 32
description = "Hypervisor Control Register"
default = "0x00000000"
offset = "0x00050E00"
[[register]]
name = "GICH_VTR_ALIAS7"
type = "ro"
width = 32
description = "VGIC Type Register"
default = "0x90000003"
offset = "0x00050E04"
[[register]]
name = "GICH_VMCR_ALIAS7"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x004C0000"
offset = "0x00050E08"
[[register]]
name = "GICH_MISR_ALIAS7"
type = "ro"
width = 32
description = "Maintenance Interrupt Status Register"
default = "0x00000000"
offset = "0x00050E10"
[[register]]
name = "GICH_EISR0_ALIAS7"
type = "ro"
width = 32
description = "End of Interrupt Status Register"
default = "0x00000000"
offset = "0x00050E20"
[[register]]
name = "GICH_ELSR0_ALIAS7"
type = "ro"
width = 32
description = "Empty List register Status Register"
default = "0x0000000F"
offset = "0x00050E30"
[[register]]
name = "GICH_APR0_ALIAS7"
type = "rw"
width = 32
description = "Active Priority Register"
default = "0x00000000"
offset = "0x00050EF0"
[[register]]
name = "GICH_LR0_ALIAS7"
type = "rw"
width = 32
description = "List Register 0"
default = "0x00000000"
offset = "0x00050F00"
[[register]]
name = "GICH_LR1_ALIAS7"
type = "rw"
width = 32
description = "List Register 1"
default = "0x00000000"
offset = "0x00050F04"
[[register]]
name = "GICH_LR2_ALIAS7"
type = "rw"
width = 32
description = "List Register 2"
default = "0x00000000"
offset = "0x00050F08"
[[register]]
name = "GICH_LR3_ALIAS7"
type = "rw"
width = 32
description = "List Register 3"
default = "0x00000000"
offset = "0x00050F0C"
[[register]]
name = "GICV_CTLR"
type = "rw"
width = 32
description = "Virtual Machine Control Register"
default = "0x00000000"
offset = "0x00060000"
[[register]]
name = "GICV_PMR"
type = "rw"
width = 32
description = "VM Priority Mask Register"
default = "0x00000000"
offset = "0x00060004"
[[register]]
name = "GICV_BPR"
type = "rw"
width = 32
description = "VM Binary Point Register"
default = "0x00000002"
offset = "0x00060008"
[[register]]
name = "GICV_IAR"
type = "ro"
width = 32
description = "VM Interrupt Acknowledge Register"
default = "0x000003FF"
offset = "0x0006000C"
[[register]]
name = "GICV_EOIR"
type = "wo"
width = 32
description = "VM End of Interrupt Register"
default = "0x00000000"
offset = "0x00060010"
[[register]]
name = "GICV_RPR"
type = "ro"
width = 32
description = "VM Running Priority Register"
default = "0x000000FF"
offset = "0x00060014"
[[register]]
name = "GICV_HPPIR"
type = "ro"
width = 32
description = "VM Highest Priority Pending Interrupt Register"
default = "0x000003FF"
offset = "0x00060018"
[[register]]
name = "GICV_ABPR"
type = "rw"
width = 32
description = "VM Aliased Binary Point Register"
default = "0x00000003"
offset = "0x0006001C"
[[register]]
name = "GICV_AIAR"
type = "ro"
width = 32
description = "VM Aliased Interrupt Acknowledge Register"
default = "0x000003FF"
offset = "0x00060020"
[[register]]
name = "GICV_AEOIR"
type = "wo"
width = 32
description = "VM Aliased End of Interrupt Register"
default = "0x00000000"
offset = "0x00060024"
[[register]]
name = "GICV_AHPPIR"
type = "ro"
width = 32
description = "VM Aliased Highest Priority Pending Interrupt Register"
default = "0x000003FF"
offset = "0x00060028"
[[register]]
name = "GICV_APR0"
type = "rw"
width = 32
description = "VM Active Priority Register"
default = "0x00000000"
offset = "0x000600D0"
[[register]]
name = "GICV_IIDR"
type = "ro"
width = 32
description = "VM CPU Interface Identification Register"
default = "0x0202143B"
offset = "0x000600FC"
[[register]]
name = "GICV_DIR"
type = "wo"
width = 32
description = "VM Deactivate Interrupt Register"
default = "0x00000000"
offset = "0x00070000"
