description = "OCM Memory Controller Configuration"
[[bank]]
  name = "OCM"
  address = "0xff960000"
[[register]]
  name = "OCM_ERR_CTRL"
  type = "mixed"
  width = 32
  description = "Enable/Disable a error response"
  default = "0x0000000F"
  offset = "0x00000000"
  [[register.field]]
    name = "RESERVED"
    bits = "31:4"
    type = "raz"
  [[register.field]]
    name = "UE_RES"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "PWR_ERR_RES"
    bits = "2"
    type = "rw"
  [[register.field]]
    name = "PZ_ERR_RES"
    bits = "1"
    type = "rw"
    shortdesc = '''XMPU security check fails,XMPU asserts poison signal on read nad write channel.'''
    longdesc = '''When XMPU asserts poison signal, the resulting decode eror will be: 0: decerr = 1'b0 1: decerr = 1'b1 There is also a maskable interrupt , "INV_OCM_INT" that could be asserted, independent of what option is selected here.'''
  [[register.field]]
    name = "APB_ERR_RES"
    bits = "0"
    type = "rw"
[[register]]
  name = "OCM_ISR"
  type = "mixed"
  width = 32
  description = "Interrupt Status Register for intrN. This is a sticky register that holds the value of the interrupt until cleared by a value of 1."
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "RESERVED"
    bits = "31:11"
    type = "raz"
  [[register.field]]
    name = "UE_RMW"
    bits = "10"
    type = "wtc"
  [[register.field]]
    name = "FIX_BURST_WR"
    bits = "9"
    type = "wtc"
  [[register.field]]
    name = "FIX_BURST_RD"
    bits = "8"
    type = "wtc"
  [[register.field]]
    name = "ECC_UE"
    bits = "7"
    type = "wtc"
  [[register.field]]
    name = "ECC_CE"
    bits = "6"
    type = "wtc"
  [[register.field]]
    name = "LOCK_ERR_WR"
    bits = "5"
    type = "wtc"
  [[register.field]]
    name = "LOCK_ERR_RD"
    bits = "4"
    type = "wtc"
  [[register.field]]
    name = "INV_OCM_WR"
    bits = "3"
    type = "wtc"
  [[register.field]]
    name = "INV_OCM_RD"
    bits = "2"
    type = "wtc"
  [[register.field]]
    name = "PWR_DWN"
    bits = "1"
    type = "wtc"
  [[register.field]]
    name = "INV_APB"
    bits = "0"
    type = "wtc"
[[register]]
  name = "OCM_IMR"
  type = "mixed"
  width = 32
  description = "Interrupt Mask Register for intrN. This is a read-only location and can be atomically altered by either the IDR or the IER."
  default = "0x000007FF"
  offset = "0x00000008"
  [[register.field]]
    name = "RESERVED"
    bits = "31:11"
    type = "raz"
  [[register.field]]
    name = "UE_RMW"
    bits = "10"
    type = "ro"
  [[register.field]]
    name = "FIX_BURST_WR"
    bits = "9"
    type = "ro"
  [[register.field]]
    name = "FIX_BURST_RD"
    bits = "8"
    type = "ro"
  [[register.field]]
    name = "ECC_UE"
    bits = "7"
    type = "ro"
  [[register.field]]
    name = "ECC_CE"
    bits = "6"
    type = "ro"
  [[register.field]]
    name = "LOCK_ERR_WR"
    bits = "5"
    type = "ro"
  [[register.field]]
    name = "LOCK_ERR_RD"
    bits = "4"
    type = "ro"
  [[register.field]]
    name = "INV_OCM_WR"
    bits = "3"
    type = "ro"
  [[register.field]]
    name = "INV_OCM_RD"
    bits = "2"
    type = "ro"
  [[register.field]]
    name = "PWR_DWN"
    bits = "1"
    type = "ro"
  [[register.field]]
    name = "INV_APB"
    bits = "0"
    type = "ro"
[[register]]
  name = "OCM_IEN"
  type = "mixed"
  width = 32
  description = "Interrupt Enable Register. A write of to this location will unmask the interrupt. (IMR: 0)"
  default = "0x00000000"
  offset = "0x0000000C"
  [[register.field]]
    name = "RESERVED"
    bits = "31:11"
    type = "raz"
  [[register.field]]
    name = "UE_RMW"
    bits = "10"
    type = "wo"
  [[register.field]]
    name = "FIX_BURST_WR"
    bits = "9"
    type = "wo"
  [[register.field]]
    name = "FIX_BURST_RD"
    bits = "8"
    type = "wo"
  [[register.field]]
    name = "ECC_UE"
    bits = "7"
    type = "wo"
  [[register.field]]
    name = "ECC_CE"
    bits = "6"
    type = "wo"
  [[register.field]]
    name = "LOCK_ERR_WR"
    bits = "5"
    type = "wo"
  [[register.field]]
    name = "LOCK_ERR_RD"
    bits = "4"
    type = "wo"
  [[register.field]]
    name = "INV_OCM_WR"
    bits = "3"
    type = "wo"
  [[register.field]]
    name = "INV_OCM_RD"
    bits = "2"
    type = "wo"
  [[register.field]]
    name = "PWR_DWN"
    bits = "1"
    type = "wo"
  [[register.field]]
    name = "INV_APB"
    bits = "0"
    type = "wo"
[[register]]
  name = "OCM_IDS"
  type = "mixed"
  width = 32
  description = "Interrupt Disable Register. A write of one to this location will mask the interrupt. (IMR: 1)"
  default = "0x00000000"
  offset = "0x00000010"
  [[register.field]]
    name = "RESERVED"
    bits = "31:11"
    type = "raz"
  [[register.field]]
    name = "UE_RMW"
    bits = "10"
    type = "wo"
  [[register.field]]
    name = "FIX_BURST_WR"
    bits = "9"
    type = "wo"
  [[register.field]]
    name = "FIX_BURST_RD"
    bits = "8"
    type = "wo"
  [[register.field]]
    name = "ECC_UE"
    bits = "7"
    type = "wo"
  [[register.field]]
    name = "ECC_CE"
    bits = "6"
    type = "wo"
  [[register.field]]
    name = "LOCK_ERR_WR"
    bits = "5"
    type = "wo"
  [[register.field]]
    name = "LOCK_ERR_RD"
    bits = "4"
    type = "wo"
  [[register.field]]
    name = "INV_OCM_WR"
    bits = "3"
    type = "wo"
  [[register.field]]
    name = "INV_OCM_RD"
    bits = "2"
    type = "wo"
  [[register.field]]
    name = "PWR_DWN"
    bits = "1"
    type = "wo"
  [[register.field]]
    name = "INV_APB"
    bits = "0"
    type = "wo"
[[register]]
  name = "OCM_ECC_CTRL"
  type = "mixed"
  width = 32
  description = "control register for OCM"
  default = "0x00000000"
  offset = "0x00000014"
  [[register.field]]
    name = "RESERVED"
    bits = "31:3"
    type = "raz"
  [[register.field]]
    name = "FI_MODE"
    bits = "2"
    type = "rw"
    shortdesc = '''User can inject error in OCM DATA & Syndrome bits by writing fault inject register along with fault inject counter register.'''
    longdesc = '''OCM loads the internal counter with the fault inject counter regiser value and count down on every clock cycle. Once counter reaches to "zero", ocm injects one/mutiple error indicated by fault inject register depending on FI_MODE 0 = Inject single error on write trasaction after FI Counter reaches to zero 1= Inject error on every write transaction after FI counter reaches to zero'''
  [[register.field]]
    name = "DET_ONLY"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "ECC_ON_OFF"
    bits = "0"
    type = "rw"
    shortdesc = '''ON/OFF controll of ECC port 1 = on ; 0 = OFF.'''
    longdesc = '''This bit should be initialized during system boot. It should not be changed while OCM is in use'''
[[register]]
  name = "OCM_CLR_EXE"
  type = "mixed"
  width = 32
  description = "CLEAR REGITER FOR EXLCUSIVE ACCESS MONITORS"
  default = "0x00000000"
  offset = "0x00000018"
  [[register.field]]
    name = "RESERVED"
    bits = "31:8"
    type = "raz"
  [[register.field]]
    name = "MON_7"
    bits = "7"
    type = "wo"
  [[register.field]]
    name = "MON_6"
    bits = "6"
    type = "wo"
  [[register.field]]
    name = "MON_5"
    bits = "5"
    type = "wo"
  [[register.field]]
    name = "MON_4"
    bits = "4"
    type = "wo"
  [[register.field]]
    name = "MON_3"
    bits = "3"
    type = "wo"
  [[register.field]]
    name = "MON_2"
    bits = "2"
    type = "wo"
  [[register.field]]
    name = "MON_1"
    bits = "1"
    type = "wo"
  [[register.field]]
    name = "MON_0"
    bits = "0"
    type = "wo"
[[register]]
  name = "OCM_CE_FFA"
  type = "mixed"
  width = 32
  description = "Correctable Error First Failing Address Register"
  default = "0x00000000"
  offset = "0x0000001C"
  [[register.field]]
    name = "RESERVED"
    bits = "31:18"
    type = "raz"
  [[register.field]]
    name = "ADDR"
    bits = "17:0"
    type = "ro"
    shortdesc = '''This register stores the memory address [17:0] for 256KB OCM) of the first occurrence of an access with a correctable error.'''
    longdesc = '''OCM holds the logged value untill software clears the CE interrupt.'''
[[register]]
  name = "OCM_CE_FFD0"
  type = "ro"
  width = 32
  description = "Correctable Error First Failing Data Register (CE_FFD [31:0])"
  default = "0x00000000"
  offset = "0x00000020"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''This register stores the (uncorrected) failing data (bits [31:0]) of the first occurrence of an access with a correctable error.'''
    longdesc = '''OCM holds the logged value untill software clears the CE interrupt.'''
[[register]]
  name = "OCM_CE_FFD1"
  type = "ro"
  width = 32
  description = "Correctable Error First Failing Data Register (CE_FFD [63:32])"
  default = "0x00000000"
  offset = "0x00000024"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''This register stores the (uncorrected) failing data (bits [63:32]) of the first occurrence of an access with a correctable error.'''
    longdesc = '''OCM holds the logged value untill software clears the CE interrupt.'''
[[register]]
  name = "OCM_CE_FFD2"
  type = "ro"
  width = 32
  description = "Correctable Error First Failing Data Register (CE_FFD [95:64])"
  default = "0x00000000"
  offset = "0x00000028"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''This register stores the (uncorrected) failing data (bits [95:64]) of the first occurrence of an access with a correctable error.'''
    longdesc = '''OCM holds the logged value untill software clears the CE interrupt.'''
[[register]]
  name = "OCM_CE_FFD3"
  type = "ro"
  width = 32
  description = "Correctable Error First Failing Data Register (CE_FFD [127:96])"
  default = "0x00000000"
  offset = "0x0000002C"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''This register stores the (uncorrected) failing data (bits [127:96]) of the first occurrence of an access with a correctable error.'''
    longdesc = '''OCM holds the logged value untill software clears the CE interrupt.'''
[[register]]
  name = "OCM_CE_FFE"
  type = "mixed"
  width = 32
  description = "Correctable Error First Failing ECC Register"
  default = "0x00000000"
  offset = "0x00000030"
  [[register.field]]
    name = "RESERVED"
    bits = "31:16"
    type = "raz"
  [[register.field]]
    name = "SYNDROME"
    bits = "15:0"
    type = "ro"
    shortdesc = '''This register stores the ECC bits of the first occurrence of an access with a correctable error.'''
    longdesc = '''OCM holds the logged value untill software clears the CE interrupt.'''
[[register]]
  name = "OCM_UE_FFA"
  type = "mixed"
  width = 32
  description = "Uncorrectable Error First Failing Address Register"
  default = "0x00000000"
  offset = "0x00000034"
  [[register.field]]
    name = "RESERVED"
    bits = "31:18"
    type = "raz"
  [[register.field]]
    name = "ADDR"
    bits = "17:0"
    type = "ro"
[[register]]
  name = "OCM_UE_FFD0"
  type = "ro"
  width = 32
  description = "Uncorrectable Error First Failing Data Register (UE_FFD [31:0])"
  default = "0x00000000"
  offset = "0x00000038"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''This register stores the (uncorrected) failing data (bits [31:0]) of the first occurrence of an access with a uncorrectable error.'''
    longdesc = '''OCM holds the logged value untill software clears the UE interrupt.'''
[[register]]
  name = "OCM_UE_FFD1"
  type = "ro"
  width = 32
  description = "Uncorrectable Error First Failing Data Register (UE_FFD [63:32])"
  default = "0x00000000"
  offset = "0x0000003C"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''This register stores the (uncorrected) failing data (bits [63:32]) of the first occurrence of an access with a uncorrectable error.'''
    longdesc = '''OCM holds the logged value untill software clears the UE interrupt.'''
[[register]]
  name = "OCM_UE_FFD2"
  type = "ro"
  width = 32
  description = "Uncorrectable Error First Failing Data Register (UE_FFD [95:64])"
  default = "0x00000000"
  offset = "0x00000040"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''This register stores the (uncorrected) failing data (bits [95:64]) of the first occurrence of an access with a uncorrectable error.'''
    longdesc = '''OCM holds the logged value untill software clears the UE interrupt.'''
[[register]]
  name = "OCM_UE_FFD3"
  type = "ro"
  width = 32
  description = "Uncorrectable Error First Failing Data Register (UE_FFD [127:96])"
  default = "0x00000000"
  offset = "0x00000044"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "ro"
    shortdesc = '''This register stores the (uncorrected) failing data (bits [127:96]) of the first occurrence of an access with a uncorrectable error.'''
    longdesc = '''OCM holds the logged value untill software clears the UE interrupt.'''
[[register]]
  name = "OCM_UE_FFE"
  type = "mixed"
  width = 32
  description = "Uncorrectable Error First Failing ECC Register"
  default = "0x00000000"
  offset = "0x00000048"
  [[register.field]]
    name = "RESERVED"
    bits = "31:16"
    type = "raz"
  [[register.field]]
    name = "SYNDROME"
    bits = "15:0"
    type = "ro"
[[register]]
  name = "OCM_FI_D0"
  type = "rw"
  width = 32
  description = "Fault Injection Data Register (FI_D0)"
  default = "0x00000000"
  offset = "0x0000004C"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "OCM_FI_D1"
  type = "rw"
  width = 32
  description = "Fault Injection Data Register (FI_D1)"
  default = "0x00000000"
  offset = "0x00000050"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "OCM_FI_D2"
  type = "rw"
  width = 32
  description = "Fault Injection Data Register (FI_D2)"
  default = "0x00000000"
  offset = "0x00000054"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "OCM_FI_D3"
  type = "rw"
  width = 32
  description = "Fault Injection Data Register (FI_D3)"
  default = "0x00000000"
  offset = "0x00000058"
  [[register.field]]
    name = "DATA"
    bits = "31:0"
    type = "rw"
[[register]]
  name = "OCM_FI_SY"
  type = "mixed"
  width = 32
  description = "Fault Injection Syndrome Register (FI_SY)"
  default = "0x00000000"
  offset = "0x0000005C"
  [[register.field]]
    name = "RESERVED"
    bits = "31:16"
    type = "raz"
  [[register.field]]
    name = "DATA"
    bits = "15:0"
    type = "rw"
[[register]]
  name = "OCM_RMW_UE_FFA"
  type = "mixed"
  width = 32
  description = "RMW uncorrectable error log register"
  default = "0x00000000"
  offset = "0x00000070"
  [[register.field]]
    name = "RESERVED"
    bits = "31:18"
    type = "raz"
  [[register.field]]
    name = "ADDR"
    bits = "17:0"
    type = "ro"
[[register]]
  name = "OCM_FI_CNTR"
  type = "mixed"
  width = 32
  description = "Fault Injection Count Register"
  default = "0x00000000"
  offset = "0x00000074"
  [[register.field]]
    name = "RESERVED"
    bits = "31:24"
    type = "raz"
  [[register.field]]
    name = "COUNT"
    bits = "23:0"
    type = "rw"
    shortdesc = '''OCM FI Counter value in its internal counter and count down on every clock cycle.'''
    longdesc = '''Once counter reach to Zero, it injects single/multiple error (depend on FI_MODE bit) in bits indicated by FI_D and FI_SY registers'''
[[register]]
  name = "OCM_IMP"
  type = "mixed"
  width = 32
  description = "OCM Implementation Register"
  default = "0x00000000"
  offset = "0x00000080"
  [[register.field]]
    name = "RESERVED"
    bits = "31:4"
    type = "raz"
  [[register.field]]
    name = "SIZE"
    bits = "3:0"
    type = "ro"
[[register]]
  name = "OCM_PRDY_DBG"
  type = "mixed"
  width = 32
  description = "OCM PRDY Debug register"
  default = "0x0000FFFF"
  offset = "0x00000084"
  [[register.field]]
    name = "RESERVED"
    bits = "31:16"
    type = "raz"
  [[register.field]]
    name = "BANK3"
    bits = "15:12"
    type = "ro"
  [[register.field]]
    name = "BANK2"
    bits = "11:8"
    type = "ro"
  [[register.field]]
    name = "BANK1"
    bits = "7:4"
    type = "ro"
  [[register.field]]
    name = "BANK0"
    bits = "3:0"
    type = "ro"
[[register]]
  name = "OCM_SAFETY_CHK"
  type = "rw"
  width = 32
  description = "OCM Safety Check Register"
  default = "0x00000000"
  offset = "0x00000FF8"
  [[register.field]]
    name = "VAL"
    bits = "31:0"
    type = "rw"
