description = "Replicator forks ATB data to multiple streams"
[[bank]]
  name = "CORESIGHT_SOC_REPLIC"
  address = "0xfe960000"
[[register]]
  name = "IDFILTER0"
  type = "rw"
  width = 32
  description = "Allows the setting of ID filter for Master 0."
  default = "0x00000000"
  offset = "0x00000000"
  [[register.field]]
    name = "ID0_70_7F"
    bits = "7"
    type = "rw"
  [[register.field]]
    name = "ID0_60_6F"
    bits = "6"
    type = "rw"
  [[register.field]]
    name = "ID0_50_5F"
    bits = "5"
    type = "rw"
  [[register.field]]
    name = "ID0_40_4F"
    bits = "4"
    type = "rw"
  [[register.field]]
    name = "ID0_30_3F"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "ID0_20_2F"
    bits = "2"
    type = "rw"
  [[register.field]]
    name = "ID0_10_1F"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "ID0_0_F"
    bits = "0"
    type = "rw"
[[register]]
  name = "IDFILTER1"
  type = "rw"
  width = 32
  description = "Allows the setting of ID filter for Master 1."
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "ID1_70_7F"
    bits = "7"
    type = "rw"
  [[register.field]]
    name = "ID1_60_6F"
    bits = "6"
    type = "rw"
  [[register.field]]
    name = "ID1_50_5F"
    bits = "5"
    type = "rw"
  [[register.field]]
    name = "ID1_40_4F"
    bits = "4"
    type = "rw"
  [[register.field]]
    name = "ID1_30_3F"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "ID1_20_2F"
    bits = "2"
    type = "rw"
  [[register.field]]
    name = "ID1_10_1F"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "ID1_0_F"
    bits = "0"
    type = "rw"
[[register]]
  name = "ITATBCTR1"
  type = "ro"
  width = 32
  description = "Returns the value of the ATREADYM0, ATREADYM1 and ATVALIDS inputs in integration mode."
  default = "0x00000000"
  offset = "0x00000EF8"
  [[register.field]]
    name = "ATVALIDS_R"
    bits = "3"
    type = "ro"
  [[register.field]]
    name = "ATREADYM1_R"
    bits = "1"
    type = "ro"
  [[register.field]]
    name = "ATREADYM0_R"
    bits = "0"
    type = "ro"
[[register]]
  name = "ITATBCTR0"
  type = "wo"
  width = 32
  description = "Controls the value of the ATVALIDM0, ATVALIDM1 and ATREADYS outputs in integration mode."
  default = "0x00000000"
  offset = "0x00000EFC"
  [[register.field]]
    name = "ATREADYS_W"
    bits = "4"
    type = "wo"
  [[register.field]]
    name = "ATVALIDM1_W"
    bits = "2"
    type = "wo"
  [[register.field]]
    name = "ATVALIDM0_W"
    bits = "0"
    type = "wo"
[[register]]
  name = "ITCTRL"
  type = "rw"
  width = 32
  description = "Used to enable topology detection. See the CoreSight Architecture Specification for more information. This register enables the component to switch from a functional mode, the default behavior, to integration mode where the inputs and outputs of the component can be directly controlled for integration testing and topology solving. Note: When a device has been in integration mode, it might not function with the original behavior. After performing integration or topology detection, you must reset the system to ensure correct behavior of CoreSight and other connected system components that are affected by the integration or topology detection."
  default = "0x00000000"
  offset = "0x00000F00"
  [[register.field]]
    name = "INTEGRATION_MODE"
    bits = "0"
    type = "rw"
    shortdesc = '''Enables the component to switch from functional mode to integration mode and back.'''
    longdesc = '''If no integration functionality is implemented, this register must read as zero.'''
[[register]]
  name = "CLAIMSET"
  type = "rw"
  width = 32
  description = "This is used in conjunction with Claim Tag Clear Register, CLAIMCLR. This register forms one half of the Claim Tag value. This location allows individual bits to be set, write, and returns the number of bits that can be set, read."
  default = "0x0000000F"
  offset = "0x00000FA0"
  [[register.field]]
    name = "CLAIMSET"
    bits = "3:0"
    type = "rw"
[[register]]
  name = "CLAIMCLR"
  type = "rw"
  width = 32
  description = "This register is used in conjunction with Claim Tag Set Register, CLAIMSET. This register forms one half of the Claim Tag value. This location enables individual bits to be cleared, write, and returns the current Claim Tag value, read."
  default = "0x00000000"
  offset = "0x00000FA4"
  [[register.field]]
    name = "CLAIMCLR"
    bits = "3:0"
    type = "rw"
[[register]]
  name = "LAR"
  type = "wo"
  width = 32
  description = "This is used to enable write access to device registers."
  default = "0x00000000"
  offset = "0x00000FB0"
  [[register.field]]
    name = "ACCESS_W"
    bits = "31:0"
    type = "wo"
    shortdesc = '''A write of 0xC5ACCE55 enables further write access to this device.'''
    longdesc = '''An invalid write has the affect of removing write access.'''
[[register]]
  name = "LSR"
  type = "ro"
  width = 32
  description = "This indicates the status of the lock control mechanism. This lock prevents accidental writes by code under debug. This register must always be present although there might not be any lock access control mechanism. The lock mechanism, where present and locked, must block write accesses to any control register, except the Lock Access Register. For most components this covers all registers except for the Lock Access Register, 0xFB0."
  default = "0x00000003"
  offset = "0x00000FB4"
  [[register.field]]
    name = "LOCKTYPE"
    bits = "2"
    type = "ro"
  [[register.field]]
    name = "LOCKGRANT"
    bits = "1"
    type = "ro"
  [[register.field]]
    name = "LOCKEXIST"
    bits = "0"
    type = "ro"
[[register]]
  name = "AUTHSTATUS"
  type = "ro"
  width = 32
  description = "Reports the required security level and current status of those enables. Where functionality changes on a given security level then this change in status must be reported in this register"
  default = "0x00000000"
  offset = "0x00000FB8"
  [[register.field]]
    name = "SNID"
    bits = "7:6"
    type = "ro"
  [[register.field]]
    name = "SID"
    bits = "5:4"
    type = "ro"
  [[register.field]]
    name = "NSNID"
    bits = "3:2"
    type = "ro"
  [[register.field]]
    name = "NSID"
    bits = "1:0"
    type = "ro"
[[register]]
  name = "DEVID"
  type = "ro"
  width = 32
  description = "Indicates the capabilities of the CoreSight Replicator."
  default = "0x00000002"
  offset = "0x00000FC8"
  [[register.field]]
    name = "PORTNUM"
    bits = "3:0"
    type = "ro"
[[register]]
  name = "DEVTYPE"
  type = "ro"
  width = 32
  description = "Provides a debugger with information about the component when the Part Number field is not recognized. The debugger can then report this information."
  default = "0x00000022"
  offset = "0x00000FCC"
  [[register.field]]
    name = "SUB_TYPE"
    bits = "7:4"
    type = "ro"
  [[register.field]]
    name = "MAJOR_TYPE"
    bits = "3:0"
    type = "ro"
[[register]]
  name = "PIDR4"
  type = "ro"
  width = 32
  description = "Part of the set of Peripheral Identification registers. Contains part of the designer identity and the memory footprint indicator."
  default = "0x00000004"
  offset = "0x00000FD0"
  [[register.field]]
    name = "FOURKB_COUNT"
    bits = "7:4"
    type = "ro"
    shortdesc = '''This is a 4-bit value that indicates the total contiguous size of the memory window used by this component in powers of 2 from the standard 4KB.'''
    longdesc = '''If a component only requires the standard 4KB, this must read as 0x0, 4KB only. For 8KB set to 0x1, for 16KB set to 0x2, for 32KB set to 0x3, and so on.'''
  [[register.field]]
    name = "JEP106_CONT"
    bits = "3:0"
    type = "ro"
[[register]]
  name = "PIDR5"
  type = "rw"
  width = 32
  description = "Reserved"
  default = "0x00000000"
  offset = "0x00000FD4"
[[register]]
  name = "PIDR6"
  type = "rw"
  width = 32
  description = "Reserved"
  default = "0x00000000"
  offset = "0x00000FD8"
[[register]]
  name = "PIDR7"
  type = "rw"
  width = 32
  description = "Reserved"
  default = "0x00000000"
  offset = "0x00000FDC"
[[register]]
  name = "PIDR0"
  type = "ro"
  width = 32
  description = "Part of the set of Peripheral Identification registers. Contains part of the designer specific part number."
  default = "0x00000009"
  offset = "0x00000FE0"
  [[register.field]]
    name = "PART_NUMBER_BITS7TO0"
    bits = "7:0"
    type = "ro"
    shortdesc = '''Bits [7:0] of the component part number.'''
    longdesc = '''This is selected by the designer of the component.'''
[[register]]
  name = "PIDR1"
  type = "ro"
  width = 32
  description = "Part of the set of Peripheral Identification registers. Contains part of the designer specific part number and part of the designer identity."
  default = "0x000000B9"
  offset = "0x00000FE4"
  [[register.field]]
    name = "JEP106_BITS3TO0"
    bits = "7:4"
    type = "ro"
  [[register.field]]
    name = "PART_NUMBER_BITS11TO8"
    bits = "3:0"
    type = "ro"
    shortdesc = '''Bits [11:8] of the component part number.'''
    longdesc = '''This is selected by the designer of the component.'''
[[register]]
  name = "PIDR2"
  type = "ro"
  width = 32
  description = "Part of the set of Peripheral Identification registers. Contains part of the designer identity and the product revision."
  default = "0x0000001B"
  offset = "0x00000FE8"
  [[register.field]]
    name = "REVISION"
    bits = "7:4"
    type = "ro"
    shortdesc = '''The Revision field is an incremental value starting at 0x0 for the first design of this component.'''
    longdesc = '''This only increases by 1 for both major and minor revisions and is used as a look-up to establish the exact major and minor revision.'''
  [[register.field]]
    name = "JEDEC"
    bits = "3"
    type = "ro"
    shortdesc = '''Always set.'''
    longdesc = '''Indicates that a JEDEC assigned value is used.'''
  [[register.field]]
    name = "JEP106_BITS6TO4"
    bits = "2:0"
    type = "ro"
[[register]]
  name = "PIDR3"
  type = "ro"
  width = 32
  description = "Part of the set of Peripheral Identification registers. Contains the RevAnd and Customer Modified fields."
  default = "0x00000000"
  offset = "0x00000FEC"
  [[register.field]]
    name = "REVAND"
    bits = "7:4"
    type = "ro"
    shortdesc = '''This field indicates minor errata fixes specific to this design, for example metal fixes after implementation.'''
    longdesc = '''In most cases this field is zero. It is recommended that component designers ensure this field can be changed by a metal fix if required, for example by driving it from registers that reset to zero.'''
  [[register.field]]
    name = "CUSTOMER_MODIFIED"
    bits = "3:0"
    type = "ro"
    shortdesc = '''Where the component is reusable IP, this value indicates if the customer has modified the behavior of the component.'''
    longdesc = '''In most cases this field is zero.'''
[[register]]
  name = "CIDR0"
  type = "ro"
  width = 32
  description = "A component identification register, that indicates that the identification registers are present."
  default = "0x0000000D"
  offset = "0x00000FF0"
  [[register.field]]
    name = "PREAMBLE"
    bits = "7:0"
    type = "ro"
[[register]]
  name = "CIDR1"
  type = "ro"
  width = 32
  description = "A component identification register, that indicates that the identification registers are present. This register also indicates the component class."
  default = "0x00000090"
  offset = "0x00000FF4"
  [[register.field]]
    name = "CLASS"
    bits = "7:4"
    type = "ro"
  [[register.field]]
    name = "PREAMBLE"
    bits = "3:0"
    type = "ro"
[[register]]
  name = "CIDR2"
  type = "ro"
  width = 32
  description = "A component identification register, that indicates that the identification registers are present."
  default = "0x00000005"
  offset = "0x00000FF8"
  [[register.field]]
    name = "PREAMBLE"
    bits = "7:0"
    type = "ro"
[[register]]
  name = "CIDR3"
  type = "ro"
  width = 32
  description = "A component identification register, that indicates that the identification registers are present."
  default = "0x000000B1"
  offset = "0x00000FFC"
  [[register.field]]
    name = "PREAMBLE"
    bits = "7:0"
    type = "ro"
