[[instance]]
type = "cpu.pmu"

[[instance]]
name = "PMUInternalBus"
type = "bus.axi4"

[[instance]]
name = "pmuram"
type = "ram.sram.pmuram"

[[connection]]
type = "bus"
connection = "cpu.pmu -> PMUInternalBus"

[[connection]]
type = "bus"
connection = "PMUInternalBus -> pmuram"
fixed_address = "0xFFDC_0000"
