actions = [
    "soft_src"
]

[[process]]
name = 'soft_src'
processor = 'software_sources'
cpus = "pmu"
sources = [
    { in = "src", out = "src" },
    { in = "CMakeLists.txt", out = "CMakeLists.txt" },
]
