actions = [
    "make_config",
    "sbt_run",
    "src",
    "read_verilog_top"
]

[[process]]
name = 'make_config'
processor = 'toml'
filename = 'config.toml'
parameters = [
   "apb_address_width",
   "apb_data_width",
   "apb_use_slave_error",
   "apb_pipeline",

   "pmb_addresswidth",
   "pmb_datawidth",
]

[[process]]
name = 'sbt_run'
processor = 'sbt'
main_scala = "pmb_to_apb.scala"
with_build_sbt = true
args = '+runMain PMBToAPBBridge config.toml .. ${name}'
path_op = 'push'

[[process]]
name = 'src'
processor = 'sources'
sources = [{ file = "${name}.v", language = "verilog" }]

[[process]]
name = 'read_verilog_top'
processor = 'read_verilog_top'
source = "${name}"
