[defaults]
pullup = false
slew = "Slow"
drive = 8
standard = "LVCMOS33"

[[definition]]
type = "board.myirfz3"
board_type = "Xilinx"
board_family = "UltraScale+"
board_device = "xczu3eg-sfvc784-1-e"

[[definition]]
type = "ram.ddr.ddr4.MT40A256M16LY"
size_in_bytes = "4 GiB"

[[definition]]
type = "clock.ref.25MHz"
pin = "M6"
standard = "LVCMOS18"

[[definition]]
type = "pingroup.SYS.FAN_TACH"
pin = "AD14"

[[definition]]
type = "pingroup.LED.SYS_STATUS"
pin = "AA13"
standard = "LVCMOS33"

# J15
[[definition]]
type = "pingroup.HD_L06_25"
pin_p = "F12"
pin_n = "F11"

[[definition]]
type = "pingroup.HD_L07_26"
pin_p = "G13"
pin_n = "F13"

[[definition]]
type = "pingroup.HD_L08_25"
pin_p = "E12"
pin_n = "D11"
[[definition]]
type = "pingroup.HD_L10_25"
pin_p = "B11"
pin_n = "A10"
[[definition]]
type = "pingroup.HP_BANK66_L01"
pin_p = "G1"
pin_n = "F1"
[[definition]]
type = "pingroup.HP_BANK66_L02"
pin_p = "E1"
pin_n = "D1"
[[definition]]
type = "pingroup.HP_BANK66_L07"
pin_p = "C1"
pin_n = "B1"
[[definition]]
type = "pingroup.HP_BANK66_L08"
pin_p = "A2"
pin_n = "A1"
[[definition]]
type = "pingroup.HP_BANK66_L12"
pin_p = "C3"
pin_n = "C2"
[[definition]]
type = "pingroup.HP_BANK65_L07"
pin_p = "L1"
pin_n = "K1"
[[definition]]
type = "pingroup.HP_BANK65_L08"
pin_p = "J1"
pin_n = "H1"
[[definition]]
type = "pingroup.HP_BANK65_L12"
pin_p = "L3"
pin_n = "L2"

# J16
[[definition]]
type = "pingroup.PS_MIO6"
pin = "AF16"
[[definition]]
type = "pingroup.PS_MIO7"
pin = "AH17"
[[definition]]
type = "pingroup.PS_MIO8"
pin = "AF17"
[[definition]]
type = "pingroup.PS_MIO9"
pin = "AC16"

[[definition]]
type = "pingroup.HD_L03_26"
pin_p = "B13"
pin_n = "A13"
[[definition]]
type = "pingroup.HD_L05_25"
pin_p = "G11"
pin_n = "F10"
[[definition]]
type = "pingroup.HD_L06_26"
pin_p = "E14"
pin_n = "E13"
[[definition]]
type = "pingroup.HD_L07_25"
pin_p = "E10"
pin_n = "D10"
[[definition]]
type = "pingroup.HD_L08_26"
pin_p = "F15"
pin_n = "E15"
[[definition]]
type = "pingroup.HD_L09_25"
pin_p = "C11"
pin_n = "B10"
[[definition]]
type = "pingroup.HD_L10_26"
pin_p = "H14"
pin_n = "H13"
[[definition]]
type = "pingroup.HD_L11_25"
pin_p = "A12"
pin_n = "A11"

# BT1120
[[definition]]
type = "pingroup.BT1120.CLK"
pin = "AC12"
[[definition]]
type = "pingroup.BT1120.DATA"
pins = ["Y9", "AA8", "AB9", "Y10",
    "AH11", "AG10", "AF10", "AE10",
    "AG11", "AF11", "AG21", "AF12",
    "AD10", "AE12", "W10", "AD11"]
[[definition]]
type = "pingroup.BT1120.UART0_RXD" # BT1120 GPIO X
pin = "AH10"
[[definition]]
type = "pingroup.BT1120.UART0_TXD" # BT1120 GPIO Y
pin = "AB10"
[[definition]]
type = "pingroup.BT1120.GPIO_Z"
pin = "AD12"

# MIPI CSI
[[definition]]
type = "pingroup.MIPI.CSI_CLK"
pin_p = "AD5"
pin_n = "AD4"
[[definition]]
type = "pingroup.MIPI.CSI_DATA0"
pin_p = "AC4"
pin_n = "AC3"
[[definition]]
type = "pingroup.MIPI.CSI_DATA1"
pin_p = "AB4"
pin_n = "AB3"
[[definition]]
type = "pingroup.MIPI.CSI_DATA2"
pin_p = "AB2"
pin_n = "AC2"
[[definition]]
type = "pingroup.MIPI.CSI_DATA3"
pin_p = "AB1"
pin_n = "AC1"
[[definition]]
type = "pingroup.CAM.PWDN_n"
pin = "J7"
[[definition]]
type = "pingroup.CAM.RST_n"
pin = "H7"
[[definition]]
type = "pingroup.CAM.MCLK"
pin = "K8"

[[definition]]
type = "pingroup.QSPI.LOWER_SCK"
pin = "AG15"
[[definition]]
type = "pingroup.QSPI.LOWER_DATA"
pins = ["AH16", "AG16", "AF15", "AH15"]
[[definition]]
type = "pingroup.QSPI.LOWER_CS"
pin = "AD16"

[[definition]]
type = "pingroup.SDIO1.EMMC_CMD"
pin = "AC21"
[[definition]]
type = "pingroup.SDIO1.EMMC_CLK"
pin = "AB20"
[[definition]]
type = "pingroup.SDIO1.EMMC_RST"
pin = "AB18"
[[definition]]
type = "pingroup.SDIO1.EMMC_DATA"
pins = ["AH18", "AG18", "AE18", "AF18", "AC18", "AC19", "AE19", "AD19"]

[[definition]]
type = "pingroup.SDIO0.WP"
pin = "J20"
[[definition]]
type = "pingroup.SDIO0.CD"
pin = "K20"
[[definition]]
type = "pingroup.SDIO0.CMD"
pin = "M19" # PS_MIO_50
[[definition]]
type = "pingroup.SDIO0.CLK"
pin = "L21"
[[definition]]
type = "pingroup.SDIO0.DATA"
pins = ["L20", "H21", "J21", "M18"]

[[definition]]
type = "pingroup.USBHUB.RESET_N"
pin = "J17"
[[definition]]
type = "pingroup.USBPHY.RESET_N"
pin = "H18"
[[definition]]
type = "pingroup.USB0.CLK_IN"
pin = "G18" # PS_MIO_52
[[definition]]
type = "pingroup.USB0.DIR"
pin = "D16"
[[definition]]
type = "pingroup.USB0.NXT"
pin = "B16"
[[definition]]
type = "pingroup.USB0.STP"
pin = "F18"
[[definition]]
type = "pingroup.USB0.TX_DATA"
pins = ["C16", "A16", "F17", "E17", "C17", "D17", "A17", "E18"]
[[definition]]
type = "pingroup.USB0.SSTX"
pin_p = "D23"
pin_n = "D24"
[[definition]]
type = "pingroup.USB0.SSRX"
pin_p = "D27"
pin_n = "D28"
[[definition]]
type = "pingroup.MGTR.USB3_0_CLK_26MHz"
pin_p = "E21"
pin_n = "E22"

[[definition]]
type = "pingroup.ENET.TXC"
pin = "E19"
[[definition]]
type = "pingroup.ENET.TDATA"
pins = ["A18", "G19", "B18", "C18"]
[[definition]]
type = "pingroup.ENET.TX_CTL"
pin = "D19"
[[definition]]
type = "pingroup.ENET.RXC"
pin = "C19" # PS_MIO_70
[[definition]]
type = "pingroup.ENET.RDATA"
pins = ["B19", "G20", "G21", "D20"]
[[definition]]
type = "pingroup.ENET.RX_CTL"
pin = "A19"
[[definition]]
type = "pingroup.ENET.MDC"
pin = "B20"
[[definition]]
type = "pingroup.ENET.MDIO"
pin = "F20"
[[definition]]
type = "pingroup.ENET.INT"
pin = "H19"
[[definition]]
type = "pingroup.ENET.RST"
pin = "K18" # PS_MIO_40

[[definition]]
type = "pingroup.WDT.FEED"
pin = "J19"

[[definition]]
type = "pingroup.DEBUG.RXD"
pin = "L17"
[[definition]]
type = "pingroup.DEBUG.TXD"
pin = "H17"

[[definition]]
type = "pingroup.PS.PMIC_IRQ"
pin = "L15"
[[definition]]
type = "pingroup.PL.PMIC_IRQ"
pin = "AE13"

[[definition]]
type = "pingroup.PMBUS.CLK"
pin = "AE15" # PL_SMB_SCLK
[[definition]]
type = "pingroup.PMBUS.DAT"
pin = "AG14" # PL_SMB_SDA

[[definition]]
type = "pingroup.CAN.TX"
pin = "AB19"
[[definition]]
type = "pingroup.CAN.RX"
pin = "AB21"
[[definition]]
type = "pingroup.PL.485_RXD"
pin = "AB15"
[[definition]]
type = "pingroup.PL.485_TXD"
pin = "AB14"
[[definition]]
type = "pingroup.PL.485_DE"
pin = "W14"

[[definition]]
type = "pingroup.SECURE.PIOA"
pin = "Y14"
[[definition]]
type = "pingroup.SECURE.PIOB"
pin = "Y13"

# i2c0   : cam (0x1B)
[[definition]]
type = "pingroup.I2C0.SCL"
pin = "L18"
[[definition]]
type = "pingroup.I2C0.SDA"
pin = "K19"

# on i2c1: DeepCover Secure Auth chip(DS28C36BQ) 0x1B
#        : 256Kb Eeprom (CAT24C256WI) 0x51, 
#        : pcie routed to port
#        : Clock Gen (si5332) Initial = 0x6A Config = 0x76
#        : pmbus (TPS6508641RSKT) 0x5E
[[definition]]
type = "pingroup.I2C1.SCL"
pin = "J16"
[[definition]]
type = "pingroup.I2C1.SDA"
pin = "L16"

[[definition]]
type = "pingroup.PCIE.RST"
pin = "H16"
[[definition]]
type = "pingroup.PCIE.HOTPLUG_DET"
pin = "AG13"

[[definition]]
type = "pingroup.MGTR.PCIE_CLK_100MHz"
pin_p = "F23"
pin_n = "F24"
[[definition]]
type = "pingroup.MGTR.DP_CLK_27MHz"
pin_p = "C21"
pin_n = "C22"

[[definition]]
type = "pingroup.MGT0_PCIE_TX0"
pin_p = "E25"
pin_n = "E26"
[[definition]]
type = "pingroup.MGT0_PCIE_RX0"
pin_p = "F27"
pin_n = "F28"
[[definition]]
type = "pingroup.MGT0.DP1_TX"
pin_p = "C25"
pin_n = "C26"
[[definition]]
type = "pingroup.MGT0.DP0_TX"
pin_p = "B25"
pin_n = "B24"

[[definition]]
type = "pingroup.DP.DOUT"
pin = "J15"
[[definition]]
type = "pingroup.DP.HP_DET"
pin = "K15"
[[definition]]
type = "pingroup.DP.OE"
pin = "G16"
[[definition]]
type = "pingroup.DP.DIN"
pin = "F16" # PS_MIO_30
