description = "FPD System-level Control - Secure"
[[register]]
  name = "CTRL"
  type = "rw"
  width = 1
  description = "General control register for the LPD SLCR SECURE."
  default = "0x00000000"
  offset = "0x00000004"
  [[register.field]]
    name = "SLVERR_ENABLE"
    bits = "0"
    type = "rw"
    shortdesc = '''By default, invalid address requests are ignored.'''
    longdesc = '''However, a maskable interrupt exists. By enabling this slverr_enable, invalid address requests cause a slverr to occur. Enable/Disable SLVERR during address decode failure. 0: SLVERR is disabled. Register write is ignored. Read returns 0. 1: SLVERR is enabled. SLVERR is asserted. Register write is ignored. Read returns 0.'''
[[register]]
  name = "ISR"
  type = "wtc"
  width = 1
  description = "Interrupt Status and clear."
  default = "0x00000000"
  offset = "0x00000008"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wtc"
    shortdesc = '''Status for an address decode error.'''
    longdesc = '''Reads: 0: No Event. 1: Event Occurred. Writes: 0: ignored. 1: clear bit.'''
[[register]]
  name = "IMR"
  type = "ro"
  width = 1
  description = "Interrupt Mask"
  default = "0x00000001"
  offset = "0x0000000C"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "ro"
    shortdesc = '''Mask for an address decode error.'''
    longdesc = '''0: Interrupt Enabled 1: Interrupt Disabled'''
[[register]]
  name = "IER"
  type = "wo"
  width = 1
  description = "Interrupt Enable"
  default = "0x00000000"
  offset = "0x00000010"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
    shortdesc = '''Enable for an address decode error.'''
    longdesc = '''Writes: 0: ignored. 1: IMR register bit set to 0.'''
[[register]]
  name = "IDR"
  type = "wo"
  width = 1
  description = "Interrupt Disable"
  default = "0x00000000"
  offset = "0x00000014"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
    shortdesc = '''Mask for an address decode error.'''
    longdesc = '''Writes: 0: ignored. 1: IMR register bit set to 1.'''
[[register]]
  name = "ITR"
  type = "wo"
  width = 1
  description = "Interrupt Trigger"
  default = "0x00000000"
  offset = "0x00000018"
  [[register.field]]
    name = "ADDR_DECODE_ERR"
    bits = "0"
    type = "wo"
    shortdesc = '''Trigger an address decode error interrupt.'''
    longdesc = '''Writes: 0: ignored. 1: ISR register bit set to 1.'''
[[register]]
  name = "SLCR_SATA"
  type = "mixed"
  width = 32
  description = "SATA TrustZone settings."
  default = "0x0000000E"
  offset = "0x00000020"
  [[register.field]]
    name = "RESERVED"
    bits = "31:4"
    type = "raz"
  [[register.field]]
    name = "TZ_AXIMDMA1"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "TZ_AXIMDMA0"
    bits = "2"
    type = "rw"
  [[register.field]]
    name = "TZ_AXIS"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "TZ_EN"
    bits = "0"
    type = "rw"
[[register]]
  name = "SLCR_PCIE"
  type = "mixed"
  width = 32
  description = "PCIe TrustZone settings."
  default = "0x01FFFFFF"
  offset = "0x00000030"
  [[register.field]]
    name = "RESERVED"
    bits = "31:25"
    type = "raz"
  [[register.field]]
    name = "TZ_DMA_3"
    bits = "24"
    type = "rw"
  [[register.field]]
    name = "TZ_DMA_2"
    bits = "23"
    type = "rw"
  [[register.field]]
    name = "TZ_DMA_1"
    bits = "22"
    type = "rw"
  [[register.field]]
    name = "TZ_DMA_0"
    bits = "21"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_INGR_7"
    bits = "20"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_INGR_6"
    bits = "19"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_INGR_5"
    bits = "18"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_INGR_4"
    bits = "17"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_INGR_3"
    bits = "16"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_INGR_2"
    bits = "15"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_INGR_1"
    bits = "14"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_INGR_0"
    bits = "13"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_EGR_7"
    bits = "12"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_EGR_6"
    bits = "11"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_EGR_5"
    bits = "10"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_EGR_4"
    bits = "9"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_EGR_3"
    bits = "8"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_EGR_2"
    bits = "7"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_EGR_1"
    bits = "6"
    type = "rw"
  [[register.field]]
    name = "TZ_AT_EGR_0"
    bits = "5"
    type = "rw"
  [[register.field]]
    name = "TZ_DMA_REGS"
    bits = "4"
    type = "rw"
  [[register.field]]
    name = "TZ_MSIX_PBA"
    bits = "3"
    type = "rw"
  [[register.field]]
    name = "TZ_MSIX_TABLE"
    bits = "2"
    type = "rw"
  [[register.field]]
    name = "TZ_ECAM"
    bits = "1"
    type = "rw"
  [[register.field]]
    name = "TZ_BRIDGE_REGS"
    bits = "0"
    type = "rw"
[[register]]
  name = "SLCR_DPDMA"
  type = "mixed"
  width = 32
  description = "DisplayPort DMA TrustZone Setting."
  default = "0x00000001"
  offset = "0x00000040"
  [[register.field]]
    name = "RESERVED"
    bits = "31:1"
    type = "raz"
  [[register.field]]
    name = "TZ"
    bits = "0"
    type = "rw"
[[register]]
  name = "SLCR_GDMA"
  type = "rw"
  width = 8
  description = "FPD DMA Trustzone Settings."
  default = "0x000000FF"
  offset = "0x00000050"
  [[register.field]]
    name = "TZ"
    bits = "7:0"
    type = "rw"
[[register]]
  name = "SLCR_GIC"
  type = "rw"
  width = 1
  description = "APU GIC setting."
  default = "0x00000000"
  offset = "0x00000060"
  [[register.field]]
    name = "CFG_DISABLE"
    bits = "0"
    type = "rw"
