[[definition]]
type = "switch.i2c.zynqps8"
buses = [
    { name = "iopunitsswitch_i2c${index}", protocol = "internal_i2c", supplier = false, data_width = 32, address_width = 32 },
]
registers = [
    { resource = "zynqps8/i2c.toml", name = "I2C${index}", base_address = "0x0202_0000", address_increment = "0x1_0000" },
]
drivers = ["zynqps8.i2c"]
max_instances = 2
