# FPD domain
[[instance]]
name = "CCI"
type = "switch.internal.cci.zynqps8"

[[instance]]
name = "FPDMainSwitch"
type = "switch.internal.fpd.zynqps8"

[[instance]]
name = "SIOUSwitch"
type = "switch.internal.siouswitch.zynqps8"

[[instance]]
name = "SIOUOutboundSwitch"
type = "switch.internal.siououtbound.zynqps8"

[[instance]]
name = "GPU"
type = "graphic.gpu.mali400.zynqps8"

[[instance]]
name = "DP"
type = "graphic.display.displayport.zynqps8"

[[instance]]
name = "FPD_SLCR"
type = "other.internal.fpd_slcr.zynqps8"

[[instance]]
name = "FPDDMA"
type = "other.dma.fpd.zynqps8"

[[instance]]
name = "DP_HP0_MP"
type = "switch.internal.two_to_one_multiplexer.zynqps8"

[[instance]]
name = "HP1_HP2_MP"
type = "switch.internal.two_to_one_multiplexer.zynqps8"

[[instance]]
name = "HP3_FPDDMA_MP"
type = "switch.internal.two_to_one_multiplexer.zynqps8"

[[instance]]
name = "CORESIGHT_HPC0_HPC1_MP"
type = "switch.internal.three_to_one_multiplexer.zynqps8"

[[instance]]
name = "FPD_DDR_SPLITTER0"
type = "switch.internal.one_to_two_splitter.zynqps8"

[[instance]]
name = "FPD_DDR_SPLITTER1"
type = "switch.internal.one_to_two_splitter.zynqps8"

[[instance]]
name = "FPD_DDR_SPLITTER2"
type = "switch.internal.one_to_two_splitter.zynqps8"

# FPD connection
[[connection]]
type = "bus"
connection = "CCI -> FPDMainSwitch"
bus_name = "cci_fpd"

[[connection]]
type = "bus"
connection = "FPDMainSwitch -> SIOUSwitch"
bus_name = "fpd_siou"

[[connection]]
type = "logical"
connection = "FPDMainSwitch -> PS8Soc"

[[connection]]
type = "bus"
connection = "SIOUSwitch -> GPU"
bus_name = "siou_gpu"

[[connection]]
type = "bus"
connection = "SIOUOutboundSwitch -> CCI"
bus_name = "siou_cci"

[[connection]]
type = "bus"
connection = "GPU -> SIOUOutboundSwitch"
bus_name = "gpu_siououtbound"

[[connection]]
type = "bus"
connection = "SIOUSwitch -> FPD_SLCR"
bus_name = "siou_fpd_slcr"

[[connection]]
type = "bus"
connection = "SIOUSwitch -> DP"
bus_name = "siou_dp"

[[connection]]
type = "bus"
connection = "SIOUSwitch -> FPDDMA"
bus_name = "siou_fpddma"

[[connection]]
type = "bus"
connection = "FPDMainSwitch -> LPDInboundSwitch"
bus_name = "fpd_lpdinbound"

# Multiplexers
[[connection]]
type = "bus"
connection = "DP -> DP_HP0_MP"
bus_name = "dp_out"
consumer_bus_name = "in0"

[[connection]]
type = "logical"
connection = "PS8Soc -> DP_HP0_MP"
bus_name = "in1"

[[connection]]
type = "logical"
connection = "PS8Soc -> HP1_HP2_MP"
bus_name = "in0"
[[connection]]
type = "logical"
connection = "PS8Soc -> HP1_HP2_MP"
bus_name = "in1"

[[connection]]
type = "logical"
connection = "PS8Soc -> HP3_FPDDMA_MP"
bus_name = "in0"
[[connection]]
type = "logical"
connection = "FPDDMA -> HP1_HP2_MP"
bus_name = "in1"

#[[connection]]
#type = "logical"
#connection = "CORESIGHT -> CORESIGHT_HPC0_HPC1_MP"
#bus_name = "in0"
[[connection]]
type = "logical"
connection = "PS8Soc -> CORESIGHT_HPC0_HPC1_MP"
bus_name = "in1"
[[connection]]
type = "logical"
connection = "PS8Soc -> CORESIGHT_HPC0_HPC1_MP"
bus_name = "in2"
[[connection]]
type = "bus"
connection = "CORESIGHT_HPC0_HPC1_MP -> CCI"
bus_name = "out"


[[connection]]
type = "bus"
connection = "DP_HP0_MP -> FPD_DDR_SPLITTER0"
bus_name = "out"
consumer_bus_name = "in"

[[connection]]
type = "bus"
connection = "HP1_HP2_MP -> FPD_DDR_SPLITTER1"
bus_name = "out"
consumer_bus_name = "in"

[[connection]]
type = "bus"
connection = "HP3_FPDDMA_MP -> FPD_DDR_SPLITTER2"
bus_name = "out"
consumer_bus_name = "in"

[[connection]]
type = "bus"
connection = "FPD_DDR_SPLITTER0 -> FPDMainSwitch"
bus_name = "out0"
consumer_bus_name = "splitter0_fpd"

[[connection]]
type = "bus"
connection = "FPD_DDR_SPLITTER1 -> FPDMainSwitch"
bus_name = "out0"
consumer_bus_name = "splitter1_fpd"

[[connection]]
type = "bus"
connection = "FPD_DDR_SPLITTER2 -> FPDMainSwitch"
bus_name = "out0"
consumer_bus_name = "splitter2_fpd"

