#include "core/core.h"
#include "rom_extensions.h"
#include "hw/reg_access.h"
#include "hw/memory_map.h"
#include "hw_regs/crf_apb.h"

void A53Sleep0() {
	RomServiceTable[REN_ACPU0SLEEP]();
}
void A53Sleep1() {
	RomServiceTable[REN_ACPU1SLEEP]();
}
void A53Sleep2() {
	RomServiceTable[REN_ACPU2SLEEP]();
}
void A53Sleep3() {
	RomServiceTable[REN_ACPU3SLEEP]();
}

void A53Sleep() {
	RomServiceTable[REN_ACPU0SLEEP]();
	RomServiceTable[REN_ACPU1SLEEP]();
	RomServiceTable[REN_ACPU2SLEEP]();
	RomServiceTable[REN_ACPU3SLEEP]();
}
void R5FSleep0() {
	RomServiceTable[REN_R5F0SLEEP]();
}
void R5FSleep1() {
	RomServiceTable[REN_R5F1SLEEP]();
}

void R5FSleep() {
	RomServiceTable[REN_R5F0SLEEP]();
	RomServiceTable[REN_R5F1SLEEP]();
}

void A53WakeUp0() {
	// put apu in reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 0));
	RomServiceTable[REN_ACPU0WAKE]();
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 0));

}
void A53WakeUp1() {
	// put apu in reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 0));
	RomServiceTable[REN_ACPU1WAKE]();
	// take out of reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 0));
}
void A53WakeUp2() {
	// put apu in reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 1) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 1) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 0));
	RomServiceTable[REN_ACPU2WAKE]();
	// take out of reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 0));
}
void A53WakeUp3() {
	// put apu in reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 1));
	RomServiceTable[REN_ACPU3WAKE]();
	// take out of reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 0) |
								 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 0));
}

void A53WakeUp() {
	// put apu in reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 1) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 1));
	RomServiceTable[REN_ACPU0WAKE]();
	RomServiceTable[REN_ACPU1WAKE]();
	RomServiceTable[REN_ACPU2WAKE]();
	RomServiceTable[REN_ACPU3WAKE]();
	// take out of reset
	HW_REG_SET(CRF_APB, RST_FPD_APU,
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, APU_L2_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU0_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU1_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU2_RESET, 0) |
						 HW_REG_ENCODE_FIELD(CRF_APB, RST_FPD_APU, ACPU3_RESET, 0));
}

void R5FWakeUp0() {
	RomServiceTable[REN_R5F0WAKE]();
}
void R5FWakeUp1() {
	RomServiceTable[REN_R5F1WAKE]();
}

void R5FWakeUp() {
	RomServiceTable[REN_R5F0WAKE]();
	RomServiceTable[REN_R5F1WAKE]();
}
