actions = [
    "make_config",
    "sbt_run",
    "src",
    "read_verilog_top",
    "read_toml_registers"
]


[[process]]
name = 'make_config'
processor = 'toml'
filename = 'config.toml'
parameters = [
    "reset_clocks"
]

[[process]]
name = 'sbt_run'
processor = 'sbt'
main_scala = "apb_ctrl.scala"
with_build_sbt = true
args = '+runMain UartApbCtrl config.toml .. ${name}'

[[process]]
name = 'src'
processor = 'sources'
sources = [{ file = "${name}.v", language = "verilog" }]

[[process]]
name = 'read_verilog_top'
processor = 'read_verilog_top'
source = "${name}"

[[process]]
name = 'read_toml_registers'
processor = 'read_toml_registers'
source = "${name}_regs"
