path = "dma"

[[definition]]
type = "other.dma.lpd.zynqps8"
registers = [
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH0", base_address = "0x2a8_0000" }, #FD base
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH1", base_address = "0x2a9_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH2", base_address = "0x2aa_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH3", base_address = "0x2ab_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH4", base_address = "0x2ac_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH5", base_address = "0x2ad_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH6", base_address = "0x2ae_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH7", base_address = "0x2af_0000" },
]
buses = [
    { name = "iopinbound_lpddma", supplier = false, data_width = 32 },
    { name = "lpddma_lpdoutbound", supplier = true, data_width = 128 },
]

[[definition]]
type = "other.dma.fpd.zynqps8"
registers = [
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH0", base_address = "0x50_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH1", base_address = "0x51_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH2", base_address = "0x52_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH3", base_address = "0x53_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH4", base_address = "0x54_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH5", base_address = "0x55_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH6", base_address = "0x56_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH7", base_address = "0x57_0000" },
]
buses = [
    { name = "siou_fpddma", supplier = false, data_width = 32 },
    { name = "out", supplier = true, data_width = 128 },
]
