path = "dma"

[[definition]]
type = "other.dma.lpd.zynqps8"
registers = [
    # 0xffa80000
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH0", base_address = "0xa8_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH1", base_address = "0xa9_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH2", base_address = "0xaa_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH3", base_address = "0xab_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH4", base_address = "0xac_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH5", base_address = "0xad_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH6", base_address = "0xae_0000" },
    { resource = "zynqps8/zdma.toml", name = "LPD_DMA_CH7", base_address = "0xaf_0000" },
]
buses = [
    { name = "iopinbound_lpddma", supplier = false, data_width = 32 },
    { name = "lpddma_lpdoutbound", supplier = true, data_width = 128 },
]

[[definition]]
type = "other.dma.fpd.zynqps8"
registers = [
    # 0xffa80000
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH0", base_address = "0xa8_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH1", base_address = "0xa9_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH2", base_address = "0xaa_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH3", base_address = "0xab_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH4", base_address = "0xac_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH5", base_address = "0xad_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH6", base_address = "0xae_0000" },
    { resource = "zynqps8/zdma.toml", name = "FPD_DMA_CH7", base_address = "0xaf_0000" },
]
buses = [
    { name = "fpd_fpddma", supplier = false, data_width = 32 },
    { name = "internal_multiplexer1", supplier = true, data_width = 128 },
]
