[[include]]
resource = "x86_64_linux_host.toml"

[[definition]]
type = "cpu.riscv32im.vexriscv_smallest"
triple = "riscv32-none-elf"
width = 32
gateware = "vexriscv/vexriscv_smallest.toml"
supplier_prefix = ["dBus_", "iBus_"]

# 3 types hard CPUs for zynqps8
[[include]]
resource = "zynqps8/a53.toml"
[[include]]
resource = "zynqps8/r5f.toml"
[[include]]
resource = "zynqps8/pmu.toml"
