actions = [
    "src",
    "read_verilog_top"
]

[parameters]
ADDR_WIDTH = 32 # Width of address bus in bits
AXI_DATA_WIDTH = 32 # Width of input (slave) AXI interface data bus in bits
AXI_ID_WIDTH = 8 # Width of AXI ID signal
AXIL_DATA_WIDTH = 32 # Width of output (master) AXI lite interface data bus in bits
CONVERT_BURST = 1 # When adapting to a wider bus, re-pack full-width burst instead of passing through narrow burst if possible
CONVERT_NARROW_BURST = 0 # When adapting to a wider bus, re-pack all bursts instead of passing through narrow burst if possible

[[process]]
name = 'src'
processor = 'sources'
sources = [
    { file = "rtl/axi_axil_adapter.v", language = "verilog" },
    { file = "rtl/axi_axil_adapter_rd.v", language = "verilog" },
    { file = "rtl/axi_axil_adapter_wr.v", language = "verilog" }
]

[[process]]
name = 'read_verilog_top'
processor = 'read_verilog_top'
source = "rtl/axi_axil_adapter.v"
