path = "buses"

[[definition]]
type = "bus.pipelined_memory_bus.spinal"
gateware = "spinal/pipelined_memory_bus/pipelined_memory_bus.toml"

[[definition]]
type = "bus.advanced_peripheral_bus.spinal"
gateware = "spinal/advanced_peripheral_bus/advanced_peripheral_bus.toml"

