[[definition]]
  type = "cpu.a53"
  arch = "arm8-a"
  width = 64

[[definition]]
  type = "cpu.r5f"
  arch = "arm7-a"
  width = 32

[[definition]]
  type = "cpu.pmu"
  arch = "microblaze"
  width = 32
