registerPath = "ZynqPs8"

[[definition]]
  type = "soc.zynqps8"

[[definition]]
  type = "cpu.a53"
  arch = "arm8-a"
  width = 64
  software = [
    "a53_cti",
    "a53_dbg",
    "a53_etm",
    "a53_pmu",
    "a53_rom"
  ]

[[definition]]
  type = "cpu.r5f"
  arch = "arm7-a"
  width = 32
  software = [
    "r5_dbg",
    "r5_etm",
    "r5_rom"
  ]

[[definition]]
  type = "cpu.pmu"
  arch = "microblaze"
  width = 32
  software = [
    "pmu_global",
    "pmu_iomodule",
    "pmu_local"
  ]

[[definition]]
  type = "ram.sram.tcm"
  size = "128 KiB"

[[definition]]
  type = "ram.sram.pmuram"
  size = "128 KiB"

[[definition]]
  type = "ram.sram.ocp"
  size = "256 KiB"

[[definition]]
  type = "NxMinterconnect.axi4"

[[definition]]
  type = "NxMinterconnect.apb"

[[definition]]
  type = "connection.apb"

[[definition]]
  type = "connection.axi4"

[[definition]]
  type = "connection.tcm"

[[definition]]
  type = "connection.ocp"

[[definition]]
  type = "connection.pmuram"

[[definition]]
  type = "connection.ddr4"

[[definition]]
  type = "bridge.i2c.axi4"

[[definition]]
  type = "bridge.apb.axi4"

[[definition]]
  type = "net.ethernet.zynqps8"
  software = ["gem"]

[[definition]]
  type = "storage.sdio.zynqps8"
  software = ["sdio"]

[[definition]]
  type = "storage.qspi.zynqps8"
  software = ["qspi"]