path = "ZynqPs8"

[[definition]]
	type = "cpu.a53"
	arch = "arm8-a"
	triple = "aarch64-none-elf"
	width = 64
	core_count = 4

	software = [
		{ registers = "a53_cti" },
		{ registers = "a53_dbg" },
		{ registers = "a53_etm" },
		{ registers = "a53_pmu" },
		{ registers = "a53_rom" },
	]

[[definition]]
	type = "cpu.r5f"
	arch = "arm7-a"
	triple = "arm-none-elf"
	width = 32
	core_count = 2
	software = [
		{ registers = "r5_dbg" },
		{ registers = "r5_etm" },
		{ registers = "r5_rom" },
	]

[[definition]]
	type = "cpu.pmu"
	arch = "microblaze"
	triple = "mircroblaze-none-elf"
	width = 32
	core_count = 1
	software = [
		{ registers = "pmu_global" },
		{ registers = "pmu_iomodule" },
		{ registers = "pmu_local" },
	]

# tcm is 256KiB in lock step mode or 128K in dual core mode
# Doesn't really matter we put here as the bus will split and portion correctly
[[definition]]
	type = "ram.sram.tcm"
	size_in_bytes = "256 KiB"

[[definition]]
	type = "ram.sram.pmuram"
	size_in_bytes = "128 KiB"

[[definition]]
	type = "ram.sram.ocp"
	size_in_bytes = "256 KiB"

[[definition]]
	type = "ram.ddr.ddr4.MT40A256M16LY"
	size_in_bytes = "4 GiB"

[[definition]]
	type = "bus.axi4"

[[definition]]
	type = "bus.apb"

[[definition]]
	type = "bridge.i2c.axi4"

[[definition]]
	type = "bridge.apb.axi4"

[[definition]]
	type = "other.uart.zynqps8"
	software = [{registers = "uart", bankPrefix = "USB"}]
	hardware = [{max_cores = 2}]

[[definition]]
	type = "net.ethernet.zynqps8"
	software = [{registers = "gem", bankPrefix = "ENET"}]
	hardware = [{max_cores = 4}]

[[definition]]
	type = "storage.sdio.zynqps8"
	software = [{registers = "sdio", bankPrefix = "SD"}]
	hardware = [{max_cores = 2}]

[[definition]]
	type = "storage.qspi.zynqps8"
	software = [{registers = "qspi", bankPrefix = "QSPI"}]
