[[definition]]
type = "switch.internal.cci.zynqps8"
registers = [
    { resource = "registers/cci400.toml", name = "CCI_GPV", base_address = "0x006e_0000" },
    { resource = "registers/cci_reg.toml", name = "CCI_REG", base_address = "0x005e_0000" },
]
buses = [
    { name = "apu_cci", supplier = false, data_width = 128, address_width = 40 },
    { name = "hpcmulti_cci", supplier = false, data_width = 128, address_width = 40 },
    { name = "siou_cci", supplier = false, data_width = 128, address_width = 40 },
    { name = "cci0_ddrc", supplier = true, data_width = 128, address_width = 40 },
    { name = "cci1_ddrc", supplier = true, data_width = 128, address_width = 40 },
    { name = "cci_fpd", supplier = true, data_width = 128, address_width = 40 },
]

[[definition]]
type = "switch.internal.fpd.zynqps8"
registers = [
    { resource = "registers/fpd/crf_apb.toml", name = "CRF_APB", base_address = "0x1a_0000" },
    { resource = "registers/fpd/fpd_gpv.toml", name = "FPD_GPV", base_address = "0x70_0000" },
]

buses = [
    { name = "cci_fpd", supplier = false, data_width = 128, address_width = 40 },
    { name = "splitter0_fpd", supplier = false },
    { name = "splitter1_fpd", supplier = false },
    { name = "splitter2_fpd", supplier = false },
    { name = "fpd_siou", supplier = true, data_width = 64, address_width = 40 },
    { name = "fpd_ocm", supplier = true, base_address = "0x200_0000", data_width = 128, address_width = 18 },
    { name = "fpd_hpm{$index}", supplier = true, data_width = 128, address_width = 18 },
    { name = "fpd_lpdinbound", supplier = true, data_width = 64, address_width = 40 },
]


[[definition]]
type = "switch.internal.siouswitch.zynqps8"
registers = [
    { resource = "registers/siou.toml", name = "SIOU", base_address = "0x3d_0000" },
    { resource = "registers/serdes.toml", name = "SERDES", base_address = "0x40_0000" },
]
buses = [
    { name = "fpd_siou", supplier = false, data_width = 64, address_width = 32 },
    { name = "siou_gpu", supplier = true, data_width = 128 },
    { name = "siou_sata", supplier = true, data_width = 32 },
    { name = "siou_pcie", supplier = true, data_width = 32 },
    { name = "siou_dp", supplier = true, data_width = 32 },
    { name = "siou_fpddma", supplier = true, data_width = 32 },
    { name = "siou_fpd_config", supplier = true, data_width = 32 },
    { name = "siou_fpd_slcr", supplier = true, data_width = 32 },
]


[[definition]]
type = "switch.internal.siououtbound.zynqps8"
buses = [
    { name = "gpu_siououtbound", supplier = false, data_width = 64, address_width = 32 },
    { name = "sata_siououtbound", supplier = false, data_width = 64, address_width = 32 },
    { name = "pcie_siououtbound", supplier = false, data_width = 64, address_width = 32 },
    { name = "siou_cci", supplier = true, data_width = 128, address_width = 18 },
]

[[definition]]
type = "other.internal.fpd_slcr.zynqps8"
registers = [
    { resource = "registers/fpd/fpd_slcr.toml", name = "FPD_SLCR", base_address = "0x61_0000" },
    { resource = "registers/fpd/fpd_slcr_secure.toml", name = "FPD_SLCR_SECURE", base_address = "0x69_0000" },
]
buses = [
    { name = "siou_fpd_slcr", supplier = false },
]

[[definition]]
type = "switch.internal.three_to_one_multiplexer.zynqps8"
buses = [
    { name = "in0", supplier = false },
    { name = "in1", supplier = false },
    { name = "in2", supplier = false },
    { name = "out", supplier = true },
]

[[definition]]
type = "switch.internal.two_to_one_multiplexer.zynqps8"
buses = [
    { name = "in0", supplier = false },
    { name = "in1", supplier = false },
    { name = "out", supplier = true },
]

[[definition]]
type = "switch.internal.one_to_two_splitter.zynqps8"
buses = [
    { name = "in", supplier = false },
    { name = "out0", supplier = true },
    { name = "out1", supplier = true },
]
