path = "prefabs/socs/zynqps8"

[[prefab]]
name = "socs.zynqps8.fabric"

[[prefab]]
name = "socs.zynqps8.a53"

[[prefab]]
name = "socs.zynqps8.r5f"

[[prefab]]
name = "socs.zynqps8.pmu"

# boot rom
[[instance]]
type = "program.bootrom.zynqps8"

[[instance]]
type = "program.pmu_monitor"
