[[instance]]
name = "RawPS8"
type = "other.zynqps8.rawps8"

[[instance]]
name = "apbBus"
type = "bus.apb.zynqps8"

[[instance]]
name = "mainBus"
type = "bus.axi4.zynqps8"

[[instance]]
name = "mainBus_to_APB"
type = "bridge.internal.mainbus_to_apb"

[[instance]]
name = "mainDDR4"
type = "ram.ddr.ddr4.zynqps8"


[[connection]]
type = "logical"
connection = "mainBus_to_APB -> apbBus"

[[connection]]
type = "bus"
connection = "mainBus -> mainBus_to_APB"
address_offset = "0xFF00_0000"

[[connection]]
type = "bus"
connection = "RawPS8 -> mainBus"
address_offset = "0"
