# FPD domain
[[instance]]
name = "CCI"
type = "switch.internal.cci.zynqps8"

[[instance]]
name = "FPDMainSwitch"
type = "switch.internal.fpd.zynqps8"

[[instance]]
name = "SIOUSwitch"
type = "switch.internal.siouswitch.zynqps8"

[[instance]]
name = "SIOUOutboundSwitch"
type = "switch.internal.siououtbound.zynqps8"

[[instance]]
name = "GPU"
type = "graphic.gpu.mali400.zynqps8"

[[instance]]
name = "DP"
type = "graphic.display.displayport.zynqps8"

[[instance]]
name = "FPD_SLCR"
type = "other.internal.fpd_slcr.zynqps8"
[[instance]]
name = "FPDDMA"
type = "other.dma.fpd.zynqps8"

[[instance]]
name = "DP_HP0_MULTIPLEXER"
type = "switch.internal.two_to_one_multiplexer.zynqps8"

[[instance]]
name = "HP1_HP2_MULTIPLEXER"
type = "switch.internal.two_to_one_multiplexer.zynqps8"

[[instance]]
name = "HP3_FPDDMA_MULTIPLEXER"
type = "switch.internal.two_to_one_multiplexer.zynqps8"

[[instance]]
name = "FPD_DDR_SPLITTER0"
type = "switch.internal.one_to_two_splitter.zynqps8"

[[instance]]
name = "FPD_DDR_SPLITTER1"
type = "switch.internal.one_to_two_splitter.zynqps8"

[[instance]]
name = "FPD_DDR_SPLITTER2"
type = "switch.internal.one_to_two_splitter.zynqps8"

# FPD connection
[[connection]]
type = "bus"
connection = "CCI -> FPDMainSwitch"
bus_name = "cci_fpd"

[[connection]]
type = "bus"
connection = "FPDMainSwitch -> SIOUSwitch"
bus_name = "fpd_siou"

[[connection]]
type = "logical"
connection = "FPDMainSwitch -> PS8Soc"
bus_name = "fpd_hpm{$index}"

[[connection]]
type = "logical"
connection = "FPDMainSwitch -> PS8Soc"
bus_name = "fpd_hpm{$index}"

[[connection]]
type = "bus"
connection = "SIOUSwitch -> GPU"
bus_name = "siou_gpu"

[[connection]]
type = "bus"
connection = "SIOUOutboundSwitch -> CCI"
bus_name = "siou_cci"

[[connection]]
type = "bus"
connection = "GPU -> SIOUOutboundSwitch"
bus_name = "gpu_siououtbound"

[[connection]]
type = "bus"
connection = "SIOUSwitch -> FPD_SLCR"
bus_name = "siou_fpd_slcr"

[[connection]]
type = "bus"
connection = "SIOUSwitch -> DP"
bus_name = "siou_dp"

[[connection]]
type = "bus"
connection = "FPDMainSwitch -> FPDDMA"
bus_name = "fpd_fpddma"

[[connection]]
type = "bus"
connection = "DP -> DP_HP0_MULTIPLEXER"
bus_protocol = "internal_multiplexer0"
[[connection]]
type = "logical"
connection = "PS8Soc -> DP_HP0_MULTIPLEXER"
bus_protocol = "internal_multiplexer1"

[[connection]]
type = "logical"
connection = "PS8Soc -> HP1_HP2_MULTIPLEXER"
bus_protocol = "internal_multiplexer0"
[[connection]]
type = "logical"
connection = "PS8Soc -> HP1_HP2_MULTIPLEXER"
bus_protocol = "internal_multiplexer1"

[[connection]]
type = "logical"
connection = "PS8Soc -> HP3_FPDDMA_MULTIPLEXER"
bus_protocol = "internal_multiplexer0"
[[connection]]
type = "logical"
connection = "FPDDMA -> HP1_HP2_MULTIPLEXER"
bus_protocol = "internal_multiplexer1"

[[connection]]
type = "bus"
connection = "DP_HP0_MULTIPLEXER -> FPD_DDR_SPLITTER0"
bus_protocol = "internal_splitter"

[[connection]]
type = "bus"
connection = "HP1_HP2_MULTIPLEXER -> FPD_DDR_SPLITTER1"
bus_protocol = "internal_splitter"

[[connection]]
type = "bus"
connection = "HP3_FPDDMA_MULTIPLEXER -> FPD_DDR_SPLITTER2"
bus_protocol = "internal_splitter"

[[connection]]
type = "bus"
connection = "FPD_DDR_SPLITTER0 -> FPDMainSwitch"
bus_protocol = "internal_splitter_out"

[[connection]]
type = "bus"
connection = "FPD_DDR_SPLITTER1 -> FPDMainSwitch"
bus_protocol = "internal_splitter_out"

[[connection]]
type = "bus"
connection = "FPD_DDR_SPLITTER2 -> FPDMainSwitch"
bus_protocol = "internal_splitter_out"
