#IOP domain
[[instance]]
name = "IOPInboundSwitch"
type = "switch.internal.iopinbound.zynqps8"

[[instance]]
name = "IOPUnitsSwitch"
type = "switch.internal.iopunitsswitch.zynqps8"

[[instance]]
name = "IOPOutboundSwitch"
type = "switch.internal.iopoutbound.zynqps8"

[[instance]]
name = "LPDDMA"
type = "other.dma.lpd.zynqps8"

# IOP connections

[[connection]]
type = "bus"
connection = "IOPOutboundSwitch -> LPDMainSwitch"
bus_name = "iopoutbound_lpd"

# UARTs
[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> UART0"
bus_name = "iopunitsswitch_uart${index}"
silent = true

[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> UART1"
bus_name = "iopunitsswitch_uart${index}"
silent = true

# CANs
[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> CAN0"
bus_name = "iopunitsswitch_can${index}"
silent = true

[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> CAN1"
bus_name = "iopunitsswitch_can${index}"
silent = true

# I2Cs
[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> I2C0"
bus_protocol = "internal_i2c"
silent = true

[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> I2C1"
bus_protocol = "internal_i2c"
silent = true

# USBs
[[connection]]
type = "bus"
connection = "IOPInboundSwitch -> USB0"
bus_name = "iopinbound_usb${index}"
silent = true

[[connection]]
type = "bus"
connection = "IOPInboundSwitch -> USB1"
bus_name = "iopinbound_usb${index}"
silent = true

[[connection]]
type = "bus"
connection = "USB0 -> LPDOutboundSwitch"
bus_name = "usb0_lpdoutbound"
silent = true

[[connection]]
type = "bus"
connection = "USB1 -> LPDOutboundSwitch"
bus_name = "usb${index}_lpdoutbound"
silent = true

# GEMs (ethernet)
[[connection]]
type = "bus"
connection = "IOPInboundSwitch -> Gem0"
bus_name = "iopunitsswitch_gem${index}"
silent = true

[[connection]]
type = "bus"
connection = "Gem0 -> IOPOutboundSwitch"
bus_name = "gem${index}_iopoutbound"
silent = true

# SDIO
[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> SDIO0"
bus_name = "iopunitsswitch_sdio${index}"
silent = true

[[connection]]
type = "bus"
connection = "SDIO0 -> IOPOutboundSwitch"
bus_name = "sdio${index}_iopoutbound"
silent = true

[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> SDIO1"
bus_name = "iopunitsswitch_sdio${index}"
silent = true

[[connection]]
type = "bus"
connection = "SDIO1 -> IOPOutboundSwitch"
bus_name = "sdio${index}_iopoutbound"
silent = true

# QuadSPI
[[connection]]
type = "bus"
connection = "IOPUnitsSwitch -> QSPI"
bus_name = "iopunitsswitch_quadspi"
silent = true

[[connection]]
type = "bus"
connection = "QSPI -> IOPOutboundSwitch"
bus_name = "quadspi_iopoutbound"
silent = true


# DMA
[[connection]]
type = "bus"
connection = "IOPInboundSwitch -> LPDDMA"
bus_name = "iopinbound_lpddma"

[[connection]]
type = "bus"
connection = "LPDDMA -> LPDOutboundSwitch"
bus_name = "lpddma_lpdoutbound"

