path = "prefabs/socs/zynqps8"

[[instance]]
name = "pmu"
type = "cpu.zynqps8.pmu"

[[instance]]
name = "pmuRAM"
type = "ram.sram.pmuram"

[[instance]]
name = "pmuInternalBus"
type = "bus.internal.pmu"

[[instance]]
name = "pmu_to_mainBus"
type = "bridge.internal.pmu_to_mainbus"

[[connection]]
type = "logical"
connection = "pmu -> pmuInternalBus"

[[connection]]
type = "bus"
connection = "pmuInternalBus -> pmuRAM"
address_offset = "0xFFDC_0000"

[[connection]]
type = "logical"
connection = "pmuInternalBus -> pmu_to_mainBus"

[[connection]]
type = "bus"
connection = "pmu_to_mainBus -> mainBus"
address_offset = "0"

[[connection]]
type = "bus"
connection = "mainBus -> pmuRAM"
address_offset = "0xFFDC_0000"
