path = "prefabs/socs/zynqps8"

[[instance]]
name = "RPU"
type = "cpu.r5f.zynqps8"

[[instance]]
name = "RPU_to_TCM"
type = "switch.internal.tcm.zynqps8"

[[connection]]
type = "bus"
connection = "RPU -> RPU_to_TCM"
bus_name = "rputcm"

[[instance]]
name = "RPUTCM"
type = "ram.sram.tcm.zynqps8"

[[connection]]
type = "logical"
connection = "RPU_to_TCM -> RPUTCM"

[[connection]]
type = "bus"
connection = "RPU -> RPUSwitch"
bus_name = "rpu0"

[[connection]]
type = "bus"
connection = "RPU -> RPUSwitch"
bus_name = "rpu1"

[[connection]]
type = "bus"
connection = "RPUIOSwitch -> RPU"
bus_name = "rpus${index}"

[[connection]]
type = "bus"
connection = "RPUIOSwitch -> RPU"
bus_name = "rpus${index}"
