path = "prefabs/socs/zynqps8"

[[instance]]
name = "r5fCluster"
type = "cpu.zynqps8.r5f"

[[instance]]
name = "r5fClusterTCM"
type = "ram.sram.tcm"

[[instance]]
name = "r5fClusterInternalBus"
type = "bus.internal.r5f"

[[instance]]
name = "r5fCluster_to_mainBus"
type = "bridge.internal.r5f_to_mainbus"

[[connection]]
type = "logical"
connection = "r5fCluster -> r5fClusterInternalBus"

[[connection]]
type = "bus"
connection = "r5fClusterInternalBus -> r5fClusterTCM"

[[connection]]
type = "logical"
connection = "r5fClusterInternalBus -> r5fCluster_to_mainBus"

[[connection]]
type = "bus"
connection = "r5fCluster_to_mainBus -> mainBus"

[[connection]]
type = "bus"
connection = "mainBus -> r5fClusterTCM"
address_offset = [
    ["0xFFE0_0000", "64 KiB"],
    ["0xFFE2_0000", "64 KiB"],
    ["0xFFE9_0000", "64 KiB"],
    ["0xFFEB_0000", "64 KiB"]
]
