[[definition]]
type = "io.uart.apb_ctrl"
gateware = "apb_ctrl/apb_ctrl.toml"
consumer_prefix = "apb_"

[[definition]]
type = "io.uart.zynqps8"
registers = [
    { resource = "zynqps8/uart.toml", name = "UART${index}", base_address = "0x0200_0000", address_increment = "0x1_0000", register_window_size = "64 KiB" }
]
buses = [
    { name = "iopunitsswitch_uart${index}", supplier = false },
]

max_instances = 2