name: Clean Compile and Run tests

on:
  workflow_run:
    workflows: ["Scala CI"]
    types:
      - completed
  workflow_dispatch:  # Allows manual triggering

jobs:
  compile-and-run-tests:
    runs-on: ubuntu-latest
    # Only run if the Scala CI workflow succeeded or this was manually triggered
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive  # Fetches all submodules recursively
      
    # Set up minimal environment for running the application
    - name: Set up JDK 17
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
        
    - name: Install sbt (only for manual trigger)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install sbt
    
    # For workflow_run triggers, download artifacts from the previous workflow
    - name: Download target directory from previous workflow
      if: ${{ github.event_name == 'workflow_run' }}
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: scala.yml
        name: target-directory
        path: target/
        
    # For manual triggers, we need to compile from scratch
    - name: Clean compile (only for manual trigger)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: sbt clean compile
      
    - name: Stage application (only for manual trigger)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: sbt universal:stage
      
    - name: Check executable existence
      run: |
        if [ ! -f target/universal/stage/bin/overlord ]; then
          echo "ERROR: The overlord executable was not found at target/universal/stage/bin/overlord"
          echo "This could be because the universal:stage task did not run correctly."
          echo "Directory contents of target/universal/stage/bin:"
          ls -la target/universal/stage/bin/ || echo "Directory doesn't exist"
          echo "Directory contents of target/universal/stage:"
          ls -la target/universal/stage/ || echo "Directory doesn't exist"
          exit 1
        else
          echo "Found overlord executable at target/universal/stage/bin/overlord"
        fi

    - name: Run tests
      run: sbt test

    - name: Verify test results
      run: |
        if [ $? -ne 0 ]; then
          echo "ERROR: Tests failed."
          exit 1
        else
          echo "All tests passed successfully."
        fi

