name: Scala CI

# Trigger the workflow on pushes and pull requests to the main or master branches.
# Ignore changes to files in the .devcontainer directory and the overlord_template_project submodule.
on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '.devcontainer/**'
      - 'overlord_template_project/**'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'overlord.code-workspace'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '.devcontainer/**'
      - 'overlord_template_project/**'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'overlord.code-workspace'

jobs:
  build:
    # Use the latest Ubuntu runner for the build job.
    runs-on: ubuntu-latest

    steps:
    # Check out the repository, including all submodules.
    - uses: actions/checkout@v3
      with:
        submodules: recursive  # Fetches all submodules recursively

    # Set up JDK 17 using the Temurin distribution.
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'

    # Install sbt (Scala Build Tool) on the runner.
    - name: Install sbt
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install sbt

    # Run the test suite using sbt.
    - name: Run tests
      run: sbt test

    # Build the project into a JAR file using sbt-assembly.
    - name: Build package
      run: sbt assembly

    # Create a universal package for deployment using sbt.
    - name: Create universal package
      run: sbt universal:stage

    # Upload the target directory as an artifact for use in subsequent workflows.
    - name: Upload target directory
      uses: actions/upload-artifact@v4
      with:
        name: target-directory
        path: target/
        retention-days: 1