name: Scala CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Install sbt
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install sbt
    - name: Run tests
      run: sbt test
    - name: Build package
      run: sbt assembly
      
    # Upload build artifacts for use in subsequent workflows
    - name: Upload target directory
      uses: actions/upload-artifact@v3
      with:
        name: target-directory
        path: target/
        retention-days: 1